### ISSUE TITLE
Test names for some webaudio tests are not consistent (breaks reporting)

### ISSUE THREAD

**Issue by thejohnjansen** [web-platform-tests/wpt#10201]
If you look at this test file: https://github.com/w3c/web-platform-tests/blob/master/webaudio/the-audio-api/the-iirfilternode-interface/iirfilter-getFrequencyResponse.html

It seems as though the test names are generated based on the performance of the test itself. This means that test names are always coming up different, and there is no way to compare one run to the next (or one browser to the next). 

I don't think we got around to discussing test names at the last TPAC meeting, but I was hoping we could have consistent names so I can always say, "we consistently pass this test". I tried to see how WPT.FYI is dealing with this, but the subdirectory of tests is not being reported.

**Comment by foolip** [comment]
There are results for this here, and they look pretty funny:
https://wpt.fyi/webaudio/the-audio-api/the-iirfilternode-interface/iirfilter-getFrequencyResponse.html?sha=ecd2c46c1a

**Comment by foolip** [comment]
@rtoy, this test came from https://chromium-review.googlesource.com/c/chromium/src/+/909306, can you take a look at whether the test names are deterministic?

**Comment by rtoy** [comment]
Sorry for the long delay!  I need better filters for my wpt emails.

Yes, the tests include bits of the actual test output (frequency response) as part of the message. (A hold-over from porting our audit system to testharness.)

The test output should be consistent for each browser, but not between browsers because the actual frequency response values may differ between browsers.  And they could be different between browser  version if the internal implementation causes the actual response to change.  That's something we do want to catch.

I know this has come up before, but seeing the expected output has been immensely helpful in understanding the test results.

**Comment by foolip** [comment]
@rtoy I take it knowing the expected frequency is helpful even if the test passes? If not, it could simply be moved to an assertion with a good message.

If you want extra information even when passing, I think what would fix it is additional per-subtest metadata that has no effect on passing or failing, but is shown on wpt.fyi and Chromium's baselines.

P.S. https://web-platform-tests.org/reviewing-tests/email.html has some suggestions for mail filters that aren't well documented elsewhere.

**Comment by karlt** [comment]
Some discussion has resumed on https://github.com/web-platform-tests/wpt/issues/12781.
