### ISSUE TITLE
Run PRs on Taskcluster

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#10503]
If https://github.com/w3c/web-platform-tests/pull/9226 works out, it's an obvious next step to also run some subset of the tests for PRs, probably replacing the Travis runs that so often time out: https://github.com/w3c/web-platform-tests/issues/7660

**Comment by jugglinmike** [comment]
In TravisCI today, we script unnecessary jobs to exit early. This avoids unnecessary work, but it also makes task reports a little noisy (since they include meaningless results for those no-op jobs).

A nice-to-have improvement would be to use TaskCluster's "decision tasks" feature to avoid scheduling unnecessary tasks. @jgraham found an example of a GitHub project using a TaskCluster decision task here:

https://github.com/mozilla/normandy/blob/26b6537d7b6a0986f30f58bfb4c0d85ad8a6eea1/ci/taskcluster/bin/decision.py

**Comment by jgraham** [comment]
https://github.com/lissyx/taskcluster-github-decision/blob/master/tc-decision.py is another example to crib from.

**Comment by foolip** [comment]
This issue could be split into a bunch of smaller ones, basically one for each Travis job we have. The one that I was thinking about when filing this issue was test running itself. A decision task that looks at the affected tests and picks some number of tasks to get the job done, perhaps up to as many as are used for master builds if testharness.js itself is changed.
