### ISSUE TITLE
MISSING-TESTDRIVER-VENDOR is not documented

### ISSUE THREAD

**Issue by marcoscaceres** [web-platform-tests/wpt#10501]
The linter tells me to go to: 
http://web-platform-tests.org/writing-tests/lint-tool.html

But MISSING-TESTDRIVER-VENDOR doesn't seem to be documented.

**Comment by jugglinmike** [comment]
We just merged gh-17189, so the online documentation of the lint tool now describes every available rule (including MISSING-TESTDRIVER-VENDOR):

https://web-platform-tests.org/writing-tests/lint-tool.html

And because that list is programmatically generated, we can have more confidence that the documentation will remain up-to-date as the rule set changes.
