### ISSUE TITLE
/workers/opaque-origin.html is disabled/flaky in chromium webkit

### ISSUE THREAD

**Issue by zcorpan** [web-platform-tests/wpt#11188]
http://bocoup.github.io/wpt-disabled-tests-report/

Investigate what's up with this test:

Path | Products | Results | Bugs
-- | -- | -- | --
/workers/opaque-origin.html | chromium webkit | [ Failure Crash Timeout ] [ Skip ] | https://crbug.com/626703 None

cc @mkruisselbrink

I think the issue is that the test isn't enabling the port message queue, it needs `channel.port1.start();`

**Comment by mkruisselbrink** [comment]
As mentioned on the pull request it seems the issue is that fetch_tests_from_worker used to auto-start the port (because it assigned to onmessage), and that later was changed to addEventListener('message', ...) instead. So presumably that could effect more than just this test (unless there is special code already to make sure a shared worker's port is started for example)?

**Comment by zcorpan** [comment]
@foolip can you update TestExpectations for chromium?

@cdumez can you update TestExpectations for webkit?

**Comment by foolip** [comment]
Test enabled in https://chromium-review.googlesource.com/1140053.

**Comment by zcorpan** [comment]
Filed https://bugs.webkit.org/show_bug.cgi?id=197705 to get the test enabled in WebKit.
