### ISSUE TITLE
Make fetch_tests_from_worker et al non-racy

### ISSUE THREAD

**Issue by zcorpan** [web-platform-tests/wpt#11406]
See https://github.com/web-platform-tests/wpt/pull/11405

We could investigate making it non-racy to use more than one of these functions in a test.

Files with multiple `fetch_tests_*`:
```
$ grep -rc "fetch_tests_" . | grep -vE ":[01]$"
./tools/serve/serve.pyc:3
./tools/serve/serve.py:3
./tools/serve/__pycache__/serve.cpython-36.pyc:3
./streams/generate-test-wrappers.js:2
./resources/test/tests/functional/iframe-consolidate-errors.html:3
./resources/test/tests/functional/iframe-consolidate-tests.html:3
./resources/testharness.js:10
./docs/_writing-tests/testharness-api.md:9
./content-security-policy/inside-worker/dedicated-inheritance.html:7
./content-security-policy/inside-worker/dedicated-script.html:7
./content-security-policy/inside-worker/shared-inheritance.html:3
./content-security-policy/inside-worker/shared-script.html:3
./fetch/range/sw.https.window.js:2
./workers/name-property.html:4
./workers/opaque-origin.html:2
./service-workers/service-worker/client-navigate.https.html:5
```

**Comment by zcorpan** [comment]
@jgraham said in irc

> Test order explicitly isn't part of the contract provided by testharness.js, so if the selftests are trying to enforce that, they shouldn't

So another fix is to normalize the order of the tests before comparing.

**Comment by foolip** [comment]
Right, the fact that subtest order isn't guaranteed means that wpt.fyi and anything else showing/comparing results needs to ignore order. @Hexcles, I think we've also discussed this problem in Chromium because it affects our -expected.txt files, but decided to just treat those tests as flaky because there weren't that many. I can't find the issue now, do you recall?

Closing since this has the infra label and I'm doing triage :)

**Comment by zcorpan** [comment]
This needs a fix for the tests under resources/ so reopening.
