### ISSUE TITLE
Documentation for lint rule CONTENT-VISUAL missing

### ISSUE THREAD

**Issue by marcoscaceres** [web-platform-tests/wpt#11479]
The docs are missing "CONTENT-VISUAL": 
https://web-platform-tests.org/writing-tests/lint-tool.html

The linting message is not very helpful - it doesn't really say why a particular file was flagged as "CONTENT-VISUAL". The linting message just says to  get around the problem by adding it to `lint.whitelist`, but that feels kinda wrong and getting around the problem.

**Comment by marcoscaceres** [comment]
For reference: 
https://travis-ci.org/web-platform-tests/wpt/jobs/391363836

**Comment by jugglinmike** [comment]
We just merged gh-17189, so the online documentation of the lint tool now describes every available rule (including CONTENT-VISUAL):

https://web-platform-tests.org/writing-tests/lint-tool.html

And because that list is programmatically generated, we can have more confidence that the documentation will remain up-to-date as the rule set changes.
