### ISSUE TITLE
Some sort of governance/process

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#11473]
This is something that's mostly been discussed on IRC at various points.

There's a number of issues here:

 * Where do policy decisions get made? (The status quo appears to be all over the place.)
 * How do we ensure interested parties are aware of where the decisions are being made? (The status quo appears to be random subsets of people.)
 * Is there anyone to whom you can appeal the decision?

cc/ @web-platform-tests/admins @annevk @domenic (who I think are the two who have brought this up most often?)

**Comment by foolip** [comment]
> Where do policy decisions get made?

> How do we ensure interested parties are aware of where the decisions are being made?

For both of these I would suggest a new repo, called "policy", "governance" or "meta", which is low-volume enough that it's possible to subscribe to it.

> Is there anyone to whom you can appeal the decision?

@zcorpan and I discussed this a bit today. A steering group in the style of https://github.com/whatwg/sg might work, with the same expectation that the mechanism will always never be used, because people generally prefer to resolve their issues without escalation, where they have more control over the outcome.

The tricky part is how to create the initial group. Because it should be "boring" and effectively never used, having a big election or similar would make it seem more important than it is. My best suggestion might be to use the same procedure as when [picking the logo](https://docs.google.com/document/d/1S_WSpZVyzIKgnFo2Oc3cgSMd46NsmO9s7-TI3rKhmWM/edit?disco=AAAABwC-YIc), namely asking the top 10 wpt contributors vote if there are too many candidates.

**Comment by foolip** [comment]
@jgraham recommended that I watch [How Rust Does Open Development](https://youtu.be/rdmpOktHLmM). It's a long talk, but [2m12s](https://youtu.be/rdmpOktHLmM?t=2m12s) is a brief history, [6m8s](https://youtu.be/rdmpOktHLmM?t=6m8s) has the talk outline, and [46m1s](https://youtu.be/rdmpOktHLmM?t=46m1s) has the main lessons.

The answer to [WWIC?](http://www.ftrain.com/wwic.html) was an RFC process for "substantial" changes. Documented at https://github.com/rust-lang/rfcs. Not clear if there's a fast path when everybody agrees, I expect that'd be the case in WPT 90% of the time. I think a process like this would be good, a single place to monitor for "substantial" changes rather than relying on others poking you on big issues/PRs.

For a process like that to work we would still need a way to resolve disputes, i.e. a group of people who are trusted to make reasonable decisions. @web-platform-tests/admins could be this group, but it was created with no transparency, and I agree with @annevk (on IRC) that it's probably best to not conflate the two roles. Instead, we could create many teams or working groups as in Rust and have them decide in their areas, or perhaps have a single steering group intended as an infrequent escalation path.

There's also a lot of discussion on how to attract new contributors and help them advance to regular contributor and roles of leadership. This is an area we're frankly not doing very well in. [This Week in Rust](https://this-week-in-rust.org/) looks nice, I'd love a "This Week in WPT".

On planning larger arcs of work, I like the "slogans" idea, where the goals for a whole year are condensed into single short slogans. Currently we have no shared roadmap at all for WPT, only things like [Ecosystem Infra 2018 OKRs](https://docs.google.com/document/d/1hCOWgU95pN0LaZLdkoJyjlS9A5sjyQQWW6gh8YaDF8o/edit?usp=sharing) which represent just what one company is up to.

**Comment by plehegar** [comment]
I like the direction. Some comments below:

I would to make the "core team" to be at least 6 if we're keeping a requirement to have at least 3 browser engines. With only 5 and the requirement to have 3 browser engines, you're preventing the project to be independent from browser engines, which was always important in my mind to have on the paper, even if the reality is different (due to current major contributors). Having the *potential* to have some independence is important imho.

The scope of WPT, as a project, shouldn't be restricted to "unit tests for browser engines" imho. The overall project is about moving the Web forward using tests. I grant you that the current WPT repo achieves a lot for that. But I could imagine for example a separate repo called web-platform-tests/wpt-app-tests, which would focus on Web applications testing (like specific UI scrolling pattern/practices). So, those wouldn't be necessarily integrated into the browser engine implementer workflow. The core team overall goal should be bigger than just webplatform-tests/wpt. As such, in your list of potential changes requiring a RFC, I would add an another example something like "Adding a new repository for application-level or performance tests"

**Comment by plehegar** [comment]
btw, for the core team, what type of agreement did you have in mind?

**Comment by foolip** [comment]
I've put together https://github.com/foolip/rfcs as a strawman for how an RFC process might look.

> btw, for the core team, what type of agreement did you have in mind?

That question was for @jgraham, but this is still TBD in my RFC repo. I think the core team would also be the group that somehow resolves RFC that do not reach a consensus.

**Comment by foolip** [comment]
@jgraham, I've incorporated https://github.com/web-platform-tests/wpt/issues/11473#issuecomment-413583544 into https://github.com/foolip/rfcs by referencing a core team which does not exist yet, and using some of your phrasing.

**Comment by sideshowbarker** [comment]
> @web-platform-tests/admins and others, would you find that procedure acceptable?

Sounds good to me

**Comment by marcoscaceres** [comment]
>  top 100 wpt contributors

You might want the [top 100 in last 12 months](https://github.com/web-platform-tests/wpt/graphs/contributors?from=2017-10-19&to=2018-10-01&type=c) maybe? From the full list, lots of  people are inactive.

**Comment by foolip** [comment]
That might be better, yeah, although I hope no voting will be required. I'd leave that decision to the trusted volunteer.

**Comment by jgraham** [comment]
I think that procedure is acceptable, although I was imagining something less complex.

Appointing a trusted volunteer is challenging for theoretical and practical reasons. The theoretical reasons are just that the appointment of such a person is itself a fiat decision that needs to be made by someone or some group of people. Therefore it doesn't really reduce the number of meta decisions that need to be made, just causes a small amount of indirection. Practically finding a person who both has the relevant context and is neutral is hard. However if people feel the complexity is adding transparency then I'm happy to go ahead with that part of the plan.

**Comment by gsnedders** [comment]
Doing it by voting alone seems likely to end up with @foolip, myself, and @jgraham among others on the core team; in a sense that's less than ideal because it means the majority of users of the project are essentially underrepresented (how many tests for the three of us write?). There's also the question of whether we want to encourage those currently less involved to become moreso.

**Comment by foolip** [comment]
@jgraham has sent out [web-platform-tests Governance](https://lists.w3.org/Archives/Public/public-test-infra/2018OctDec/0008.html) to public-test-infra, drafted by him, @marcoscaceres and me. The process is a little bit different (simpler) than what I described in https://github.com/web-platform-tests/wpt/issues/11473#issuecomment-425756781, so please read there and if you are interested fill out [the self-nomination form](https://goo.gl/forms/YrQJCGaikKDBWXyp2).

**Comment by tobie** [comment]
Don't you want to extend this to the end of TPAC to make sure everyone sees it? Just a thought.

**Comment by foolip** [comment]
If someone shows up at TPAC that missed this discussion/announcement and would like to self-nominate, then sure, we'll include them in our effort to form a core team. But we'll want to do the "If possible a mutually agreeable decision is made from the pool of nominees" step during TPAC, so I don't think we should wait until the end to close the self-nomination form.

**Comment by annevk** [comment]
I got this clarified: there will be a 1 month objection period following any decision about who the core team should be with objections handled by @marcoscaceres: https://lists.w3.org/Archives/Public/public-test-infra/2018OctDec/0009.html. So whatever happens at TPAC is subject to scrutiny. This seems fairly reasonable to me.

**Comment by foolip** [comment]
@jgraham has announced the provisional membership of the initial core team and there is now a 1 month period in which objections to these members may be raised:
https://lists.w3.org/Archives/Public/public-test-infra/2018OctDec/0017.html

**Comment by tobie** [comment]
This team looks amazing. Congrats to all involved!

**Comment by gsnedders** [comment]
We now have a process and an RFC repo, so we can close this!
