### ISSUE TITLE
Support distinguishing service/shared/dedicated workers in .any.js tests

### ISSUE THREAD

**Issue by lukebjerring** [web-platform-tests/wpt#11928]
An example use-case for this feature would be any IDL that spans several combinations of subsets of window/sharedworker/serviceworker/dedicatedworker, e.g. [push-api](https://github.com/web-platform-tests/wpt/blob/master/interfaces/push-api.idl) has `PushManager` (Window, Worker) and `PushEvent` (ServiceWorker).

Currently, distinction is only possible with something like

    location.path.includes('.serviceworker.')

or

    self instanceof ServiceWorkerGlobalScope

NB: Somewhat related to https://github.com/web-platform-tests/wpt/issues/11529

**Comment by foolip** [comment]
Example of the four different global scopes currently supported:
http://w3c-test.org/IndexedDB/idlharness.any.html (window)
http://w3c-test.org/IndexedDB/idlharness.any.sharedworker.html
http://w3c-test.org/IndexedDB/idlharness.any.worker.html
https://w3c-test.org/IndexedDB/idlharness.https.any.serviceworker.html

The worker ones are backed by http://w3c-test.org/IndexedDB/idlharness.any.worker.js.

In the output:
```js
self.GLOBAL = {
  isWindow: function() { return true; },
  isWorker: function() { return false; },
};
```

This is actually documented in https://web-platform-tests.org/writing-tests/testharness.html.

If we could expand this to have `isDedicatedWorker()`, `isSharedWorker()` and `isServiceWorker()`, probably keeping `isWorker()` as the union of the three, then that should solve the problem.

Technically, that's not entirely straightforward since the same .any.worker.js is used for all three kinds of workers. Options:
* Turn the generated .any.worker.js into three different generated files with different `self.GLOBAL` preamble.
* Just use `self instanceof ServiceWorkerGlobalScope` to implement these helpers.

**Comment by foolip** [comment]
@lukebjerring, would this be used to make the correct assertions about what interface objects etc. are exposed in each global scope? Does idlharness.js currently just get it wrong?

**Comment by lukebjerring** [comment]
idlharness already uses self instanceof checks, so it's not farfetched that we continue that pattern. However, it seems inconsistent to have an isWorker function prepended in one case and a computation function elsewhere. Why do we have the isWorker function at all? We could compute that too.

**Comment by foolip** [comment]
It was added in https://github.com/w3c/wpt-tools/pull/88, maybe @Ms2ger or @jgraham know why?

**Comment by foolip** [comment]
> I added it as an easy way to distinguish the cases that couldn't be affected by browser bugs.

I wouldn't be surprised if someone forgot to expose the WorkerGlobalScope interface object somewhere at some point, so that makes sense.

What we could do instead is to add tests under /infrastructure/, with one global per test, that asserts that the `self instanceof Something` checks work, and then just use that pattern and remove `self.GLOBAL`. Option is to add non-generated helpers on `self.GLOBAL`. @lukebjerring, WDYT?

**Comment by Ms2ger** [comment]
One other thing to note is that you always need to check `"FooScope" in self && self instanceof self.FooScope`; it'd be somewhat nice to have a shorthand. Maybe that would be better put in th.js directly, though.

Anyway, I'm fine whichever way, as long as the tests keep working :)

**Comment by lukebjerring** [comment]
Seems like the verdict here is that further additions to self.GLOBAL isn't desirable.
