### ISSUE TITLE
Incorrect mimetype used

### ISSUE THREAD

**Issue by jyavenard** [web-platform-tests/wpt#12336]
https://github.com/web-platform-tests/wpt/blob/0de692bce7f4c1834ae3f3c86229caa16372a771/media-source/mediasource-changetype-util.js#L22

While not 100% incorrect, the mimetype for audio files should be using audio/webm or audio/mp4

so: 
 type: 'video/webm; codecs="vorbis"', becomes  type: 'audio/webm; codecs="vorbis"',
and
type: 'video/mp4; codecs="mp4a.40.2"', becomes type: 'audio/mp4; codecs="mp4a.40.2"',

**Comment by wolenetz** [comment]
In this initial version, I chose to use specific codecs since the spec allows:  though the spec recommends user agents not require such specificity in non-normative note, it similarly recommends apps request using codecs. Chromium MSE currently doesn't follow the former (it still requires specific codecs).

As I relax Chromium's MSE codec strictness, I'll add/update tests, since there are other places (addSourceBuffer, for instance) used in many other places in the tests still with strict codecs.

**Comment by wolenetz** [comment]
Oh! I see. Type mime type, not the codec parameter itself, is ok, but not perfect :)
I'll land a Chromium CL that will auto-export to WPT with s/video/audio/ for the audio codec mimetype+codec strings in those tests.

**Comment by wolenetz** [comment]
Tracking fixing this in Chromium in https://bugs.chromium.org/p/chromium/issues/detail?id=871929

**Comment by wolenetz** [comment]
Chromium CL to fix this is in code-review currently: https://chromium-review.googlesource.com/c/chromium/src/+/1166030

**Comment by wolenetz** [comment]
@jyavenard I believe https://github.com/web-platform-tests/wpt/commit/531bf4a9a5fd6e7812a40a8df1a6c32b4ba748e3 fixes this issue. Thank you for reporting it.
