### ISSUE TITLE
contain-size-007.html through 010.html use "overflow:hidden" on a box that doesn't support it

### ISSUE THREAD

**Issue by dholbert** [web-platform-tests/wpt#12388]
The tests `contain-size-007.html` through `contain-size-010.html` have `overflow:hidden` in a context where it has no effect, which is somewhat problematic. Test links:
https://github.com/web-platform-tests/wpt/blob/master/css/css-contain/contain-size-007.html
https://github.com/web-platform-tests/wpt/blob/master/css/css-contain/contain-size-008.html
https://github.com/web-platform-tests/wpt/blob/master/css/css-contain/contain-size-009.html
https://github.com/web-platform-tests/wpt/blob/master/css/css-contain/contain-size-010.html

They're trying to test that `contain:size` has no effect on internal table parts (e.g. table-row & table-row-group), and it looks like they're trying to test that by seeing whether they collapse to nothing when given `overflow:hidden`.  But this is ineffective because `overflow:hidden` doesn't actually do anything useful on these boxes.  (You can easily see this by using `overflow:scroll` instead -- if the `overflow` property had any effect in this context, then that'd make scrollbars appear. But none appear; hence, the `overflow` property seems to be ignored on these boxes.)

To really test this, I think we should put `overflow:hidden` on an *ancestor element*, like we do for e.g. https://github.com/web-platform-tests/wpt/blob/master/css/css-contain/contain-size-001.html and https://github.com/web-platform-tests/wpt/blob/master/css/css-contain/contain-size-002.html .  That would still let us accurately find out whether the `contain:size` thing actually collapsed away or not, by virtue of whether it props up the size of our auto-sized `overflow:hidden` ancestor.

CC @frivoal

**Comment by TalbotG** [comment]
Manuel Rego (test author) is on vacation (holidays) until September 3rd.

I agree that the use of `overflow: hidden` in those tests is inadequate.

Setting `overflow: hidden` on an ancestor may work. My preference would be to search for a test design that would instead avoid using, resorting to `overflow: hidden` in tests like `contain: size`. I am convinced this should be doable. The test does not have to be very complex since its original purpose is to verify that `contain: size` does not apply to table-row and table row groups.

**Comment by frivoal** [comment]
My assumption when writing this was that in order to apply, (if a browser accidentally did so in violation of the spec), contain:size would certainly have to turn the elements into something to which overflow would happen.

Thinking back, there is nothing certain about this, so I agree with the suggestion of putting overflow:hidden on an ancestor.

I'm open to the suggestion by @TalbotG that this could be done differently, but the suggested fix is simple enough, and the alternative approach isn't obvious to me now, so I made a PR https://github.com/web-platform-tests/wpt/pull/12486 using an `overflow:hidden` wrapper.
