### ISSUE TITLE
Instructions on how to override browser flags

### ISSUE THREAD

**Issue by marcoscaceres** [web-platform-tests/wpt#12397]
As new web features are usually behind flags (e.g., `dom.payments.request.enabled`), it would be nice to give instructions on how to "pref on" features when running tests. 

The problem I'm having is that, for instance, I do the following:

```
./wpt install firefox browser
./wpt run firefox payment-request/payment-request-show-method.https.html
```

But the test fails because the `dom.payments.request.enabled` is not on by default. When I try to set it manually in the the Firefox instance that pops up, Firefox doesn't seem to remember that I set it. 

Any suggestions?

**Comment by gsnedders** [comment]
https://github.com/web-platform-tests/wpt/issues/10452 is related to this

**Comment by foolip** [comment]
@jgraham, is there an equivalent for Firefox, or is a prefs file needed?

**Comment by jugglinmike** [comment]
Sounds like a job for the `--setpref` flag:

    $ ./wpt run --help

    [omitted]

    Gecko-specific:

    [omitted]

      --setpref PREF=VALUE  Defines an extra user preference (overrides those in
                            prefs_root)

Leaving the support request open as we may want to resolve with an enhancement to the documentation.

**Comment by marcoscaceres** [comment]
I’ve been working around it by modifying Firefox’s User.js file, but with Nighty... well... it gets trashed Nightly 😂 

Is the setpref already supported? Totally missed that.

**Comment by jugglinmike** [comment]
I stripped out some of the surrounding documentation, but if you check the output of `./wpt run --help`, you'll find that there's also a `--prefs-root` argument. That might be more appropriate if you have a lot of preferences to set (though I don't think I've ever used it myself).

**Comment by marcoscaceres** [comment]
Yeah, I actually have quite a few. Right now, I keep them in text file that I copy/paste from so it would actually be really nice to just be able to point to them.

**Comment by jugglinmike** [comment]
Since setting preferences is just one browser-specific use case among many, it's hard to justify promoting the description above the other command-line arguments.

However, there have been a couple improvements to the documentation site which may be sufficient to address this issue:

First, the command-line arguments are now included: https://web-platform-tests.org/running-tests/command-line-arguments.html For many folks, this listing is probably easier to take in on a web page than in a terminal.

Building off that, the website offers a search functionality. That new CLI arguments page is the first result when you search for [pref](https://web-platform-tests.org/search.html?q=pref), [preference](https://web-platform-tests.org/search.html?q=preference), and [preferences](https://web-platform-tests.org/search.html?q=preferences), and the relevant text is highlighted if you get there from those results.

@marcoscaceres Do you think that's enough to call this issue "resolved"?

**Comment by marcoscaceres** [comment]
That's great! thanks @jugglinmike

**Comment by jugglinmike** [comment]
Glad to get this one resolved :)
