### ISSUE TITLE
[css-writing-modes] <img> in some 'vertical-lr' tests may actually be missing 'vertical-align: bottom'

### ISSUE THREAD

**Issue by TalbotG** [web-platform-tests/wpt#12420]
http://test.csswg.org/harness/test/css-writing-modes-3_dev/spec/css-writing-modes-3/section/7/abs-pos-non-replaced-vlr-227/

Some browsers (like Epiphany Technological Preview version 605.1.15; using WebKitGTK+ 2.21.5) will show a **4px horizontal difference** between test and reference file. It seems that such difference is due to the fact that the "support/pass-cdts-abs-pos-non-replaced.png" `<img>` in the test is baseline-aligned according to 'vertical-lr' writing-mode and is **not bottom-aligned inside its 'vertical-lr' line box**. And the reference file does not take this factor into account, into consideration when positioning that same "support/pass-cdts-abs-pos-non-replaced.png" `<img>`.

**Comment by TalbotG** [comment]
I have double-checked a list of 26 writing-mode tests where Epiphany Technological Preview (version 605.1.15; using WebKitGTK+ 2.21.5) shows an horizontal or vertical difference between the 26 tests and their associated reference files. The thing is: I saw no horizontal or vertical difference when trying those 26 tests with Firefox 63.0a1 buildID=20180812220618 (latest nightly build for today) and with Chromium 70.0.3522.0 (latest build for today) **except for 2 tests: vertical-alignment-003 and vertical-alignment-009 **: 

http://test.csswg.org/harness/test/css-writing-modes-3_dev/spec/css-writing-modes-3/section/7/vertical-alignment-003/

http://test.csswg.org/harness/test/css-writing-modes-3_dev/spec/css-writing-modes-3/section/7/vertical-alignment-009/

So, I am still unsure about the 24 other tests...

**Comment by frivoal** [comment]
unless text-orientation is set to sideways, the central baseline should be used. The alignment problem you're mentioning is cause by aligning the bottom of the image to alphabetic baseline, instead of the center to the central baseline. When that's done properly, there is no gap at the bottom for large enough images. Safari fails the 3 tests you mentioned due to this bug, and I suspect that epiphany does as well. I don't know what are the other tests mentioned, but I suspect it's the same problem.

Closing. Please reopen if you can find some tests which are not explained by this.
