### ISSUE TITLE
[css-contain] contain-layout-015 should be improved

### ISSUE THREAD

**Issue by TalbotG** [web-platform-tests/wpt#12421]
Manuel Rego and I agree that the current test
http://test.csswg.org/suites/css-contain-1_dev/nightly-unstable/html/contain-layout-015.htm
has problems.

> Since overflowed content must be treated as ink overflow and therefore as unreachable (because outside of scrollable region) content, then I think such content (overflowing content outside div#wrapper's height and width) should be red, not green. As designed, the test can not render red even if 'contain: layout' is disabled or removed.
(...) [The test should also] mention that scrollbars shouldn't be present if the test works as expected.

I have proposed 

http://www.gtalbot.org/BrowserBugsSection/CSS3Contain/contain-layout-015.1-Rego.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Contain/contain-layout-015.2-Rego.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Contain/contain-layout-015.3-Rego.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Contain/contain-layout-015.4-Rego.html

as replacements

**Comment by TalbotG** [comment]
@mrego

**Comment by mrego** [comment]
I guess these kind of tests are already covered by `contain-layout-ink-overflow-*`.
Should we just remove `contain-layout-015.html`?

CC @frivoal

**Comment by frivoal** [comment]
I think we should indeed remove it.

As it is, it doesn't show any red regardless of support for css-contain. The presence of scrollbars should make it fail, but since many modern browsers/OSes have transient scrollbars, that's might not work.

However, if we fix that test to take care of that issue, then it is redundant with the contain-layout-ink-overflow-* tests from Gérard.

**Comment by frivoal** [comment]
If you want to submit a PR to remove it, I'll gladly approve it. Otherwise, I'll get to it myself eventually.
