### ISSUE TITLE
Add a module variant for .any.js

### ISSUE THREAD

**Issue by domenic** [web-platform-tests/wpt#12480]
Some tests, notably those in https://github.com/web-platform-tests/wpt/tree/master/async-local-storage (more incoming in #12416) would benefit from running as a module in window, worker, and service worker contexts. Using .any.js today uses classic scripts, not modules, so it's not suitable for that.

This is not super-urgent as nobody is shipping module workers yet. Chrome has a flagged implementation though, and hopefully will be shipping soon.

**Comment by foolip** [comment]
A bit similar to https://github.com/web-platform-tests/wpt/issues/12443, but unlike that isn't a new global scope but a new... script type? (Terminology from https://html.spec.whatwg.org/#classic-script)

@domenic, what would you suggest as the syntax for this? If we support .module.js and combinations like .module.window.js (or .window.module.js), then maybe this?
```
// META: global=window,worker
// META: scripttype=classic,module
```

**Comment by domenic** [comment]
Hmm, would the comment syntax be in addition to the filename stuff? Indeed, there are some things I'd want to test only in module scripts, and some I'd want to test in both module scripts and classic scripts. I'd use `.module.js` for the former, and the comments for the latter.

**Comment by domenic** [comment]
Right, in theory there's no reason not to test all four combinations ((window + worker) x (classic + module)). But in practice maybe you only need to test a few.

I think the higher priority feature right now though is module x (window + worker). For that my initial thought was just filenames, with no comment syntax.

**Comment by foolip** [comment]
OK, I think .module. as part of the <s>file</s>testname would be the underpinnings for a comment syntax anyway. How about, then, if `foo.module.{any,window,worker,etc}.js` does the same stuff as .any.js and friends, except for the bit of the generated code that does `import(something)` instead of `<script>` or `importScripts`?

@gsnedders can you see complications arising with that? The only thing that comes to mind is if some analogue problem to https://github.com/web-platform-tests/wpt/issues/11105 happens because of non-unique generated paths.

**Comment by domenic** [comment]
Hmm I'd do `<script type="module" src="something">` + `new Worker("something", { type: "module" })` instead of `import("something")` myself, to be more analogous to the existing infrastructure.

**Comment by foolip** [comment]
OK, that makes sense for window. Inside workers, I take it `import("something")` is still necessary?

**Comment by domenic** [comment]
No, you can do `new Worker("something", { type: "module" })`, once browsers implement that.

I didn't even think of using `import()` to test things today; that's an interesting point.

**Comment by foolip** [comment]
@nhiroki is there someone working on this in Chromium who would champion (implement) this change? I believe there aren't too many options for how to implement it, so it's mostly a matter of writing the code and making sure that the changes won't cause trouble for downstream users of WPT (Edge, Gecko, WebKit).

**Comment by nhiroki** [comment]
@foolip  I'm interested to implement this, but I'm not sure I can start it soon. Could you provide guidance how to implement this (e.g., files to be changed) so that I or someone can work on this in spare time?

Regarding [domenic's comment](https://github.com/web-platform-tests/wpt/issues/12480#issuecomment-413312496),

> Right, in theory there's no reason not to test all four combinations ((window + worker) x (classic + module)). But in practice maybe you only need to test a few.
> 
> I think the higher priority feature right now though is module x (window + worker). For that my initial thought was just filenames, with no comment syntax.

our use case is to run existing classic worker tests as modules, that is, ((classic + module) x (worker)). Therefore, we want to support not only ```module.{window,worker,any}.js``` but also  ```anytype.{window,worker,any}.js``` (or ```META: scriptype=classic,module```).

**Comment by hiroshige-g** [comment]
Started.
Draft CL: https://chromium-review.googlesource.com/c/chromium/src/+/2455766

**Comment by jgraham** [comment]
I think this sort of API change requires an RFC. I'd assume it's not going to be very controversial, but nevertheless I think we should go through the correct process.

**Comment by hiroshige-g** [comment]
Thanks for letting me know, sounds reasonable > RFC

**Comment by hiroshige-g** [comment]
https://github.com/web-platform-tests/wpt/pull/27699 already added this functionality and thus this issue can be closed.
