### ISSUE TITLE
MutationObservers array reference

### ISSUE THREAD

**Issue by plehegar** [web-platform-tests/wpt#1273]
Write a test that modify the attributerFilter array while making attribute mutations.
https://critic.hoppipolla.co.uk/r/2502
https://critic.hoppipolla.co.uk/showcomment?chain=7783

**Comment by foolip** [comment]
Neither of the URLs are in web.archive.org, so can't see the old discussion, but https://github.com/w3c/web-platform-tests/pull/1227 was the PR, found by date.

The spec for this is now https://dom.spec.whatwg.org/#interface-mutationobserver

If that IDL is used, then the input array will be copied and there's no possibility of a mutate-during-iteration bug. @plehegar @annevk, would you agree, so that we should close this issue?

**Comment by annevk** [comment]
Yes. Though testing this would ensure the binding is indeed implemented as such.

**Comment by frehner** [comment]
came across this as I was looking for some issues to work on.

> I'll leave this alone, but would suggest that it if several years more pass without action it's just closed.

almost 2 years to the date :D
