### ISSUE TITLE
[HTTP/2.0] Writing tests that use HTTP/2

### ISSUE THREAD

**Issue by JosephPecoraro** [web-platform-tests/wpt#13532]
Now that there is a prototype implementation of HTTP/2.0 support in wptserve, and some limited documentation, how do test authors take advantage of it?

* It seems in order to enable it you would currently need to include a `--h2` switch. Does this enable `http1` and `http2` support within the same server just at different ports? That would enable a single test to issue requests that test both http1 and http2 at the same time.

* https://github.com/web-platform-tests/wpt/pull/12490 seems to indicate that `ports[http2]` would exist, but no existing tests take advantage of this yet and I didn't see any documentation pointing to this?

* Is there a plan for enabling the HTTP/2.0 server by default? The open issues for HTTP/2.0 haven't been updating since August. Is there a top level issue I can track?

**Comment by JosephPecoraro** [comment]
CC @dhdavvie given his past work on this.

**Comment by jgraham** [comment]
So the work is a little stalled. The first problem is that we can't run the HTTP/2 server on Travis because their machine images are so outdated. So this is blocked on migrating our testing away from Travis. It's also likely to cause problems for people running tests locally on OSX who are quite likely to have an out of date OpenSSL installed, and will need to install an update via homebrew or similar.

In terms of actually using the server, there is currently no facility for running top-level tests over http2, but the servers will run in parallel on different ports, so you'll be able to load subresources over the http2 server. If top-level tests over http2 are required, I imagine we would copy the `.https.` design and add a `.h2.` flag in the filename.

**Comment by dhdavvie** [comment]
@jgraham has covered everything pretty well, the current status of the H2 prototype server is stalled due to not being able to have it on by default. 

There is a little bit of [documentation](https://web-platform-tests.org/writing-tests/server-features.html) at the bottom and links to more specific stuff, for some reason the link doesn't get auto-hosted so it downloads the .md file. Please let me know what more you would want to see/know

**Comment by foolip** [comment]
Would it make sense to add some infrastructure tests for this, so that I can see if I can get them passing on macOS? Hopefully we'd also see them passing on Taskcluster already?

**Comment by dhdavvie** [comment]
@foolip Do you mean unit tests for the server? These already exist, and if memory serves correct, will run automatically if you have the correct environment.

**Comment by foolip** [comment]
@dhdavvie not quite, I mean tests under https://github.com/web-platform-tests/wpt/tree/master/infrastructure/server. Integration tests, I guess we'd call them.

**Comment by dhdavvie** [comment]
@foolip pardon my ignorance, but what advantage do these have over unit tests? Or am I misunderstanding their purpose?

**Comment by foolip** [comment]
We'd see the results on wpt.fyi and can tell by those result if the setup is working in the system that run wpt for wpt.fyi. Having the unit tests pass on some machine presumably does not ensure that it actually works, given some openssh system dependency that @jgraham has told me about.

**Comment by foolip** [comment]
That should be OpenSSL, and is tracked by https://github.com/web-platform-tests/wpt/issues/12256.

**Comment by stephenmcgruer** [comment]
So we no longer use Travis; what's still blocking this? We can turn on H2 in Taskcluster as far as I know (though we haven't), is there anything else needing done?

**Comment by jgraham** [comment]
Possibly just changing the flag at https://searchfox.org/mozilla-central/source/testing/web-platform/tests/tools/serve/serve.py#849 and testing the result. Let's try :)

**Comment by jgraham** [comment]
https://github.com/web-platform-tests/wpt/pull/20620
