### ISSUE TITLE
css/selectors/attribute-selectors/attribute-case/syntax.html test has inconsistent names of subtests

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#14003]
https://wpt.fyi/results/css/selectors/attribute-selectors/attribute-case/syntax.html?sha=71fe0a6c3d

In Edge, in addition to the failures, the subtests names are different, some are missing and there's an extra "[foo='bar' i" test at the end which I cannot find in the source.

This seems likely to be a test bug.

@jugglinmike is this a sort of anomaly that shows up in any report we have?

**Comment by gsnedders** [comment]
I don't really understand how this could be a test bug? It's a pretty simple sequence of sync tests…

**Comment by jugglinmike** [comment]
I'm on the case!

**Comment by jugglinmike** [comment]
This is the result of a deficiency in Edge/Edgedriver: string literals transmitted via the "Execute Script" and "Execute Async Scripts" commands are truncated at the first null byte.

[I've submitted a WebDriver conformance test to alert the Edge maintainers](https://github.com/web-platform-tests/wpt/pull/13880#issuecomment-441341286), and I've suggested a more immediate solution for WPT via gh-14245.

**Comment by jugglinmike** [comment]
@foolip We never did come to a conclusion for unprintable characters in test names, but now that Edge has a new WebDriver implementation which tolerates that case ([as evidenced by recent test
results](https://wpt.fyi/results/css/selectors/attribute-selectors/attribute-case/syntax.html?label=experimental&label=master&aligned)), the issue is less relevant. I'm going to un-assign myself and recommend my fix, unpopular though it may be--gh-14245.

**Comment by foolip** [comment]
Alright, I'll just go ahead and close this because without something to surface the problem it won't ever be a priority for anyone.
