### ISSUE TITLE
allow_uncaught_exception flag does not work as expected for worker.html promise_test in Chrome

### ISSUE THREAD

**Issue by andreas-butler** [web-platform-tests/wpt#14041]
In Chrome 72 it appears that the allow_uncaught_exception flag does not behave as expected during promise_test execution for worker.html tests, but rather still allows the testharness to error as a result of an uncaught exception.

To test this, copy the following small test case into a .any.js file and and run it as a worker.html test:

```javascript
// META: global=window,worker
 
setup({allow_uncaught_exception:true});
 
promise_test(async testCase => {
  const error = new Error("boo");
  const eventReceived = new Promise((resolve,reject) => {
    self.addEventListener("error", ev => {
      assert_equals(ev.error, error);
      resolve();
    });
  });
  queueMicrotask(() => { throw error; });
  await eventReceived;
}, 'error catching test');
```

The output result on chrome 72 should be similar to the following:
"
This is a testharness.js-based test.
Harness Error. harness_status.status = 1 , harness_status.message = Error in remote http://web-platform.test:8001/IndexedDB/promise-test-error.any.js: Uncaught Error: boo
PASS error catching test
Harness: the test ran to completion.
"

As can be seen, the test passes (as it should) but the testharness still errors because of the uncaught exception. My understanding is that by setting the allow_uncaught_exception flag this should not be the case. The issue appears to be unique to worker.html promise_tests (the same issue was not replicable for async tests or promise_tests run normally, on a serviceworker, or on a sharedworker).

**Comment by jugglinmike** [comment]
Thanks for the report! Here's a further reduced test case that ought to demonstrate the problem in most browsers:

```js
// META: global=window,worker

setup({allow_uncaught_exception:true});

promise_test(() => {
    return new Promise((resolve) => {
        setTimeout(() => {
            resolve();
            throw new Error('not so good');
          }, 0);
      });
  });
```

The issue is that the uncaught exception is triggering the worker's `onerror` handler, which [testharness.js (as running in the parent context) reports as a harness error](https://github.com/web-platform-tests/wpt/blob/53ef64dc2983dce0efe37016cdaee3b3ad279305/resources/testharness.js#L1913).

I don't know how to resolve this yet. Some of the solutions I've considered:

- call `preventDefault` on the error when `allow_uncaught_exception` is set. That risks invalidating tests for uncaught exceptions
- Script the child context to send testharness.js settings to the parent context via `postMessage`. That risks race conditions between the `error` and `message` events
- Script the parent context to request testharness.js settings from the child context via `postMessage` when interpreting `onerror`. That risks race conditions between the "ERROR" status and the "OKAY" status
