### ISSUE TITLE
Taskcluster status checks not finishing and blocking PRs

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#14165]
In https://github.com/web-platform-tests/wpt/pull/14088#issuecomment-440577561 @qiuzhong reported that Taskcluster isn't finishing and that they have seen this often recently. I made Taskcluster required just after I merged https://github.com/web-platform-tests/wpt/pull/14096, so that's why this has been happening only recently.

In https://github.com/web-platform-tests/wpt/issues/13194#issuecomment-439491149 we wondered what would happen, and now we know.

**Comment by foolip** [comment]
@jugglinmike have you heard back from the Taskcluster folks about this problem? Do you have up-to-date stats about how many PRs are affected?

**Comment by foolip** [comment]
The status will be "Expected — Waiting for status to be reported" when this occurs.

**Comment by foolip** [comment]
After consulting with @jgraham on IRC I've made the check not required while this is being resolved, and will assign to James.

**Comment by jugglinmike** [comment]
> @jugglinmike have you heard back from the Taskcluster folks about this problem?

No, but you can keep an eye on [the bug I filed](https://bugzilla.mozilla.org/show_bug.cgi?id=1507254) to get the latest.

> Do you have up-to-date stats about how many PRs are affected?

Sure. To keep things organized, [I've reported the new stats in the original issue](https://github.com/web-platform-tests/wpt/issues/13194#issuecomment-439491149). I've also posted the new failures on that Taskcluster ticket.

**Comment by foolip** [comment]
Thanks @jugglinmike!

**Comment by foolip** [comment]
@jgraham can you help us poke for progress on this?

**Comment by lukebjerring** [comment]
Ping @jgraham any updates on this?

**Comment by foolip** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1507254 has been resolved now. @jugglinmike can you get stats for the past week, to see if we can make stability blocking again?

**Comment by jugglinmike** [comment]
To give us a little more confidence, I'll verify all commits over the past 2 weeks (the bug was reported as "fixed" on 2018-11-28):

    $ node . --between 2018-11-28:2018-12-11 --discrepancies --format markdown

Good news! In that period, Taskcluster has reported results for every commit that TravisCI has reported results.

<details>
  <summary>All results</summary>

pull request URL | pull request author | commit | TravisCI: Chrome | Taskcluster: Chrome | TravisCI: Firefox | Taskcluster: Firefox
-----------------|---------------------|--------|------------------|---------------------|-------------------|---------------------
[gh-14430](http://github.com/web-platform-tests/wpt/pull/14430) | autofoolip | 2a8c9f35a536bbe9c66469c5f6e154049e083bb0 | PASS | PASS | ERROR | FAIL
[gh-14424](http://github.com/web-platform-tests/wpt/pull/14424) | lgrahl | c115ababdb5e4b35658566308c816adb82459beb | ERROR | FAIL | ERROR | FAIL
[gh-14424](http://github.com/web-platform-tests/wpt/pull/14424) | lgrahl | a01a43fde81f2731e77171d53da4ebfd1e98574d | ERROR | FAIL | ERROR | FAIL
[gh-14422](http://github.com/web-platform-tests/wpt/pull/14422) | chromium-wpt-export-bot | 4b1e03147f37799cf718ba2fd0120a8bab825d84 | ERROR | PASS | ERROR | PASS
[gh-14419](http://github.com/web-platform-tests/wpt/pull/14419) | youennf | c2e1ce77bdb91272a9c1557ca9a41345206d2e09 | ERROR | PASS | ERROR | FAIL
[gh-14418](http://github.com/web-platform-tests/wpt/pull/14418) | youennf | d9d2911b6a120c64bf8db2a48237b68e4da3da75 | ERROR | PASS | ERROR | PASS
[gh-14417](http://github.com/web-platform-tests/wpt/pull/14417) | youennf | c7baefa5c15a3c1f4e4ef86c4c5a102d98831338 | ERROR | FAIL | ERROR | FAIL
[gh-14417](http://github.com/web-platform-tests/wpt/pull/14417) | youennf | b8e143ae48373d1763a98c8bc607663cba495896 | ERROR | FAIL | ERROR | FAIL
[gh-14415](http://github.com/web-platform-tests/wpt/pull/14415) | andreastt | 0c61d8d031ae0183c8682306851fb778af6df825 | ERROR | FAIL | PASS | PASS
[gh-14410](http://github.com/web-platform-tests/wpt/pull/14410) | chromium-wpt-export-bot | ef1a5c8bdcb48142568258840bb6db4f7eb86c71 | PASS | FAIL | PASS | PASS
[gh-14409](http://github.com/web-platform-tests/wpt/pull/14409) | qiuzhong | fa019ce14e672c66b81eb6700b6d1422cb44c9a3 | ERROR | FAIL | ERROR | FAIL
[gh-14409](http://github.com/web-platform-tests/wpt/pull/14409) | qiuzhong | 78aa08dc806f0825ef46a90ccdf0f8d78fcb78ed | ERROR | FAIL | ERROR | FAIL
[gh-14409](http://github.com/web-platform-tests/wpt/pull/14409) | qiuzhong | 78c0a070f2562da5bf188a98b0a501114557118d | ERROR | FAIL | ERROR | FAIL
[gh-14405](http://github.com/web-platform-tests/wpt/pull/14405) | chromium-wpt-export-bot | e630525b008d015e4cb4431a6c31e007711667bd | ERROR | PASS | ERROR | FAIL
[gh-14400](http://github.com/web-platform-tests/wpt/pull/14400) | koto | b8b57d1ec2d8150520864e6ab5a72a2589857f74 | ERROR | FAIL | ERROR | PASS
[gh-14395](http://github.com/web-platform-tests/wpt/pull/14395) | Ms2ger | 4e388a4491e2fcf81142bc71ce3c4033689fd78e | ERROR | FAIL | ERROR | FAIL
[gh-14386](http://github.com/web-platform-tests/wpt/pull/14386) | chromium-wpt-export-bot | bafb027203a01a506682e966d10deba65d19d132 | PASS | PASS | ERROR | FAIL
[gh-14385](http://github.com/web-platform-tests/wpt/pull/14385) | chromium-wpt-export-bot | 168fa7c8d4aafb56e90a38b78d3d6c17d6cd5ca3 | ERROR | PASS | ERROR | PASS
[gh-14370](http://github.com/web-platform-tests/wpt/pull/14370) | autofoolip | 71880c75f5998d0c9fe684a3d644baaf593fa914 | PASS | PASS | ERROR | FAIL
[gh-14367](http://github.com/web-platform-tests/wpt/pull/14367) | ewilligers | a18a0bb6086d6b17e23e472befcfa6666f08d01f | ERROR | PASS | PASS | PASS
[gh-14364](http://github.com/web-platform-tests/wpt/pull/14364) | jugglinmike | b17d27f7f0aaefdfc54b8b875a42069b9f5b8c60 | ERROR | FAIL | ERROR | PASS
[gh-14363](http://github.com/web-platform-tests/wpt/pull/14363) | chromium-wpt-export-bot | 4365720c8c45517b647443a67380cb33fd6a340f | PASS | PASS | PASS | FAIL
[gh-14362](http://github.com/web-platform-tests/wpt/pull/14362) | chromium-wpt-export-bot | 69114e43e9f10e61cf726de017c440fe6ea340b5 | PASS | FAIL | PASS | PASS
[gh-14345](http://github.com/web-platform-tests/wpt/pull/14345) | SummerLW | f0b5ee0170d49089cf80d8d3f39e5a60a5d7afbd |  | PASS |  | PASS
[gh-14339](http://github.com/web-platform-tests/wpt/pull/14339) | chromium-wpt-export-bot | 3950f9fed0362c880089919db786fe301f68f518 | PASS | PASS | ERROR | PASS
[gh-14334](http://github.com/web-platform-tests/wpt/pull/14334) | MurakamiShinyu | 781fd3da33273b0615145dac18997418821ca3f0 | ERROR | PASS | ERROR | PASS
[gh-14319](http://github.com/web-platform-tests/wpt/pull/14319) | chromium-wpt-export-bot | 50fd7a02deef7e97ed11a645181f9a3b2d7bd6b5 | PASS | FAIL | PASS | FAIL
[gh-14317](http://github.com/web-platform-tests/wpt/pull/14317) | youennf | c6db9432e1d88b499acccda9688337eca7d22b08 | PASS | FAIL | PASS | PASS
[gh-14314](http://github.com/web-platform-tests/wpt/pull/14314) | darsh7807 | c95f79292fd0c0a2550c115aa807966df83a75b3 |  | PASS |  | PASS
[gh-14300](http://github.com/web-platform-tests/wpt/pull/14300) | foolip | f90c12ddfd08647b11eb82203e0868a6c4d52c7b | PASS | FAIL | PASS | PASS
[gh-14300](http://github.com/web-platform-tests/wpt/pull/14300) | foolip | 6bf4be29996f23646d345429f9d8a63dcfc2dec8 | PASS | FAIL | PASS | PASS
[gh-14300](http://github.com/web-platform-tests/wpt/pull/14300) | foolip | 8f0c1c82648c695410c5a7cd7a91f84304f9e329 | PASS | FAIL | PASS | FAIL
[gh-14300](http://github.com/web-platform-tests/wpt/pull/14300) | foolip | 52e81981781ebe58e69c41a044f0ea97ef67db3c | PASS | PASS | PASS | FAIL
[gh-14300](http://github.com/web-platform-tests/wpt/pull/14300) | foolip | 1fc51b41012f9eb197b83f634cd4606f3d63e2f7 | PASS | FAIL | PASS | FAIL
[gh-14300](http://github.com/web-platform-tests/wpt/pull/14300) | foolip | 18d6b1eeb0afcd66d13605e6e134858226f9dcc3 | PASS | FAIL | PASS | FAIL
[gh-14297](http://github.com/web-platform-tests/wpt/pull/14297) | marcoscaceres | 94fd139ae5d0bdc4274b5e2c4e91035d63876e5c | ERROR | FAIL | ERROR | FAIL
[gh-14293](http://github.com/web-platform-tests/wpt/pull/14293) | chromium-wpt-export-bot | cc2a9d427c81422079f79690378364172f00adce | PASS | FAIL | PASS | PASS
[gh-14288](http://github.com/web-platform-tests/wpt/pull/14288) | jyasskin | 48bb0427ce46460705e990b81348bc2d65f05632 | PASS | PASS | ERROR | PASS
[gh-14285](http://github.com/web-platform-tests/wpt/pull/14285) | chromium-wpt-export-bot | be36d606c62ff7ccf9730ab4e18f62c97b543fd2 | ERROR | PASS | ERROR | PASS
[gh-14282](http://github.com/web-platform-tests/wpt/pull/14282) | chromium-wpt-export-bot | cd6694f331094b8ca7c12575e99a200c759519c6 | PASS | PASS | PASS | FAIL
[gh-14278](http://github.com/web-platform-tests/wpt/pull/14278) | annevk | 072ffc9ec265767aad395ae73a0119aec4fcf829 | PASS | FAIL | PASS | PASS
[gh-14276](http://github.com/web-platform-tests/wpt/pull/14276) | autofoolip | bb8785f176c2424d0f74ac43d0ed2dbe20ae940b | PASS | FAIL | PASS | PASS
[gh-14273](http://github.com/web-platform-tests/wpt/pull/14273) | qiuzhong | 9aaf8ca165cc6519e47613a9e47bc089f06b28b0 | PASS | FAIL | ERROR | FAIL

    Summary:
    - Total pull requests:         162
    - Total commits:               244
    - Tested commits:              218
    - Contested commits (Chrome):  10
    - Contested commits (Firefox): 8
    - Contested commits (both):    25

</details>

(For anyone interested in reproducing this data, [the script I'm using is available here](https://github.com/bocoup/wpt-validate-taskcluster).)

**Comment by foolip** [comment]
Excellent! I've made Taskcluster a required check for master again and so closing this issue.
