### ISSUE TITLE
Intermittent "Unrecognized type EventHandlerNonNull" in html/dom/interfaces.https.html

### ISSUE THREAD

**Issue by Ms2ger** [web-platform-tests/wpt#14254]
I've seen this in https://github.com/web-platform-tests/wpt/pull/14252, but also before that. I tried to reproduce at the time, but failed.

**Comment by foolip** [comment]
This happened in https://github.com/web-platform-tests/wpt/pull/14954. From [the logs](https://taskcluster-artifacts.net/Nr8maQq6QIKpx_Au_ImTdQ/0/public/logs/live_backing.log):

|                             Test                             |                                     Subtest                                      |          Results           |                 Messages                |
|--------------------------------------------------------------|----------------------------------------------------------------------------------|----------------------------|-----------------------------------------|
| `/html/dom/interfaces.https.html?include=(Document\|Window)` | `Window interface: window must inherit property "onunload" with the proper type` | **FAIL: 9/10, PASS: 1/10** | `Unrecognized type EventHandlerNonNull` |

**Comment by foolip** [comment]
This happened in https://github.com/web-platform-tests/wpt/pull/15123 too.

**Comment by foolip** [comment]
@Ms2ger will https://github.com/web-platform-tests/wpt/pull/14866 fix this, or only partly?

**Comment by foolip** [comment]
Oh, disregard, you were saying this was the remaining Taskcluster issue. I wanted to poke at https://github.com/web-platform-tests/wpt/issues/14645.

**Comment by foolip** [comment]
https://github.com/web-platform-tests/wpt/pull/12804 was affected by this.

**Comment by foolip** [comment]
https://github.com/web-platform-tests/wpt/pull/15896 too.

**Comment by foolip** [comment]
This happens when SVG.idl is updated as well: https://github.com/web-platform-tests/wpt/pull/16765

**Comment by foolip** [comment]
@jgraham @lukebjerring this is the issue we mentioned in the meeting just now.

**Comment by lukebjerring** [comment]
This seems to be flakiness in the order in which the dependencies are resolved during `add_dependency_idls`. 

Flakiness is obvious on wpt.fyi/insights => [Flakiness (Firefox)](https://wpt.fyi/results/?label=master&label=experimental&max-count=10&product=firefox&q=seq%28%28status%3APASS%7Cstatus%3AOK%29%2B%28status%3A%21PASS%26status%3A%21OK%26status%3A%21unknown%29%29%2Bseq%28%28status%3A%21PASS%26status%3A%21OK%26status%3A%21unknown%29%2B%28status%3APASS%7Cstatus%3AOK%29%29) => [/html/dom/interfaces.https.html?include=HTML.*](https://wpt.fyi/results/html/dom/interfaces.https.html%3Finclude%3DHTML.*?label=master&label=experimental&max-count=10&product=firefox&q=seq%28%28status%3APASS%7Cstatus%3AOK%29+%28status%3A%21PASS%26status%3A%21OK%26status%3A%21unknown%29%29+seq%28%28status%3A%21PASS%26status%3A%21OK%26status%3A%21unknown%29+%28status%3APASS%7Cstatus%3AOK%29%29)

@bzbarsky - @jgraham said you might be able to help isolate what Firefox might be doing differently/non-deterministically ?

**Comment by bzbarsky** [comment]
I doubt this has anything to do with `add_dependency_idls`, because none of `EventHandlerNonNull`, `EventHandler`, or `HTMLBodyElement` are in any of the dependencies; they are all in `html.idl`.

The immediate failure here is because `EventHandlerNonNull` is in fact an unrecognized type, because https://github.com/web-platform-tests/wpt/blob/69f536cd9cc57f20a6d27acb70b7b05c6434b24d/resources/idlharness.js#L490-L493 means it's not added to the `IdlArray`'s member list.

So how are we landing here and why is it not failing for every single event handler attribute?  We're doing `assert_type_is` on the value of the `onunload` property on the `<body>`.  `assert_type_is` sees that the type passed in (`EventHandler`) is a typedef, and calls itself with that value and `EventHandlerNonNull?` as the type.  Now there are two possible codepaths:

1) The value being tested is null.  In that case, we will take this early return:
```
    if (type.nullable && value === null)
    {
        // This is fine
        return;
    }
```

2) The value being tested is not null.  In that case, we will reach this code:
```
    if (!(type in this.members))
    {
        throw new IdlHarnessError("Unrecognized type " + type);
    }
```
and throw.

So the real question is why the `onunload` attribute is set to something non-null, right?

When I run the test locally using Geckos WPT harness, it gets set from somewhere inside marionette.  I dunno where it gets set from in the test harness as it runs for wpt.fyi purposes, because I'm not sure what harness that is, exactly, or why that might be racy.  There's a good chance the relevant bit of harness is Firefox-specific, and if so that would explain why the raciness only affects Firefox.  (One reason might be if the harness sets `window.onunload` from an extension or something: in Firefox that will affect the value of `window.onunload` that the web page sees, while in Chrome and Safari it will not.)

**Comment by bzbarsky** [comment]
And presumably we should fix that idlharness bug around callbacks anyway, and add some tests for actual cases where the callback's value is not null.

**Comment by lukebjerring** [comment]
That makes more sense - I've dealt with `add_dependency_idls` bugs/shortcomings so many times I jumped the gun.

I'll put together, at the least, a placeholder `IdlCallback` that just asserts it's value's type is a function. Then, real tests about signature etc can be iterated on at a later date. Thanks for the lead!

**Comment by bzbarsky** [comment]
So at least when I am running this in Gecko's test harness, the setting of `onunload` comes from https://searchfox.org/mozilla-central/rev/40e889be8ff926e32f7567957f4c316f14f6fbef/testing/marionette/evaluate.js#133 and the script it's evaluating is:
```
 __webDriverArguments.push(rv => __webDriverCallback(rv));(function() {
  // We have to set the url here to ensure we get the same escaping as in the harness
  // and also to handle the case where the test changes the fragment
  window.__wptrunner_url = "/html/dom/interfaces.https.html?include=HTML.*";
  window.__wptrunner_testdriver_callback = arguments[arguments.length - 1];
  window.__wptrunner_process_next_event();
}).apply(null, __webDriverArguments)
```
which looks like webdriver stuff interacting with https://github.com/web-platform-tests/wpt/blob/8c0c1caee779ea4ad0dee2484be0234d14f54b7b/tools/wptrunner/wptrunner/executors/testharness_webdriver_resume.js for whatever that's worth.

**Comment by bzbarsky** [comment]
I do think we should fix the wpt harness here to not make test-visible changes to the DOM state, in general, in addition to fixing idlharness.

**Comment by foolip** [comment]
I feel like @gsnedders might know the code being injected there.

**Comment by bzbarsky** [comment]
I suspect the important part is the code doing the injecting, not the code being injected.  I'd hope @jgraham knows something about that.

**Comment by lukebjerring** [comment]
Flakiness seems indeed resolved [for latest runs](https://wpt.fyi/results/html/dom?label=master&label=experimental&max-count=10&to=2019-07-23T00%3A00%3A00.000Z&product=firefox&q=seq%28%28status%3Apass%7Cstatus%3Aok%29+%28status%3A%21pass%26status%3A%21ok%26status%3A%21unknown%29%29+seq%28%28status%3A%21pass%26status%3A%21ok%26status%3A%21unknown%29+%28status%3Apass%7Cstatus%3Aok%29%29) vs [5 days ago](https://wpt.fyi/results/html/dom?q=seq%28%28status%3Apass%7Cstatus%3Aok%29+%28status%3A%21pass%26status%3A%21ok%26status%3A%21unknown%29%29+seq%28%28status%3A%21pass%26status%3A%21ok%26status%3A%21unknown%29+%28status%3Apass%7Cstatus%3Aok%29%29&run_id=286000002&run_id=280130006&run_id=282140005&run_id=249750009&run_id=243760006&run_id=282160001&run_id=265670002&run_id=265650002&run_id=285980002&run_id=289940001)

**Comment by bzbarsky** [comment]
Fwiw, both those links are showing the same data for me: they claim to be "latest master test runs from the last 6 days" and "latest test runs for the default product set" but are showing runs from Jul 22.

**Comment by lukebjerring** [comment]
Copy-paste failure on my part! Updated now.

**Comment by bzbarsky** [comment]
That first link now shows no results at all...
