### ISSUE TITLE
Deleted tests are ERROR instead of MISSING for Taskcluster results 

### ISSUE THREAD

**Issue by lukebjerring** [web-platform-tests/wpt#14568]
From https://github.com/web-platform-tests/wpt/commit/79001b1d0d4a111b7f44608404d7b5504d755a1c

[Chrome diff](https://staging.wpt.fyi/results/resource-timing?diff&run_id=6508819563675648&run_id=6003242655809536)
[Firefox diff](https://fyi-dot-wptdashboard-staging.appspot.com/results/resource-timing?diff&run_id=5481842887098368&run_id=5893510804799488)

Both [results for 79001b1d0d4a111b7f44608404d7b5504d755a1c](https://staging.wpt.fyi/results/resource-timing?sha=79001b1d0d&q=resource_timing_) include attempting to run the deleted files:
- /resource-timing/resource_timing_buffer_full_when_populate_entries.html
- /resource-timing/resource_timing_store_and_clear_during_callback.html

**Comment by lukebjerring** [comment]
@Hexcles @foolip I think this relates to the `--affected` flag changes, but digging further to prove it.

**Comment by jgraham** [comment]
Even if we pass a deleted path to wptrunner it should just ignore it, so I think something strange must be happening at a different layer.

**Comment by Hexcles** [comment]
I think this is a manifest issue.

To reproduce a similar problem locally:

1. `./wpt manifest` to make sure you have an up-to-date manifest. `grep html/semantics/interfaces.html MANIFEST.json` shows three matches (a testharness test entry and a file checksum).
2. `rm html/semantics/interfaces.html && git commit -am 'test'`
3. `./wpt manifest` again. `grep html/semantics/interfaces.html MANIFEST.json` still shows two matches. The file checksum is gone, but the testharness test is still there.
4. `./wpt run firefox html/semantics/interfaces.html` will give you ERROR because the runner thinks the test exists.
5. Interestingly, running `./wpt manifest` again removes the testharness test entry.
