### ISSUE TITLE
wptserve sub filter: cannot substitute headers which were not sent

### ISSUE THREAD

**Issue by jeremyroman** [web-platform-tests/wpt#14572]
e.g. writing this: `{{headers[Referer]}}`

works if there is a Referer header, but raises an exception if the header was not sent. In my use case I'd like to still be able to proceed in this case.

The simplest solution would seem to be to modify the way the templates treat indexing with square brackets to catch KeyError and produce a blank value such as `''` instead (and I have a commit that would make that change).

It would be possible to do something more sophisticated, like add some other syntax for reading a header or a default value, perhaps something like `{{header_or_default(Referer, none)}}`, but this seems like it might be overkill.

The major downside would be that typos in header names in tests might be more difficult to catch, since they would yield a blank result instead of a noisy exception.

WDYT?

**Comment by jugglinmike** [comment]
I've been trying to think of a way to support your use case without making the infrastructure less capable of catching mistakes, but I've got nothing so far. I do have a few ideas to mitigate the risk, though:

- limit the fallback behavior to the `headers` object (similar to [what we already do for `GET`](https://github.com/web-platform-tests/wpt/blob/4984b190341b535c645729b8f99247aace0022fe/tools/wptserve/wptserve/pipes.py#L465-L466))
- in the event of a KeyError, emit a more disruptive/descriptive value instead of the empty string (e.g. `key-not-defined` or `key-not-defined:{{keyname}}`)
