### ISSUE TITLE
[css-contain] Doubts about 2 tests

### ISSUE THREAD

**Issue by frivoal** [web-platform-tests/wpt#14601]
Hi @mrego,

The following two tests don't look right to me. Are you sure the spec calls for that?

https://github.com/web-platform-tests/wpt/blob/master/css/css-contain/contain-layout-baseline-004.html
https://github.com/web-platform-tests/wpt/blob/master/css/css-contain/contain-layout-baseline-005.html

cc: @tabatkins

**Comment by dholbert** [comment]
I think the tests are referring to https://drafts.csswg.org/css-contain-1/#containment-layout :
> 7. For the purpose of the vertical-align property, or any other property whose effects need to relate the position of the containing element’s baseline to something other than its descendants, the containing element is treated as having no baseline.


I agree that contain-layout-baseline-004.html looks wrong. Its testcase has a single table with two table-cells, and it's asserting that the two cells should be misaligned. That doesn't make sense; the cells end up in a single table row, independent of whether they have baselines or not.

Perhaps @mrego meant to put the two table cells in *separate* tables? (I think then it might be correct...)

On the other hand, contain-layout-baseline-005.html is broader and looks roughly correct to me at first glance -- @frivoal , was there a specific part of that test you were concerned with?

**Comment by dholbert** [comment]
(Note that https://bugzilla.mozilla.org/show_bug.cgi?id=1508441#c2 is filed on some known issues where Firefox isn't suppressing baseline alignment correctly for some `contain:layout` elements. I suspect that we'll pass contain-layout-baseline-005.html when that bug is fixed, and probably a fixed-up version of contain-layout-baseline-004.html (with separate tables rather than a single table).

**Comment by mrego** [comment]
About `contain-layout-baseline-004.html` I was actually trying to test what I'm testing there, but maybe I understood something wrong.
Let's use a different example with texts that might be easier to follow:
```html
<table style="border: solid thick;">
  <tr>
    <td style="vertical-align: baseline;">foo</td>
    <td style="font-size: 50px; vertical-align: baseline;">bar</td>
  </tr>
</table>
```

![Output with texts baseline aligned](https://user-images.githubusercontent.com/11602/50246865-bcfb9600-03d6-11e9-8c29-5c462b28f736.png)

Here both texts "foo" and "bar" are baseline aligned.

What happens if we apply `contain: layout` in the second cell?
If we treat that second cell as having no baseline, we should use it's synthetized baseline instead.

```html
<table style="border: solid thick;">
  <tr>
    <td style="vertical-align: baseline;">foo</td>
    <td style="font-size: 50px; vertical-align: baseline; contain: layout;">bar</td>
  </tr>
</table>
```

![Output with texts not baseline aligned](https://user-images.githubusercontent.com/11602/50246890-c8e75800-03d6-11e9-8e79-07a50b9f1e5b.png)

This is the current behavior in Chromium/Blink, but I guess it can be wrong. I'd like to understand what should be the expected behavior here and fix the code.

The thing about testing tables mentioned by @dholbert should be covered by one of the cases in `contain-layout-baseline-005.html`. As @dholbert I don't know what @frivoal was not getting from this one. Note that it's somehow based on https://github.com/web-platform-tests/wpt/blob/master/css/vendor-imports/mozilla/mozilla-central-reftests/contain/contain-layout-suppress-baseline-002.html and that it still doesn't pass in Chromium due to a different bug (issue https://github.com/w3c/csswg-drafts/issues/3416).

**Comment by frivoal** [comment]
@mrego I now understand what you're going after in -004: I guess my assumption was that regardless of how you baseline align the two cells, after that they would still be stretched to fill the whole height of the row, and that yes, contain:layout would have the alignment effect you are testing for, but that this would not be visible as two misaligned background colors. That said, this is probably an underspecified area of tables. @FremyCompany , what do you think?

(I think @dholbert is right that it would be correct with 2 tables, but maybe it is already correct now. I am not sure)

As for -005, I now agree that it is correct.

**Comment by FremyCompany** [comment]
At first sight, the table test looks ok to me based on the current iterations of all the specs involved. If one of the cell start to use its bottom as the baseline while the other uses its text baseline, the end results would be that both text are not aligned in the end. This is different from if the second cell as bottom-aligned (in which case since they have the same height, they would match just because there is no padding to be added to preserve the constraints).

Florian is right that the cells end up growing to match the row height, but they don't do that by moving their content, only by increasing padding in directions to fill the remaining space. In case cells are baseline-aligned, that has potentially to happen in both directions.

I'm more concerned about the fact that this actually isn't helping much, because in the case of tables, you still need to compute the layout of all table cells to dimension the tracks properly, and trac size affect all table cell final layouts so I'm not sure if the promise of the property is achievable for table-cells. I'd rather have the property not apply to table-cell at all, instead of just blocking size but allowing layout. That sounds weird to me.

> When laying out the page, the contents of separate containing elements can be laid out in parallel, as they’re guaranteed not to affect each other.

You cannot do this for table-cells. Their final layout pass requires to know the row height, and the row height depends on all table-cells in the row.

**Comment by dholbert** [comment]
I think both tests are correct. Firefox initially failed -004, but I made it pass in https://phabricator.services.mozilla.com/D37118 by adjusting our table-cell code to make `contain:layout` suppress the table cell's baseline.
