### ISSUE TITLE
Document why there is a path length limit or lift it

### ISSUE THREAD

**Issue by annevk** [web-platform-tests/wpt#15355]
It's very easy to hit in `html/`.

**Comment by gsnedders** [comment]
@jgraham can you remember if we actually hit this in mozilla-central at some point? do you know if it's still the case that it's a problem?

**Comment by jgraham** [comment]
In the past it was the case that third party tools like mercurial and zip didn't support >255 characters, so even if we prefix everything with `\\?\` then other parts of the infrastructure would break. So I don't think there's much we can do here unless the Windows situation in all the environments we intend to support has markedly improved in the last 4 years.

**Comment by jgraham** [comment]
Oh and for clarity, yes this was a real problem that blocked running wpt in m-c until it was fixed.

**Comment by LukeZielinski** [comment]
Triage: so it sounds like lifting the limit is unlikely, but documenting the reasons still makes sense. Adding backlog priority.

**Comment by jugglinmike** [comment]
The docs already explain the rationale:

> Due to path length limitations on Windows, test paths must be less that 150 characters relative to the test root directory (this gives vendors just over 100 characters for their own paths when running in automation).

I'm not sure how to proceed since [this explanation was present at the time this issue was filed](https://github.com/web-platform-tests/wpt/commit/4489ad98946). Normally, this would be a sign that the information is too hard to find, but it's already pretty central: the "File Path and Names" section of the "General Test Guidelines" page.

That page is hierarchically "below" the "Writing Tests" page, so we *could* move the information up, but I personally don't think this consideration is essential enough to warrant such a promotion.

@annevk do you have thoughts about how we can make this easier to find?

**Comment by annevk** [comment]
Nah, let's close this then.
