### ISSUE TITLE
TaskCluster Chrome builds failing

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#16448]
We last got a master run for Chrome in 4131304.

Ever since, we've got:

```
SessionNotCreatedException: session not created (500): session not created: This version of ChromeDriver only supports Chrome version 76
```

We seem to be running ChromeDriver 76.0.3775.0; but the google-chrome-unstable package is only 75.0.3766.2-1. Canary is currently 76, but given we're running dev on Linux (where there is no canary package), and dev is 75, we end up with this error. Presumably we're downloading ChromeDriver for canary and not dev, and this breaks in the brief periods where canary and dev have different versions?

**Comment by gsnedders** [comment]
This is also causing any PR that runs `infrastructure` to fail.

**Comment by Hexcles** [comment]
> Presumably we're downloading ChromeDriver for canary and not dev, and this breaks in the brief periods where canary and dev have different versions?

This is basically correct. The only caveat is that technically in this case we are downloading ChromeDriver for the tip of the tree (which is roughly Canary).

We do try to download the correct version of ChromeDriver by following this [algorithm](http://chromedriver.chromium.org/downloads/version-selection), which works well for Stable & Beta. The problem is that ChromeDriver [does not release on Dev channel yet](https://crbug.com/chromedriver/2656), so when we are testing Dev/Unstable, we fall back to TotT ChromeDriver, which is a few days ahead of Dev/Unstable.

There are three ways that I can think of to work around of this issue:
1. Release ChromeDriver Dev, too (the best approach IMHO, but blocked on ChromeDriver folks to figure out the process).
2. Use some [Omaha](https://omahaproxy.appspot.com/) magics to figure out which source revision the Dev channel is on, and download ChromeDriver from that specific revision.
3. Unleash the forbidden force (a hidden flag) to override ChromeDriver's version check.

**Comment by gsnedders** [comment]
@Hexcles I think we need ChromeDriver Dev (it doesn't really make sense it's available for every other channel!), but we need to workaround this in the short term. Use the hidden flag?

**Comment by rakuco** [comment]
Reopening. See https://tools.taskcluster.net/task-group-inspector/#/Xz1EYlhoRDuk_mWUN7G5hg from #16559:

````
Downloading ChromeDriver from https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/652427/chromedriver_linux64.zip
[...]
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/652427/chromedriver_linux64.zip
````

https://omahaproxy.appspot.com/deps.json?version=75.0.3770.9 (the latest stable version at the time of writing) has `"chromium_base_position": "652427"`, but according to https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Linux_x64/ there are releases for r652421 and r652428. This is probably related to M75 having been branched from master last Friday and ChromeDriver not updating their release files.

**Comment by gsnedders** [comment]
See also https://bugs.chromium.org/p/chromedriver/issues/detail?id=2656#c21 for some further comments, including:

> For instance, currently the Mac Dev is 75.0.3770.8 r652427, but we don't have a build at r652427 on the Mac waterfall builder.

**Comment by gsnedders** [comment]
So, to workaround, we have two options now:

* Get the parts of the Chrome team who care about WPT to convince other parts of the Chrome team to release ChromeDriver alongside Chrome for all channels.
* Pass the undocumented override flag to ignore the version check and hope it works.

**Comment by jgraham** [comment]
We should 100% do the hacky thing in the short term. The situation where Chrome is failing on all macOS jobs and making it look like all PRs fail is pretty untenable, and option 1 is not something we can fix in a period of days.

**Comment by rakuco** [comment]
@Hexcles will the existing Chromium PRs that failed due to Taskcluster all need to be retriggered manually?

**Comment by Hexcles** [comment]
@rakuco yeah I'm in the middle of it

**Comment by Hexcles** [comment]
Well I think I've handled the bulk of it, but may have missed a few. Apologies in advance. If anyone suspects their PR was affected by this and hasn't been restarted, please try closing and reopening the PR.
