### ISSUE TITLE
Bring manifest parsing in the web-based runner up to date

### ISSUE THREAD

**Issue by sideshowbarker** [web-platform-tests/wpt#16471]
http://web-platform.test:8000/tools/runner/index.html is currently failing to actually run any tests, due to it failing internally to parse the manifest.

The manifest parsing needs to be brought up to date so that it’s in sync with the manifest parsing used by the command-line runner and other parts of the system.

**Comment by gsnedders** [comment]
So I think there are two bugs here:

```
runner.js:642 Uncaught TypeError: Cannot read property 'map' of null
    at Results.to_json (runner.js:642)
    at VisualOutput.on_done (runner.js:337)
    at runner.js:783
    at Array.forEach (<anonymous>)
    at Runner.done (runner.js:782)
    at Runner.do_start (runner.js:747)
    at Runner.start (runner.js:723)
    at TestControl.<anonymous> (runner.js:538)
```

This is ultimately caused by it finding no tests, but we should handle the case whereby it finds no tests better. (Bug 1)

The actual cause of it finding no tests is fixing all the cases in the manifest generation where we encoded the `url_base` in the item URLs (which it never should have been!), and the JS runner assuming the item URLs are absolute paths.
