### ISSUE TITLE
External network fetch causes a CRASH in Firefox

### ISSUE THREAD

**Issue by lukebjerring** [web-platform-tests/wpt#17977]
In /html/dom/interfaces.https.html on the network,`foo` is resolving to a machine, which causes the following `CRASH` in Firefox:

     0:07.90 TEST_START: /html/dom/interfaces.https.html?include=HTML.*
     0:09.10 pid:57928 FATAL ERROR: Non-local network connections are disabled and a connection attempt to foo ([Redacted]) was made.
     0:09.10 pid:57928 You should only access hostnames available via the test networking proxy (if running mochitests) or from a test-specific httpd.js server (if running xpcshell tests). Browser services should be disabled or redirected to a local server.

**Comment by Hexcles** [comment]
The network request to `foo` might have long existed (it might be a recent network change in our office).

I can think of two courses of actions (not exclusive):
1. Find out where the network request is made. Presumably the test needs a failed network request to construct some object(s), and we should use `nonexistent` for that.
2. Perhaps browsers should just reject all external network requests instead of hard crashing? @jgraham

**Comment by Hexcles** [comment]
The first one is easy. I found:
https://github.com/web-platform-tests/wpt/blob/98a383468cf72dbecc825a17ba73097d2fa43dc0/html/dom/interfaces.https.html#L203

**Comment by jgraham** [comment]
It's probably possible to do something better than crashing here, but the behaviour isn't that easy to change (requires writing C++ code in the gecko networking library) and is probably undesirable for non-wpt suites, so I'd at least need to be convinced that the tradeoff is worth it.

**Comment by jgraham** [comment]
Like, maybe you could just add something like
```
    mCondition = NS_ERROR_CONNECTION_REFUSED;
    OnSocketDetached(nullptr);
    return mCondition;
```
at https://searchfox.org/mozilla-central/source/netwerk/base/nsSocketTransport2.cpp#1285 if some additional environment variable was set, but I don't know the gecko networking code well enough to be sure that's not going to cause some other problems.
