### ISSUE TITLE
Experiment: run Gecko's mochitests with some adapter code

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#19438]
This is from discussion with @wisniewskit, @tdsmith and @zcorpan at https://2019.viewsourceconf.org.

As a way to understand what can be learned from all vendor-specific tests and specifically Gecko's mochitests, we could try something like this **on a branch**:
- Find a bunch of mochitests and put them in a directory of wpt
- Hack something in the manifest code to detect them and the executors to inject some adapter code to provide the mochitest APIs but report results in the testharness.js test/subtest format
- Run this against Chrome, Edge and Firefox
- Compare the cross-browser results and see where most of the differences are.

@jgraham do you think this would work, and that something interesting could be learned?

**Comment by foolip** [comment]
https://wpt.fyi/results/css/vendor-imports/mozilla/mozilla-central-reftests?q=is%3Adifferent&run_id=320630013&run_id=332270002&run_id=328590003 is another vendor test suite that we do have results, and the differences there suggest that there could be value in stuff like this. That test suite reveals a lot of Safari-specific failures and Firefox-only passes, both of which are interesting categories.

**Comment by jgraham** [comment]
I think there is some value here, but I have in the past raised the concern that if we provide too much support for vendor testsuites, we don't end up with a shared testsuite but a collection of mutually-unintelligable testsuites contributed by each vendor, such that anyone wanting to modify them has to learn N different testing formats.

So, as an experiment I'm happy to do this on a branch and get one-off results. I'd be more opposed to a long term plan to incorporate these tests as-is.

Technically note that mochitests don't really have the concept of subtests and tend to fall over after the first failure (because they weren't intended to support long-term fails), so all the problems of cross-browser comparison where the subtests don't match up between browsers will be writ large on any such comparison.

I don't know if it was intention or oversight, but I'm much more interested in Firefox, (Chrome|Edge) & *Safari* results than anything with two blink-based browsers but no WebKit.

**Comment by foolip** [comment]
These are all good concerns I think, to have another read-only directory like css/vendor-imports wouldn't be great. And even if the tests aren't actually in the tree and are just run via some "extra stuff" mechanism some of the same issues apply. I hope that if we identify some part of mochitests that surface especially many browser inconsistencies, then converting/upstreaming those might be prioritized.

It has of course crossed my mind to do something similar to WebKit's js-test.js tests, and there too identifying the valuable tests would be step 1, step 2 quite unclear.

The lack of subtests probably means we'll need to wrap this as single-page tests, which is unfortunate in that different ways of failing will be hard to tell apart, but I guess we'd just look at the results and see if any signal can be extracted.

For these purposes I think it's simplest to just exclude new Edge since it's also Chromium, but maybe adding Edge classic could reveal a smaller number of extra interesting tests, maybe the 2/2 splits. The two categories I mentioned are just the ones that seem to account for most of the tests in the `is:different` query.

**Comment by foolip** [comment]
@wisniewskit is this something you'd like to work on? Wondering what priority to set and whether to assign you :)

**Comment by foolip** [comment]
@Hexcles this is the issue I mentioned to you.

While I haven't mentioned it here, getting results into wpt.fyi from Test262, the WebGL test suites or other things that we can't easily just merge into WPT might use a "some adapter code" approach as well. But I think in each case an experiment to show value is needed before considering landing code for long term support of something like it.

**Comment by foolip** [comment]
https://github.com/web-platform-tests/wpt/issues/8308 is similar to this, I didn't remember that there was an issue. Some work was done for it in https://github.com/web-platform-tests/wpt/pull/8980, but not merged.

**Comment by foolip** [comment]
I filed this, and I'm not pursuing it, so closing.
