### ISSUE TITLE
[offscreen-canvas] Procedurally-generated tests are invalid

### ISSUE THREAD

**Issue by jugglinmike** [web-platform-tests/wpt#20180]
Many of the tests which are generated programmatically report results before any assertions are made. The tests' "template" code defines a single subtest:

    var t = async_test("%(escaped_desc)s");
    t.step(function() {

    var offscreenCanvas = new OffscreenCanvas(100, 50);
    var ctx = offscreenCanvas.getContext('2d');

    %(code)s
    t.done();

    });

Although declared using the `async_test` API, the invocation of the `t.done` method in the test body makes these tests fully synchronous. However, many of the code excerpts used to expand this template include asynchronous operations, e.g. [`compositing/2d.composite.canvas.copy.html`](https://github.com/web-platform-tests/wpt/blob/192a7c9ae8683984ef180d1bd9edc57b2f000072/offscreen-canvas/compositing/2d.composite.canvas.copy.html)

In the absence of additional subtests, asynchronous code cannot influence the results reported by testharness.js.

There are many ways this could be addressed, but the most straightforward may be to relocate the invocation of `t.done` from the template and into each of the code excerpts. This would also be a good opportunity to wrap asynchronously-executed functions with the `t.step_func` method (otherwise, test failures will be reported as harness errors).

/cc @AmeliaBR @annevk @kenrussell @fserb

**Comment by guest271314** [comment]
Another issue, as described at https://github.com/web-platform-tests/wpt/issues/19799 and https://github.com/web-platform-tests/wpt/pull/19818 is that 

```
var offscreenCanvas = new OffscreenCanvas(100, 50);
var ctx = offscreenCanvas.getContext('2d');
```
throws an error at Firefox due to `OffscreenCanvasRenderingContext2D` not being implemented. As suggested, for completeness, the exisitence of `OffscreenCanvasRenderingContext2D` could be checked before executing `getContext()`. The result of the current test coul be inferred as `null` being the return value of `getContext()` though that is not the case at Firefox.

**Comment by guest271314** [comment]
@annevk If in fact the specification does mandate that the return value for `getContext("2d")` MUST be `null` https://github.com/web-platform-tests/wpt/pull/19818#issuecomment-544839988 should not the relevant `OffscreenCanvasRenderingContext2D` tests actually test https://bugzilla.mozilla.org/show_bug.cgi?id=801176#c147 for that output?
