### ISSUE TITLE
Avoid the use of BroadcastChannel (global state) in scroll-to-text-fragment tests

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#20269]
In https://github.com/web-platform-tests/wpt/pull/20184 the scroll-to-text-fragment.html test was found to be flaky, which @stephenmcgruer and @nickburris discussed in the [Chromium CL](https://chromium-review.googlesource.com/c/chromium/src/+/1903624/7#message-dc718a7b6310caf8e945d29d2c465475aa032809).

It sounds like the problem is with the use of BroadcastChannel. Filing this issue to track using the stash feature of wptserve instead.

@nickburris I'm unable to assign this to you because you're not a member of the web-platform-tests org. I've sent you an invite for that :)

**Comment by foolip** [comment]
@nickburris also, can you add a META.yml to this directory? And maybe rename https://wicg.github.io/ScrollToTextFragment/ to https://wicg.github.io/scroll-to-text-fragment/?

**Comment by nickburris** [comment]
Thanks for filing this! Sure, I'll also add a META file and I'll look into renaming the wicg repo.

**Comment by nickburris** [comment]
@foolip Philip, I have a change open[1] to convert to using Stash (also adds the META.yml), but it's still flaky. Would it be okay to land that change while I continue investigating the source of flakiness? It's strictly better, as it uses Stash instead of the non-interoperable BroadcastChannel. The BroadcastChannel solution times out when certain tests fail, making it harder for me to debug and do parallel work. The Stash solution fails properly instead of timing out in these cases (but is still flaky for some other reason).

[1] https://chromium-review.googlesource.com/c/chromium/src/+/1925428

**Comment by foolip** [comment]
@nickburris yes, if no new tests are made flaky by that and it's closer to the right solution, then landing that would be an improvment. The export PR will likely get stuck and need manual intervention, I'll comment on https://github.com/web-platform-tests/wpt/pull/20328.

**Comment by nickburris** [comment]
The [test results](https://wpt.fyi/results/scroll-to-text-fragment) are no longer flaky. Indeed the issue appears to have been BroadcastChannel, and I accidentally introduced a different source of flakiness (not closing test windows) when I made the change to using Stash, which is now fixed.
