### ISSUE TITLE
test_driver.click(button) doesn't work in iframes

### ISSUE THREAD

**Issue by jan-ivar** [web-platform-tests/wpt#20282]
The awesome user gesture automation tool `test_driver.click()` added in web-platform-tests/wpt#6897, unfortunately doesn't work in iframes, which blocks us from testing the ["display-capture"](https://w3c.github.io/mediacapture-screen-share/#feature-policy-integration-0) feature-policy, because [getDisplayMedia](https://w3c.github.io/mediacapture-screen-share/#dom-mediadevices-getdisplaymedia) requires [user activation](https://html.spec.whatwg.org/multipage/interaction.html#triggered-by-user-activation).

cc @gsnedders @jgraham

**Comment by gsnedders** [comment]
#17260 should have made it work, I thought. Maybe it doesn't, maybe we regressed it. :(

**Comment by jan-ivar** [comment]
@gsnedders [We're hitting](https://github.com/web-platform-tests/wpt/pull/20314/files#diff-3d959b7cd0491e20b2de4f01f05f680cR16) this line: https://github.com/web-platform-tests/wpt/blob/bdad828b7b7d796eaa4e8ecdcf0156d7172d8ce7/resources/testdriver.js#L99

**Comment by jan-ivar** [comment]
And I tried removing that line, but it then causes timeouts—presumably from missing buttons?
```
TIMEOUT Default "display-capture" feature policy ["self"] allows same-origin iframes. - Test timed out
TIMEOUT Default "display-capture" feature policy ["self"] disallows cross-origin iframes. - Test timed out
TIMEOUT Feature policy "display-capture" can be enabled in cross-origin iframes using "allow" attribute. - Test timed out
TIMEOUT /screen-capture/feature-policy.https.html
```
They used to pass before we [added user gesture](https://bugzil.la/1580944) in Firefox.

**Comment by gsnedders** [comment]
Well that doesn't seem very useful. We should fix this more usefully. 🙃

**Comment by foolip** [comment]
In https://chromium-review.googlesource.com/c/chromium/src/+/2283968/14/third_party/blink/web_tests/external/wpt/resources/chromium/webxr-test.js there's a workaround for this issue, making the setup non-cross-browser.

That seems unfortunate.

@stephenmcgruer have you come across other tests working around this? I'm wondering if we might have accumulated enough cases to make this worth prioritizing.

**Comment by klausw** [comment]
FWIW, I had copied this non-cross-browser setup from Chromium's [web_tests/fullscreen/trusted-click.js](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/web_tests/fullscreen/trusted-click.js), it's used by [several fullscreen tests](https://source.chromium.org/search?q=trusted_click&sq=&ss=chromium%2Fchromium%2Fsrc:third_party%2Fblink%2Fweb_tests%2Ffullscreen%2F) there. It looks as if these correspond to multiple [manual fullscreen tests](https://github.com/web-platform-tests/wpt/search?q=trusted_click&unscoped_q=trusted_click) in WPT.

**Comment by klausw** [comment]
Correction, my workaround was based on a simplified version that just uses eventSender to click at coordinates (0, 0) which was good enough for this specific use case. A more general solution would get more complicated if it needs to calculate specific coordinates for elements, especially since AFAIK a cross-origin iframe can't portably determine its position within the parent. The Chromium trusted_click function takes a clickRectInRootFrameCoordinate argument to explicitly pass this in. 

(I had experimented with using sendMessage to store the iframe position in an ad-hoc [window property](https://chromium-review.googlesource.com/c/chromium/src/+/2283968/12/third_party/blink/web_tests/external/wpt/webxr/dom-overlay/iframe-oopif.sub.https.html#120) that can be [read by simulateUserActivation](https://chromium-review.googlesource.com/c/chromium/src/+/2283968/12/third_party/blink/web_tests/external/wpt/resources/chromium/webxr-test.js#73), but that seems rather hackish.)

**Comment by stephenmcgruer** [comment]
This came up in discussion with @jgraham today too. It seems like at some point some support was added specifically for actions in `testdriver.js` - a9d6d1b058f9d37cabaf735ea60f9b87acc8a02b - but not for any other sort of interaction.

I may be over-looking something important, but it seems like we could just naively do a switch-to-frame, do-command, switch-back approach for every testdriver.js interaction and that would work? Would need some investigation and debugging to prove it out.

**Comment by jgraham** [comment]
Yes, I think for frames that would work. For windows it's a bit more complex because currently it's a pain to get the window handle for a given dom window (WebDriver supports this but implementations don't). It's also a pain to start an interaction from outside the main window; if we want to support that we'll probably need some API surface for postMessaging actions up to the main window.

**Comment by gsnedders** [comment]
And as @jgraham pointed out on IRC, `noopener` also makes windows harder.

**Comment by jgraham** [comment]
This is now fixed for all cases where the test window and window where the interaction is taking place can get handles to each other (i.e. excluding rel=noopener and similar).
