### ISSUE TITLE
[css-text] trailing-ideographic-space-003 test is incorrect

### ISSUE THREAD

**Issue by javifernandez** [web-platform-tests/wpt#20325]
The [trailing-ideographic-space-003](https://github.com/web-platform-tests/wpt/blob/master/css/css-text/white-space/trailing-ideographic-space-003.html) test defines an incorrect expected result, according to the resolution of the [ICU issue 20843](https://unicode-org.atlassian.net/browse/ICU-20843). 

The tests tries to verify that the trailing ideographic spaces hang when the text overflows. However, the  あ grapehme (Hiragana U+3042) is handled as [ID ](https://www.unicode.org/reports/tr14/#ID) class by the unicode line-breaking algorithm.

Since there are breaking opportunities between any pair of ID graphemes, and give than ideographic space is a BA, which forbids breaking before, the line-breaking  algorithm breaks the line after the fist Hiragana character to avoid overflow.

I think we should, either correct the test, maybe using an Small Hiragana letter (in combination with 'strict') or just remove it and try to define a new one for the behavior we want to verify.

**Comment by frivoal** [comment]
No, actually I think this test is right.

You are correct about the position of the wrapping opportunities (marked with a |):
`あ|あ&#x3000;|あ|あ`

However, in [css-text-3 section 4.1.3](https://drafts.csswg.org/css-text-3/#white-space-phase-2) bullet point 4 subpoint 2, there is also the requirement to hang any sequence of "white space, and/or other space separators". U+3000 is an "other space separator", so it must hang, just like a (preserved) space would.

**Comment by javifernandez** [comment]
The problem is that in order to determine the portion of the text susceptible of being hung we need to select the breaking opportunity, so that the rest of the text overflows. Actually, at the end of the [4.1.1. Phase I](https://drafts.csswg.org/css-text-3/#white-space-phase-1) it's stated that the text should be wrapped before running the trimming phase:

> Then, the entire block is rendered. Inlines are laid out, taking bidi reordering into account, and wrapping as specified by the white-space property.

Maybe I'm not interpreting that statement correctly, but as I read it, it means that we must break the line after the first Hiragana. I think your point would be valid if the U+3000 sequence would follow the last Hiragana fitting in the line.

**Comment by frivoal** [comment]
If you replace U+3000 with an ordinary U+0020 space, chrome (and other browsers) will correctly hang the space. The rule that asks for that is the same one that is the basis of this test. According to the spec, if you're doing one, you should be doing the other as well.

I guess the reason it may not be obvious is that the part of the spec you quoted in "phase I" wants you to follow the details of phase to phase 2 in order to layout the inlines taking the white space property into account, but it doesn't have an explicit reference to phase 2, so it could be read as phase 2 being something you have to do after that, rather than something that gives you information on how to do that. I suppose a parenthetical at the end of the sentence you quoted, saying "`(see phase 2)`" would make that clearer.

**Comment by frivoal** [comment]
@javifernandez The spec has now been clarified. I think we can close. Can you confirm?

**Comment by javifernandez** [comment]
Yes, we can close this issue now.
Thanks.
