### ISSUE TITLE
Frequent "Run failed: epochs - master (ccf3169)" on fork

### ISSUE THREAD

**Issue by jakearchibald** [web-platform-tests/wpt#20700]
I have a fork of web-platform-tests (https://github.com/jakearchibald/web-platform-tests) and for some reason I'm getting an email saying "Run failed: epochs - master (ccf3169)".

I'm not sure what this means, or how to stop it.

**Comment by stephenmcgruer** [comment]
@LukeZielinski has run into this previously I think, I'm not sure if he or @Hexcles pursued the fix.

We should generally make sure our actions don't run on forks.

**Comment by LukeZielinski** [comment]
Yeah a fix was attempted in https://github.com/web-platform-tests/wpt/pull/20412 but it didn't seem to eliminate the email spam. I still get emails, but now they just don't list any failed jobs, which is even more confusing (example below).

I ended up resorting to setting up an email filter and forgot about this. So more needs to be done here.

## Example
Run failed for master (ec26269)
Repository: LukeZielinski/wpt
Workflow: epochs
Duration: 3.0 seconds
Finished: 2019-12-12 12:10:46 UTC


View results

Jobs:
—
You are receiving this because this workflow ran on your branch.
Manage your GitHub Actions notifications here.

**Comment by Hexcles** [comment]
Sigh, GitHub Actions considers a workflow with no jobs a failure:

https://github.community/t5/GitHub-Actions/Status-of-workflows-with-no-running-jobs/td-p/37160
https://github.community/t5/GitHub-Actions/Skip-running-workflows/m-p/37404

It seems like the only reasonable workaround is to add a no-op job to those workflows.

**Comment by Hexcles** [comment]
@LukeZielinski could you rebase your fork and verify?

**Comment by LukeZielinski** [comment]
Done, at first glance it looks good (based on the [manifest action](https://github.com/LukeZielinski/wpt/commit/f1ddc81d2e60b6b7ecc7e862898f76e5d5b72c65/checks?check_suite_id=357336440)). Assuming epochs will behave as well, but will ping here if it doesn't.
