### ISSUE TITLE
Edge Dev/Canary runs missing since Dec 20th

### ISSUE THREAD

**Issue by stephenmcgruer** [web-platform-tests/wpt#20903]
Looks like Edge Dev/Canary runs stopped since Dec 20th; the last successful run was Dec 20th 02:40 https://wpt.fyi/runs?label=master&label=experimental&max-count=100&product=chrome&product=edge&product=firefox&product=safari&product=webkitgtk).

Looking at Azure (https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=39305&view=results), the Edge runs are all 'Queued', which I assume means builders aren't available for some reason.

**Comment by mustjab** [comment]
@stephenmcgruer I see a bunch of runs in running state now. Our rebuild of Windows VMs happens on a weekly schedule every Sunday, so that probably unblocked these runs. I can't tell why the runs got stuck as we've already destroyed these VMs to replace them with new ones. 

Let me know if we see this repro again and hopefully we'll be able to get to test VMs before they're rebuilt.
