### ISSUE TITLE
Starting a test on a subdomain?

### ISSUE THREAD

**Issue by mikewest** [web-platform-tests/wpt#20932]
Every sane person is off doing something fun for the holidays, but, for the crazies: WPT loads tests on `web-platform.test` by default. I have a few cookie tests for the `Domain` attribute that would benefit from starting on a subdomain instead. I can manage that by popping up a new window and running all the tests from there, `postMessage()`ing results back to the main window, but it adds a good deal of complexity.

Would folks accept some additional naming convention (similar to the `.https` suffix) that would start tests out at a specific subdomain instead? Like, `amazing-cookie-test.www.html`? (Of course, `amazing-cookie-test.www.sub.https.tentative.any.js` might be a bit much...)

**Comment by foolip** [comment]
Since it's not obvious from the backreference alone, https://github.com/web-platform-tests/rfcs/pull/39 is an RFC to address this.

**Comment by miketaylr** [comment]
I'm going to attempt to implement this (wish me luck...).

```
[10:56] <miketaylr> if i wanted to tackle https://github.com/web-platform-tests/rfcs/pull/39, does anyone have any pointers of where i should start looking? i tried spelunking blindly but quickly realized i know nothing about wpt internals
[11:10] <jgraham> miketaylr: well tools/manifest/item.py and sourcefile.py and set a flag and tools/wptrunner/wptrunner/wpttest.py wants to read the flag and then (iirc) tools/wptrunner/wptrunner/executors/base.py has the code to set the actual test url which should then depend on the flag
[11:10] <jgraham> But that's all from memory so I might have got things wrong
```

**Comment by foolip** [comment]
Good luck!

**Comment by miketaylr** [comment]
Here's a sketch of a plan, based my loose understanding of how this all works:

* [ ] 1. define a `subdomain` getter in the `URLManifestItem` in [item.py](https://github.com/web-platform-tests/wpt/blob/master/tools/manifest/item.py#L106)
(Note: `SourceFile` will then have the subdomain stuff in the `meta_flags` property in [sourcefile.py](https://github.com/web-platform-tests/wpt/blob/master/tools/manifest/sourcefile.py#L187), but I'm not sure we need to do anything with that. But I could be wrong.)
* [ ] 2. add `subdomain` to the `environment` dict in [wpttest.py](https://github.com/web-platform-tests/wpt/blob/master/tools/wptrunner/wptrunner/wpttest.py#L168), if the property exists (I think I can pull this out of one of the metadata args... maybe)
* [ ] modify `server_url` in [base.py](https://github.com/web-platform-tests/wpt/blob/master/tools/wptrunner/wptrunner/executors/base.py#L310-L314) to read from the `environment.subdomain` property (if it exists), or take it as an optional argument
* [ ] update `last_environment`, and any `on_environment_change` stuff so we can react properly to changes
* [ ] update all the `load_runner` callers in the executors to pass in that property as an arg (if that's the approach)
* [ ] update any other callers that are calling `server_url`, for similar reasons
* [ ] write some tests I guess
* [ ] see if I can make a fancier subdomain parsing work, so rather than just `www` you could have `www.www`, or any other valid subdomain in the `server_config` 

Depending on complexity, skipping the last step is probably OK.

@jgraham does this sound approximately reasonable?

**Comment by jgraham** [comment]
I don't think it actually needs to be part of the environment these days. It used to be that we loaded some code in the initial window and postMessaged from the test window to the harness window. But these days the harness window is just a placeholder so you can just make it part of the test url and not part of the environment.

**Comment by jgraham** [comment]
Apart from that (which I hope results in a simplification) I think that sounds reasonable.

**Comment by miketaylr** [comment]
Great, thanks -- that does simplify things.

**Comment by miketaylr** [comment]
Note to self, figuring out how to run relevant tests was tricky. This does the trick (at least for test_item.py):

`tox -epy27 -- manifest/tests/test_item.py `

**Comment by miketaylr** [comment]
OK, this is a thing now.
