### ISSUE TITLE
Request reviews of baseline tests for `vertical-lr`

### ISSUE THREAD

**Issue by kojiishi** [web-platform-tests/wpt#21124]
As far as I reviewed, the reference files for these tests need to fix:
```
external/wpt/css/css-writing-modes/inline-block-alignment-003.xht
external/wpt/css/css-writing-modes/inline-block-alignment-005.xht
external/wpt/css/css-writing-modes/inline-block-alignment-007.xht
external/wpt/css/css-writing-modes/inline-table-alignment-003.xht
external/wpt/css/css-writing-modes/inline-table-alignment-005.xht
```

A bit of background:
* When I implemented LayoutNG, these look incorrect and that I deferred fixing them, wanting the second opinions.
* Reviewed with @fantasai in September, IIRC we agreed that the test needs fix, but don't remember we reviewed them all or only some of them.
* We're currently trying to change our baseline implementation for some reasons, and are wondering whether to fix tests or to fix our code.

@fantasai Do you remember, or could you review again?

I don't know Hajime and Gerard's github account, I'll send e-mail to them.

cc @bfgeek

**Comment by kojiishi** [comment]
Reviewed again but now tests look correct. Sorry if this was a false alarm in advance.

**Comment by hshiozawa** [comment]
Hi @kojiishi 

Now I have reviewed these tests. But it will take a time to remember my previous work...
Please give me some time.

**Comment by TalbotG** [comment]
Hello Koji and Hajime :) 
It has been a long time since we talk. I hope you are both fine and doing well.

https://wpt.live/css/css-writing-modes/inline-block-alignment-003.xht
https://wpt.live/css/css-writing-modes/inline-block-alignment-003-ref.xht

https://wpt.live/css/css-writing-modes/inline-block-alignment-005.xht
https://wpt.live/css/css-writing-modes/inline-block-alignment-003-ref.xht

https://wpt.live/css/css-writing-modes/inline-block-alignment-007.xht
http://wpt.live/css/css-writing-modes/inline-block-alignment-007-ref.xht
When reviewing the original test back in 2015: 
http://hg.csswg.org/test/file/889e2828b06a/css-writing-modes-3/inline-block-alignment-007.xht
there was no `.ignore { color: silver; }` rule
but I have no objection about the `.ignore` rule and gray box.

https://wpt.live/css/css-writing-modes/inline-table-alignment-003.xht
http://wpt.live/css/css-writing-modes/inline-table-alignment-003-ref.xht

https://wpt.live/css/css-writing-modes/inline-table-alignment-005.xht
http://wpt.live/css/css-writing-modes/inline-table-alignment-003-ref.xht

I see nothing wrong with those 5 tests and 3 reference files.

**Comment by hshiozawa** [comment]
Hello @kojiishi 
```
external/wpt/css/css-writing-modes/inline-block-alignment-003.xht
external/wpt/css/css-writing-modes/inline-block-alignment-005.xht
external/wpt/css/css-writing-modes/inline-block-alignment-007.xht
external/wpt/css/css-writing-modes/inline-table-alignment-003.xht
external/wpt/css/css-writing-modes/inline-table-alignment-005.xht
```
I think that these tests are correct.



These tests are for 'vertical-lr'.
So a rendering of these tests should be equal to flipped of tests for 'vertical-rl'.


> Reviewed again but now tests look correct.

Do you think that these tests are correct now?

**Comment by kojiishi** [comment]
Thank you for taking a look, Hajime and Gerard. I think this was a false alarm, sorry for the noise.

I think my memory is coming back -- @fantasai and I reviewed them because there were no impls that pass, and concluded tests are correct. That might be why we didn't take any actions after the review.

**Comment by TalbotG** [comment]
> there were no impls that pass

Issue 664386: Baselines of inline-block and inline-table do not respect the last line box or the first row if 'writing-mode' is 'vertical-lr'.
https://bugs.chromium.org/p/chromium/issues/detail?id=664386

Bug 1179952: Baseline alignment of inline-block and inline-table when dominant baseline is central
https://bugzilla.mozilla.org/show_bug.cgi?id=1179952
