### ISSUE TITLE
Many Fetch tests do not run in service workers

### ISSUE THREAD

**Issue by annevk** [web-platform-tests/wpt#21163]
Mainly due to defaulting of `.any.js` and not inserting the necessary boilerplate.

**Comment by muodov** [comment]
This looks like a good one to get familiar with how tests files are processed and executed.
I'd like to work on this. @annevk any pointers or hints where to start would be appreciated :)

**Comment by annevk** [comment]
@muodov reading https://web-platform-tests.org/writing-tests/testharness.html#tests-for-other-or-multiple-globals-any-js would go a long way. Adding `// META: global=window,worker` to existing `.any.js` tests and converting `.html` tests (if any) to `.any.js` tests would be most of the work change-wise, I think. And then verifying that the tests still function in these additional environments and there are no new failures. (And if there are, that's exciting, you'll have found bugs.)

**Comment by muodov** [comment]
One complication of this is that service workers implies https, and this breaks some tests with cross-scheme errors ("Mixed Content" and such).
I am going to try and add serviceworker global wherever I can, and then go and fix the new failures caused by Mixed Content one by one. I guess it will be similar to [this pr](https://github.com/web-platform-tests/wpt/pull/14907)

**Comment by annevk** [comment]
Ah yeah, that's right. Sorry for not giving a fair warning about that. I think it's also fine to leave any such tests alone for the moment.
