### ISSUE TITLE
Clarify the meaning of PRECONDITION_FAILED

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt#21971]
There has been some confusion around the use of `assert_precondition` and its failure status `PRECONDITION_FAILED`:

https://github.com/web-platform-tests/wpt/pull/21936#issuecomment-590989098:
@Hexcles :
> @jgraham now I'm not sure if I understand the definition of assert_precondition (or rather, PRECONDITION_FAILED) correctly. I agree that it's better to have some sort of early failure in these tests to avoid wasteful timeout, but I wonder if PRECONDITION_FAILED is the right status in this case, as I thought PRECONDITION_FAILED has some kind of "optional" semantic. It seems to me that this example implies that almost all APIs could use PRECONDITION_FAILED to say that "only run these tests if the API is present", but IMHO a lot of these cases should really be FAILED instead of PRECONDITION_FAILED if said API is missing (I'm not debating about a particular API, but speaking more generally). It could well be the case that this is the intended use of PRECONDITION_FAILED and my understanding is wrong, in which case, @stephenmcgruer , we should treat PRECONDITION_FAILED as FAILED in our metrics.

@jgraham :
> I think your understanding matches the original RFC, but in that case I should really have pushed back on the name, because despite reviewing the RFC at the time I had internalised the idea that this is for cases where the test has a precondition that has to be met for the rest of the test to make sense, not just cases where an optional feature needs to be present.
>
> Anyway I don't mind changing these tests to use assert_true or whatever, although I'm slightly worried that doing an assert in a setup function, which is required for these tests because they start using API features in setup. Arguably the tests shouldn't do that, but I really don't want to rewrite them.

IRC chat:
https://w3.logbot.info/testing/20200225#c543919-c543927
https://w3.logbot.info/testing/20200225#c543975-c544013

My two ideas:
1. `PRECONDITION_FAILED` *only* means that the test fails early due to unmet preconditions (and consequently treat it the same as FAIL when aggregating the data), but we still need to differentiate "browser X claims to support optional feature Y but has the wrong behaviour" vs "browser X does not support optional feature Y"
2. `PRECONDITION_FAILED` implies "optional" (i.e. intended for the use case I just described), and then add a new testharness.js API to FAIL immediately (essentially a wrapper of `assert_true(false)`). And @jgraham would like to rename "precondition" in this approach.

**Comment by stephenmcgruer** [comment]
I think it may help to clarify the cases we are trying to support here:

**Case One**
A test, foo.html is attempting to test some feature Foo, but in order to do that it must rely on some other feature Bar. There are other tests that test feature Bar.

I would say our goal here is for it to be clear to an implementer that there is no point at looking at the failures from foo.html until they have implemented support for Bar. This is still a failing case to me (well, I guess more concretely *we can't tell*), it's just one where from the implementer's point of view they likely want to ignore foo.html until they support bar.html.

**Case Two**
A test, baz.html is attempting to test some feature Baz. However Baz has some optional behaviors (`MAY`), which a given user-agent may or may not support.

I would say our goal here is for baz.html to be able to ignore the subtests for the optional behaviors, if (and only if) they are not supported. If the optional behaviors are supported, the associated subtests should be treated like real tests.

----------------------------

Does anyone think there are cases other than the above, or extra nuances I should capture here?

**Comment by stephenmcgruer** [comment]
cc-ing a few folks: @jgraham @foolip

**Comment by jgraham** [comment]
Right, I think:
* For features that aren't explicitly optional but aren't implemented in a specific browser, the `precondition_failed` status isn't very useful; it's not known until after the test is run, so it doesn't work for optimising out tests that can never pass, and doesn't provide much additional value to people looking at the results compared to the test failing with a useful message. In practice Gecko are likely to add additional (local) metadata about which features we don't plan to implement so we can skip those tests entirely.

* For things that are explicitly optional e.g. supporting specific media formats; making a distinction there between "this fails because the browser has a bug" and "this fails because the browser has a design decision not to support a feature" seems at least somewhat useful. If Google are trying to collect metrics around pass rates — always a tricky thing to do given the relation between tests and actual interop issues is non-linear — I can see why this is considered a useful distinction to make.

* The name does a terrible job of communicating the optional use case (I should have realised this during the RFC discussions but apparently didn't).

So I think the conclusion I have is that I personally don't have a use case that benefits from `precondition_failed` as a status. But it sounds like @Hexcles does and it only makes sense if it's for optional features. So I propose

* We rename `assert_precondition` to `assert_implements_optional`

* We add an assert like `assert_implements` which just causes the test to fail if the passed value is falsy. This could be used like `assert_implements(CSS.AnimationWorklet)`, although getting a good error message probably requires it to look like `assert_implements(CSS.AnimationWorklet, "CSS.AnimationWorklet")`, which is unfortunate (if we really restricted it to object properties we could make it `assert_implements("CSS.AnimationWorklet")` and have the implementation parse the string into properties and evaluate those on `self`. idk if that's a good enough API).

**Comment by stephenmcgruer** [comment]
> For features that aren't explicitly optional but aren't implemented in a specific browser, ... doesn't provide much additional value to people looking at the results compared to the test failing with a useful message.

I guess in my mind it allows you filter wpt.fyi to ignore such results (or otherwise quickly determine you can ignore them). I did view this as something that would be useful for an implementer who has such an unsupported feature, but I could be incorrect. Maybe this is solved via adding an 'ignore' ability to wpt.fyi anyway.

> For things that are explicitly optional ... making a distinction there between "this fails because the browser has a bug" and "this fails because the browser has a design decision not to support a feature" seems at least somewhat useful.

I'm not sure I follow. If it's explicitly optional and we have `assert_implements_optional` (which I like), don't we already have that data? I presume `assert_implements_optional` would produce a different (sub)test result (`NOT_IMPLEMENTED`?). Again the reason for that status to me is people trying to understand the results (e.g. on wpt.fyi); I would want it to be clear to them that they don't have to worry about that test (similar to how we can markup an `.optional` test to indicate that they don't have to worry about it).

> We rename assert_precondition to assert_implements_optional

I agree. I think this API should (like `assert_precondition`) have its own result status.

> We add an assert like assert_implements

I don't currently see the usecase (vs a normal assert). @Hexcles may disagree with me.

**Comment by jgraham** [comment]
The problem with solutions that add more statuses is that adding new statuses is hard. They need support in mozlog, and all the various formatters and other consumers of logs have to be audited to ensure that they are able to cope with the new status. And there's always some risk of out-of-tree consumers breaking, so implicit in my plan was the assumption that it's not worth removing `precondition_failed` as a status (although that's probably possible) and it's not worth adding new statuses, especially given that the benefits of more precision are typically negated by the fact that people don't really use them consistently.

> I guess in my mind it allows you filter wpt.fyi to ignore such results (or otherwise quickly determine you can ignore them).

As I said gecko is planning to add "this feature isn't going to be implemented" as explicit metadata (for things that we have a "harmful" standards position on), so having some way to attach metadata to directories of tests indicating that some entire spec isn't implemented in a browser (with some distinction between "not now", "not soon", and "never") would be another approach.

> I'm not sure I follow. If it's explicitly optional and we have assert_implements_optional (which I like), don't we already have that data? I presume assert_implements_optional would produce a different (sub)test result (NOT_IMPLEMENTED?).

I was implicitly assuming that adding new statuses isn't worth the hassle.

**Comment by stephenmcgruer** [comment]
I see. I was not aware of that; given that we added `PRECONDITION_FAILED` (or maybe it was preexisting) I had assumed it was normal.

I would actually be ok to reuse `PRECONDITION_FAILED` for `assert_implements_optional` if that doesn't make everyone too sad? (It makes me... a little sad). I feel that adding `assert_implements_optional` without utilizing a different status is again somewhat pointless (one may as well write `assert_true(CSS.MyOptionalFeature)`).

**Comment by jgraham** [comment]
We did add `precondition_failed`, but it did involve a relatively large amount of work, and given that we're now having this conversation, I think it was possibly a mistake.

> I feel that adding `assert_implements_optional` without utilizing a different status is again somewhat pointless (one may as well write `assert_true(CSS.MyOptionalFeature))`.

I think the "point" of `assert_implements_optional` would be to get the "this is a specwise-legit decision not to implement a thing" status, and the point of `assert_implements` would be to get the "this is a nice error message for an early failure" feature.

There is another argument that specwise legitimate differences in implementations are much of the time not legitimate from a web compat point of view (i.e. the spec says A or B, but actually only B works with real content). I suppose the idea is that standards authors are now sufficiently aware of this that they don't add optional things that aren't truly optional.

**Comment by stephenmcgruer** [comment]
Ok, I think we are all in agreement, so the plan of action is pretty much what James posted in https://github.com/web-platform-tests/wpt/issues/21971#issuecomment-591384898:

> We rename assert_precondition to assert_implements_optional
>
> We add an assert like assert_implements which just causes the test to fail if the passed value is falsy.

With the understanding that for `assert_implements_optional` we reuse the `PRECONDITION_FAILED` status, since adding/changing status values is difficult.

Do we think this needs an RFC? We're 'only' (air quotes) renaming a testharness.js API, which was added fairly recently and isn't in major use, and adding a minor one (`assert_implements`).

**Comment by stephenmcgruer** [comment]
https://github.com/web-platform-tests/rfcs/pull/48 has now landed, which splits `assert_precondition` into `assert_implements` and `assert_implements_optional`. I'll start working on a set of PRs to update WPT code; @Hexcles we may also wish to do some work on the wpt.fyi side at some point to change how we represent `PRECONDITION_FAILED` in the UI.

**Comment by stephenmcgruer** [comment]
The last PR to remove assert_precondition just landed (https://github.com/web-platform-tests/wpt/pull/23324).

I'm closing this as fixed; @Hexcles we may want a wpt.fyi issue to track changing the UI if that's something you feel is warranted.

**Comment by Hexcles** [comment]
I took a quick look around and didn't find any special logic for `PRECONDITIONED_FAIL` on the wpt.fyi UI, but we do have a somewhat related issue for checks: https://github.com/web-platform-tests/wpt.fyi/issues/1620.
