### ISSUE TITLE
[webxr] Most of the tests require Chromium-specific code

### ISSUE THREAD

**Issue by svillar** [web-platform-tests/wpt#22350]
I'm in the process of implementing WebXR API in WebKit. After importing the available WebXR WPT I found out that I cannot use almost none of them because they depend on some testing infrastructure which is chromium specific.

I don't really see the point of having this kind of tests in the wpt repository, in this case I think the right thing to do is to keep them downstream. I perfectly understand that Chromium is leading this effort but it does not help others to join.

Can we work on a solution that would allow other vendors to run the tests?

**Comment by svillar** [comment]
James told me about issue #16294. I'll close this then, hoping that https://github.com/immersive-web/webxr-test-api would be the solution for the problem

**Comment by Manishearth** [comment]
No, this is definitely the place to discuss this. The tests are not chromium specific (the linked issue is outdated), you should be able to implement [the testing API](https://immersive-web.github.io/webxr-test-api/) and it will work.

Servo is doing this and running the tests just fine. There is chromium-specific code under WPT because Chromium's implementation of XRTest is in Javascript and weird.
