### ISSUE TITLE
Wrong font path, but file is automatically generated so can't patch

### ISSUE THREAD

**Issue by faceless2** [web-platform-tests/wpt#22820]
https://github.com/web-platform-tests/wpt/blob/master/css/WOFF2/support/available-002a.xht

This file references "support/available-002.woff2", but it's in the support subdirectory already. The font should be "available-002.woff2", as it already is in the second part of this test, https://github.com/web-platform-tests/wpt/blob/master/css/WOFF2/support/available-002b.xht

As the file has "THIS FILE WAS AUTOMATICALLY GENERATED, DO NOT EDIT" I don't think I can patch it and issue a pull request. So I'm not quite sure what do do with this one other than file it here.

**Comment by stephenmcgruer** [comment]
Thanks for the report! This is strange indeed, I don't think there should be test files at all in the `support/` directory. In fact, wpt.fyi doesn't even seem to pick it up - https://wpt.fyi/results/css/WOFF2?label=experimental&label=master&aligned (no support/ directory) - and `wpt run` doesn't find it either:

```
$ ./wpt run --channel=experimental chrome css/WOFF2/support/available-002a.xht
CRITICAL Unable to find any tests at the path(s):
CRITICAL   css/WOFF2/support/available-002a.xht
CRITICAL Please check spelling and make sure there are tests in the specified path(s).
```

cc @svgeesus as the only person listed in the WOFF2 META.yml file.

**Comment by stephenmcgruer** [comment]
Looks like its included from a test at `css/WOFF2/available-002.xht` (in an iframe), so maybe it is meant to be a support file. The lack of any reference file/etc for `css/WOFF2/available-002.xht` however means it will be basically ignored by WPT infrastructure as well.

**Comment by faceless2** [comment]
Definitely a support file for available-002, sorry I should have pointed that out. I can't speak for it's location being correct or not, but I understand what the "available-002" test is trying to ascertain and, despite the lack of reftest it's still a useful test (and the last WOFF2 test we're failing, which is why the report!)

**Comment by svgeesus** [comment]
> This is strange indeed, I don't think there should be test files at all in the support/ directory.

Correct, but this is not a stand-alone test file which is why it s in the support directory. It is instead part of [this test](https://github.com/web-platform-tests/wpt/blob/master/css/WOFF2/available-002.xht). This is one of several tests which use iframes linking to support files.

> The lack of any reference file/etc for css/WOFF2/available-002.xht however means it will be basically ignored by WPT infrastructure 

Yes, this is a visual test; the pass criteria require a human to look at the result. This is indicated by the

```
<meta name="flags" content="interact" />
```

> As the file has "THIS FILE WAS AUTOMATICALLY GENERATED, DO NOT EDIT" I don't think I can patch it and issue a pull request

The source of these tests is the test generator [here](https://github.com/w3c/woff2-tests). It requires Python, font-tools, and the Brotli library plus Python bindings. So patches would be to the Python programs that generate the tests. It would also be helpful, if anyone patches the generators, to re-run the generators and check the compiled tests into their repo and also into WPT.

For the benefit of those who can't or don't want to run the generator, there are also [the compiled tests](https://github.com/w3c/woff2-compiled-tests). The user-agent (browser) tests are [described here](http://w3c-test.org/css/WOFF2/testcaseindex.xht) and most are reftests; the two `available-*` however are not reftests. There is additional documentation on what each test is supposed to do [here](https://www.w3.org/Fonts/WG/wiki/Main_Page#WOFF_2.0_Test_Suite). The tests were created by the W3C Fonts Working Group.

**Comment by faceless2** [comment]
That's the pointer I needed, thanks!

I've patched and re-run the generator; it fixed the required file, but also modified all the WOFF2 files too. They're binary so I can't see what's changed - it's probably just the generated timestamp, but as I'm unsure I haven't included the regenerated `*.woff` in https://github.com/web-platform-tests/wpt/pull/23524.

**Comment by svgeesus** [comment]
Thanks for that, merged.
