### ISSUE TITLE
[hit-test][webxr] pointerOrigin is native-relative, even for screen spaces

### ISSUE THREAD

**Issue by Manishearth** [web-platform-tests/wpt#22901]
https://github.com/web-platform-tests/wpt/blob/f2e918abb4b8711afb28c8b98d98be3bffc9fa9a/webxr/hit-test/ar_hittest_subscription_inputSources.https.html#L118-L129

https://github.com/web-platform-tests/wpt/blob/f2e918abb4b8711afb28c8b98d98be3bffc9fa9a/webxr/hit-test/ar_hittest_subscription_inputSources.https.html#L12-L27

This  test is written assuming that the supplied parameters set a pointer origin equal to the viewer origin (`(0,1,0)`). This isn't the case, all `FakeXRRigidTransformInit`s in the spec are [native-relative unless otherwise specified](https://immersive-web.github.io/webxr-test-api/#simulated-devices).

This arises from [this Chrome code](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/web_tests/external/wpt/resources/chromium/webxr-test.js;l=1009-1030;drc=d9d2e9ee9b300cd346298e62b9e28160f2a3bf5e?originalUrl=https:%2F%2Fcs.chromium.org%2F) where different input source types are treated differently wrt the origin. It might be worth making the test API do this, but I prefer having some uniformity there.

cc @bialpio 

cc @alcooper91 for the chrome test api bug

**Comment by alcooper91** [comment]
I think pointer origin is something that we probably want to make an exception to (it looks like we've not really sketched/fully specced out the algorithms for input since Chrome's been the only one implementing it so far). Pointer origin's don't make sense to be a fixed point in the *device's* reference space, they really only make sense in the input source's reference space (since they move with it), and I believe are typically a fixed offset (e.g. the center of the controller may be here, but rays originate from here and at this orientation).

I think this is actually just a spec bug for the test api.

**Comment by Manishearth** [comment]
We've had the input algorithms implemented for a while.

> Pointer origin's don't make sense to be a fixed point in the device's reference space, they really only make sense in the input source's reference space

I don't see how this is different from any other origin.

The pointer origin is being used to _set_ the input source's reference space, it's a bit weird to define that as relative to input source's reference space.

I'd rather not have complexity in the test API, the test API should give us a way to mock specific values in a straightforward way.

**Comment by Manishearth** [comment]
It's also not guaranteed that gaze input will be exactly the same as the viewerspace, gaze might choose a more natural "center of screen" vector that is not the nose vector. The screen input is similarly offset based on where you tap. Making the origin modify these transforms seems like pointless complexity to me.

**Comment by alcooper91** [comment]
We've had the API text there, but haven't had full spec text for the input. I was under the impression that Chrome was the only ones running the input tests at the moment?

I think there's really just a spec bug, because I had always intended pointerOrigin to be "grip_from_pointer." This is the way it's currently implemented in Chrome/all of the tests that use it, or in other words, it *is* that more natural "center of screen" or "where you tap" transform. On physical controllers it represents the transform of where the pointer is relative to the tracked gripOrigin of the controller.  Because it's an intrinsic of the "physical geometery" of the controller, that is why it's required rather than optional. If it were both required and the absolute position of the pointer relative to the device origin, we'd never be able to simulate an untracked controller.

I think the assumption of the test that pointer origin is the viewer origin is fine, because the pointer origin is specified as identity.

**Comment by Manishearth** [comment]
> We've had the API text there, but haven't had full spec text for the input. I was under the impression that Chrome was the only ones running the input tests at the moment?

No, we run them too, and have been for a while.

> I think there's really just a spec bug, because I had always intended pointerOrigin to be "grip_from_pointer." 

This feels weird to me, because now you cannot simulate devices without grip but with targetRay.

> If it were both required and the absolute position of the pointer relative to the device origin, we'd never be able to simulate an untracked controller.

It doesn't need to be required, though. We should just have pointerOrigin and gripOrigin directly reflect into the native target ray and grip origins, and if unset it's untracked.

----

Basically, as a mock API I think it should be as direct to spec concepts as possible; the spec talks about native target ray and grip origins, and we should just plug this into those. I'm not a fan of introducing additional semantics to the test API.

(and, remember, it is not guaranteed that screen or gaze space targetRaySpaces will exactly match their origins)

**Comment by alcooper91** [comment]
Spoke with Manish offline. We're going to define that the pointerOrigin is relative to another object (the specific object of which depends on the target ray mode that is set). Tracking this via a spec bug in the test api repo, so closing.
