### ISSUE TITLE
webdriver/tests/support should trigger infrastructure tests

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt#22936]
https://github.com/web-platform-tests/wpt/pull/22927 did not trigger infra tests https://community-tc.services.mozilla.com/tasks/groups/KLQpcAtAQyyheGz5K9Bo-w so the regression (caused by a non-ASCII character in the comment) was not caught: https://github.com/web-platform-tests/wpt/pull/22935

**Comment by stephenmcgruer** [comment]
Oh wow, I had totally misunderstood what happened in that PR. It *did* run the `webdriver/` tests, we just didn't notice because people ignore the wpt.fyi results because they're green even when they regress...

https://community-tc.services.mozilla.com/tasks/MkeeXKwgSdmZvwuBgP6UkQ/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FMkeeXKwgSdmZvwuBgP6UkQ%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log has thousands of:

` 0:43.38 TEST_END: ERROR, expected OK - Non-ASCII character '\xe2' in file /home/test/web-platform-tests/webdriver/tests/support/__init__.py on line 6, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details (__init__.py, line 6)`

@Hexcles what 'infrastructure' tests are you referring to here that would have caught this?

**Comment by Hexcles** [comment]
This one:
https://github.com/web-platform-tests/wpt/blob/751ceadd296ff816cbcff15c5f508840bce08a41/tools/ci/tc/tasks/test.yml#L434

Whenever we change `tools/`, among other things, we run that directory specifically (not as part of `affected_test`) and check the results against the [in-tree metadata](https://github.com/web-platform-tests/wpt/tree/master/infrastructure/metadata/infrastructure).

**Comment by stephenmcgruer** [comment]
Right, that runs the `infrastructure/` tests - how do they lead to us spotting encoding errors in a random file in `webdriver/`?

**Comment by Hexcles** [comment]
Ahh sorry I forgot to include a link to the original failure that led me to discover this bug, and I can no longer find it.

Basically, your PR changed `tools/`, which triggered `infrastructure/`, and `infrastructure/webdriver/tests/test_load_file.py` failed because it failed to import `webdriver/tests/support` via the test fixture. The culprit PR landed because even though it touched `webdriver/tests/support` but it did not trigger `infrastructure/`.
