### ISSUE TITLE
Run Sphinx doc generation in Python 3

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt#23081]
We use Sphinx to parse arguments from a few `wpt` commands and generate docs automatically. It's currently running in Python 2. This is a reminder that once we switch our primary supported version to Python 3, we should upgrade Sphinx and run it with Python 3.

**Comment by Hexcles** [comment]
Code is in https://github.com/web-platform-tests/wpt/tree/master/docs

**Comment by stephenmcgruer** [comment]
@ziransun - can you start looking at how compatible our document generation is with Py3? (Low priority, but since the RFC is ongoing). 

I believe `wpt build-docs` will run it, but you'll need to make sure that it's actually using py3 all the way down. Very high level list of things I think will likely need to happen:

1. Make sure that Python3 is being used all the way down when running `wpt build-docs`.
1. Update to a new Sphinx version (in `docs/requirements.txt`) that supports py3
1. Figure out any problems, iterate on fixing them :)
1. Eventually update the docker image used for this (see `tools/docker/documentation/Dockerfile`) to be py3 based, though this shouldn't be required for local testing.

@Hexcles may have more thoughts.

**Comment by ziransun** [comment]
Thanks @stephenmcgruer! I will take a look.
