### ISSUE TITLE
No WebKitGTK runs since Apr 23

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#23313]
https://wpt.fyi/results/?run_id=493030003 is the most recent WebKitGTK run on wpt.fyi currently, see them all at https://wpt.fyi/runs?max-count=100&product=webkitgtk.

@clopez can you take a look?

**Comment by clopez** [comment]
I see the runs still happening without issue, the problem is that the results are not longer being updated to wpt.fyi

Example:

* On the [last run with results (0084aa71d4)](https://github.com/web-platform-tests/wpt/commit/0084aa71d4) you can see how there is an action triggered for  [wpt.fyi - webkitgtk[experimental]](https://github.com/web-platform-tests/wpt/runs/610686195)

* However in a [recent run for yesterday (f657d26323) ](https://github.com/web-platform-tests/wpt/commit/f657d26323) you can't see anymore the action for  `wpt.fyi - webkitgtk[experimental]
`

And if you inspect the taskcluster run for both commits, on both runs webkitgtk completed the runs ok (the global TC state failed due to servo, but webkitgtk worked without issue)

Investigating this further I suspect this was caused by [wpt.fyi commit b8fac0b](https://github.com/web-platform-tests/wpt.fyi/commit/b8fac0b)

I can see how the task-cluster task name for webkitgtk was passing the regex before, but not anymore.

```
$ echo wpt-webkitgtk_minibrowser-nightly-testharness-2 | grep -P '^wpt-(\w+-\w+)-(testharness|reftest|wdspec|crashtest|results|results-without-changes)(?:-\d+)?$'
wpt-webkitgtk_minibrowser-nightly-testharness-2

$ echo wpt-webkitgtk_minibrowser-nightly-testharness-2 | grep -P '^wpt-([a-z]+-[a-z]+)-([a-z]+(?:-[a-z]+)*)(?:-\d+)?$'
# no match.
```

I think its related to the underscore `_` used on the browser name, which its `webkitgtk_minibrowser` for the wpt runner and the TC taskcluster task definition.

Changing the regex to something like `^wpt-([a-z_]+-[a-z]+)-([a-z]+(?:-[a-z]+)*)(?:-\d+)?$` should work

// cc @Hexcles

**Comment by clopez** [comment]
Opened PR https://github.com/web-platform-tests/wpt.fyi/pull/1925
