### ISSUE TITLE
[webxr][testharness] xrSession_visibilityState:  EventWatcher constructor called with duplicate events

### ISSUE THREAD

**Issue by iBicha** [web-platform-tests/wpt#23415]
`xrSession_visibilityState` has multiple events of the same name in the `EventWatcher`.

https://github.com/web-platform-tests/wpt/blob/f9709adf63adb8c316209e7826f67f3f9c2bf2f2/webxr/xrSession_visibilityState.https.html#L21

yet the `EventWatcher` does not handle events of the same name correctly.

for recorded events, `EventWatcher`, events must be deduplicated.
Additionally, `xrSession_visibilityState` test must pass `{ record: 'all' }` option to its `eventWatcher.wait_for` call.

**Comment by foolip** [comment]
@iBicha it looks to me like the problem is that "visibilitychange" is listed twice in the `EventWatcher` constructor call. That'll cause two event listeners to be added. The API shape is pretty unintuitive IMHO, but the idea is that in the constructor you list all the (unique) events that might be fired, and in the `wait_for` call you say which (possibly repeated) events that should be fired. Any incorrect order of events or firing of events not listed in the `wait_for` call but in the constructor will fail the test.

**Comment by iBicha** [comment]
Got it, thank you for the explanation. So this is considered a bug in `xrSession_visibilityState`.
Changed the title to reflect that.
