### ISSUE TITLE
test_verify_taskcluster_yml fails on Windows in Python 3

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt#24561]
Note that this only happens on Windows with Python 3.6 or 3.8.

Examples:
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=51123&view=logs&j=f004df5f-f2f4-549d-78c2-3c60702bc2c8&t=586ef36c-9a2d-569c-1ba9-263112987f84&l=63
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=51123&view=logs&j=47b03e2b-d31e-537f-c8cf-66c80d147ca1&t=67b19343-5bc4-57b8-71e9-6c31e5bc256c&l=63

`KeyError: '_strptime'` raised from `datetime.datetime.strptime` when doing `jsone.render`.

**Comment by Hexcles** [comment]
Maybe relevant: https://github.com/pyexcel/pyexcel/issues/180

**Comment by stephenmcgruer** [comment]
I'm not sure I'm reading the logs right, but it looks like this caused a fail in https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=51916&view=logs&j=85f2ffec-1d6e-5253-c3dd-62d5cd43e221&t=a9a637ac-afdf-5c9e-e3a0-6b959a0fc833, which shouldn't happen because its XPASS?

The step failed, and this is the only test failure I see. There is also this, but not clear what it's caused by:

`2020-07-30T10:47:30.2165403Z ERROR: InvocationError for command 'D:\a\1\s\tools\.tox\py38\Scripts\pytest.EXE' --cov=tools --cov-report=term --junitxml=results.xml (exited with code 1)`

**Comment by Hexcles** [comment]
Great! XPASS means "unexpected passing". *Perhaps* one of the underlying dependency has upgraded and the issue now goes away. This is also why I prefer XFAIL over SKIP.

The last error you saw simply meant the `pytest` command failed, because of the unexpected pass.
