### ISSUE TITLE
Continuous Integration checks (wpt-decision-task and Community-TC) do not end or do not execute

### ISSUE THREAD

**Issue by TalbotG** [web-platform-tests/wpt#24620]
**Continuous Integration checks (wpt-decision-task and Community-TC) do not end or do not execute**

Dear fellow advanced GitHub colleagues and @foolip ,

Please visit 
https://github.com/web-platform-tests/wpt/pull/23880

You will see:
"
Some checks haven’t completed yet
1 expected, 1 pending, and 18 successful checks
wpt-decision-task Expected — Waiting for status to be reported
Required
@community-tc-integration
Community-TC (pull_request) Pending — TaskGroup: Pending (for pull_request.synchronize)
"
It has been like that for **over 2 hours** now. Please help me understand what is happening. Or how to fix this.

Thank you

**Comment by stephenmcgruer** [comment]
Hi Talbot,

Your change was unfortunately caught in the migration of our CI system, Taskcluster, to use the GitHub Checks API. As part of the migration I went through every PR that appeared to have recent activity, but your PR was overlooked. Apologies for the inconvenience; I have now admin-merged your PR.

For future reference, you can always '@' mention '@web-platform-tests/admins' in a PR if it seems stuck due to infrastructure issues and you don't know why.

Thanks,
Stephen (he/him)

**Comment by TalbotG** [comment]
> I have now admin-merged your PR.

Bravo! Thank you, Stephen!

> For future reference, you can always '@' mention '@web-platform-tests/admins' in a PR 

I will from now on. Thank you for your quick and helpful assistance here, @stephenmcgruer . This is appreciated :)

**Comment by TalbotG** [comment]
@web-platform-tests/admins
I am reopening because I have been gettting (yesterday and today) the same symptoms again this time in 
https://github.com/web-platform-tests/wpt/pull/21503

**Comment by stephenmcgruer** [comment]
Reading over https://github.com/web-platform-tests/wpt/pull/21503, it looks like the issue was an old PR which had real conflicts with current master, and so the decision was taken to close it and pull the changes into a new PR.

As such, I think this can be closed again.
