### ISSUE TITLE
Remove microdata API

### ISSUE THREAD

**Issue by zcorpan** [web-platform-tests/wpt#2521]
I noticed html/dom/interfaces.html at least has IDL for microdata that has been removed from the spec. Should remove that and add something to some historical.html instead.

**Comment by bzbarsky** [comment]
Note that I'm doing this in https://bugzilla.mozilla.org/show_bug.cgi?id=909633 for a bunch of web platform tests, including html/dom/interfaces.html.

There's a bunch of tests in html/editing/dnd/microdata that I'm _not_ touching because I don't know how to run it and hence check what it's really doing.

**Comment by hober** [comment]
cc @cdumez

**Comment by cdumez** [comment]
This is great news 👍

**Comment by stephenmcgruer** [comment]
I believe this was fixed in https://github.com/web-platform-tests/wpt/pull/3135, feel free to re-open if I'm wrong.
