### ISSUE TITLE
No results for webkitgtk nightly since Oct 10th

### ISSUE THREAD

**Issue by stephenmcgruer** [web-platform-tests/wpt#26097]
[wpt.fyi shows](https://wpt.fyi/runs?label=master&label=experimental&max-count=100&product=chrome&product=edge&product=firefox&product=safari&product=webkitgtk) no results for webkitgtk nightly since October 10th.

Looking at `epochs/daily`, looks like one task failed yesterday at least: https://community-tc.services.mozilla.com/tasks/groups/Ou6NP7O3RNiZH8248bBncg

[Log file](https://community.taskcluster-artifacts.net/efh1XmB6T86_Q3vb3Nvt4g/0/public/logs/live_backing.log)

It appears to have timed out:

```
[taskcluster:error] Task timeout after 7200 seconds. Force killing container.
```

The other reftest shards took 23 mins, 18 mins, 52 mins, and 35 mins. We should also look historically at `wpt-webkitgtk_minibrowser-nightly-reftest-2` to see what its running time has been.

**Comment by stephenmcgruer** [comment]
cc @clopez

**Comment by clopez** [comment]
As far as I see there has been two runs missing, on october 12 and october 13

* List of runs (nightly/experimental channel) which should be daily: https://wpt.fyi/runs?label=master&label=experimental&from=2020-10-07T00%3A00&product=webkitgtk

The run failed for october 13 is the one you point here. However, I have been unable to find the failed run for october 12.
Finding the exact sha1 commit of the epochs/daily branch for that day seems its not trivial, and the interface for showing CI runs on github or taskcluster doesn't make this any easier.

Regarding what happened on that failed runs it seems the task was killed after reaching its 7200 maximum run limit, but the tests were excuting fine by that time. The last time-stamp logged was at 118:44.09. This may be a similar problem to #19724 and we may need to either raise the timeout of the steps or increment the number of steps. As we continue to add more tests is somehow expected that running all the tests will take more time and we keep finding this issues. Let's keep this open to see if the problem appears again.

**Comment by stephenmcgruer** [comment]
We have successful runs on October 14th and October 15th. Given that I'm going to drop to `roadmap` priority, but would also be ok if this was just closed.

The big shift in time is suspicious though - notice that a passing run takes only 1hr15, whilst a timeout has to take 2 hours I think.

**Comment by clopez** [comment]
> The big shift in time is suspicious though - notice that a passing run takes only 1hr15, whilst a timeout has to take 2 hours I think.

Good point. 
I checked the timestamps on that run and I couldn't spot any specific test that took too much time to complete. No one of the tests ran there took more than 20 seconds and only 4 took more than 10 seconds. It just looks like everything took a bit more in general.

Maybe there was some issue on the CI that caused that job to run slower, don't know

The last daily run today (oct 23) for [wpt-webkitgtk_minibrowser-nightly-reftest-2](https://community-tc.services.mozilla.com/tasks/BoLSdOy2SCG7QPlpekAemw ) is taking 1hr15 as expected. 

Since more than a week (october 14th) runs are happening on a daily basis without issues. So I'm closing this. 

Please re-open or open a new issue if you detect some run failing.
