### ISSUE TITLE
[css-flexbox] table-as-item-specified-width.html fails in the same way in all browsers

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#26257]
Behold: https://wpt.fyi/results/css/css-flexbox/table-as-item-specified-width.html?run_id=711240001&run_id=697770002&run_id=737900001&run_id=715540002&run_id=705490001&run_id=720530001

The actual screenshot look something like this for all browsers, this one being from Firefox:
![image](https://user-images.githubusercontent.com/498917/97008682-6ebffc80-1543-11eb-80cd-394a0fa5d438.png)

The test was added by @davidsgrogan in https://github.com/web-platform-tests/wpt/pull/25529 and there's a comment that says "This test passed until Chrome 84 but has been broken since. Firefox also fails it." In fact, all browsers fail it.

Does this test match the spec? If so, should the spec be changed?

(Sorry, I'm only able to ask the basic questions, don't know Flexbox well enough to investigate myself.)

**Comment by davidsgrogan** [comment]
The test matches the spec (as far as I understand), but tests an apparently uncommon situation, as evidenced by the fact that no one complained when Chrome 84 broke the rendering (literally 0 bugs reported, I didn't know 84 broke it until 85 broke a similar case and I was poking around)

@atotic checked in some TablesNG code yesterday that will fix this in Blink.

Firefox's bug about this is https://bugzilla.mozilla.org/show_bug.cgi?id=1454330 Similar to Chrome's, their bug is not that popular.

I guess I'm saying that I think we should keep the test because (1) it asserts spec-compliant behavior, (2) the spec makes sense, and (3) there probably won't be too many compat problems from fixing the bug in implementations, as evidenced by the non-popularity of the bugs on our respective issue trackers.

Thoughts?

**Comment by davidsgrogan** [comment]
Oh, just for reference, Chrome's bug for this case is https://crbug.com/1128262

**Comment by foolip** [comment]
Thanks @davidsgrogan, if the spec makes sense and there's low risk in any behavior, then keeping this as-is seems OK. I'm always suspicious of tests that fail everywhere in the same way and changing the spec is usually the best fix, but not in every single case :)

I've gone ahead and linked https://bugs.chromium.org/p/chromium/issues/detail?id=1128262 and https://bugzilla.mozilla.org/show_bug.cgi?id=1454330 on wpt.fyi and will comment in the bugs linking to your comment for people trying to figure out what's going on.

**Comment by foolip** [comment]
I think https://bugs.webkit.org/show_bug.cgi?id=210102 is the most relevant WebKit bug for this, linked on wpt.fyi now too.

**Comment by atotic** [comment]
As a general rule, tables inside flex/grid are trouble, and cross-browser compatibility is poor right now. Clear standards are also missing. This is an area that could use an explicit standard.

The root of the problem is computing table's intrinsic maximum size. It's value differs depending on table's parent: block layout parent produces one value, grid/flexbox/table cell another.

**Comment by foolip** [comment]
@atotic I see, I suppose the test coverage for it is also not great then?

And which spec should define this?

**Comment by atotic** [comment]
I think it belongs in the table spec, where GRIDMIN is defined:
https://www.w3.org/TR/css-tables-3/#computing-the-table-width
Current definition of GRIDMIN is incomplete. It does not specify how table's intrinsic width is related to cells with percentage width.
The percentage width handling differs depending on whether container chain contains grid/flexbox/table cell.

**Comment by davidsgrogan** [comment]
I filed a spec issue about this 2 years ago https://github.com/w3c/csswg-drafts/issues/3336
