### ISSUE TITLE
Add test API for protocol handlers

### ISSUE THREAD

**Issue by fred-wang** [web-platform-tests/wpt#26819]
cc @annevk 

In https://github.com/web-platform-tests/wpt/pull/23504, several manual tests were added

https://github.com/web-platform-tests/wpt/tree/master/html/webappapis/system-state-and-capabilities/the-navigator-object/

because we lacked a proper API to emulate user's approval of a protocol handler registration.

When fixing the bug in Chromium https://chromium-review.googlesource.com/c/chromium/src/+/2379672 , I had to rely on C++ browser tests that auto-approve registration. It would be good if such a logic were in WPT instead.

**Comment by annevk** [comment]
Makes sense, do we just need a switch for auto-granting the permission? I'd be happy to do the WebDriver specification part of that in HTML.

**Comment by fred-wang** [comment]
Thanks Anne.

I opened this for the record and I have not really investigated into this to be honest, but checking the chromium tests, I see 3 things:
- something to claim registerProtocolHandler calls are initiated by a user interaction (as otherwise it will get rejected).
- something to force auto-granting permission to bypass the UI.
- some callback / promise to ensure the protocol has been registered and we can just go ahead testing it.

(I also wonder whether we want something more generic than just protocol handler. A quick search https://source.chromium.org/search?q=set_auto_response_for_test shows matches for WebVR or WebRTC for example)

**Comment by annevk** [comment]
I think there is a generic permission thing we could use. User interaction can already be done through `testdriver.js` (i.e., simulating a mouse click or some such). The success callback seems trickier though. Maybe @jgraham and @stephenmcgruer have ideas.

**Comment by fred-wang** [comment]
OK, thanks.

For the record, why the success is not web-exposed is explained in https://github.com/whatwg/html/issues/5845

**Comment by jgraham** [comment]
Yeah, so the way I'd imagine this working is that you first grant the permission in general, then synthesise a user guesture that causes an event that runs the registerProtocolHandler code. If there are steps after that which are asynchronous or state that we want to expose to tests but not to the web things do get more tricky. We could image a test-only DOM API allowing us to inspect the registered protocol handlers, and poll that API to check for success. Maybe we could have a test-only event, but that feels pretty exotic. I"m not sure if there's a way we could express this as a HTTP WebDriver endpoint (maybe this is a case where WebDriver-BiDi will eventually help since we could expose the registerProtocolHandler result as an event in that API without exposing it to the DOM).

**Comment by annevk** [comment]
Maybe a "reply once X is registered" endpoint, essentially a hanging GET. Seems a bit nicer than having to poll, but I suppose either works. It might be worth waiting a bit as well though for the better infrastructure to arrive.

**Comment by javifernandez** [comment]
@annevk who could be a good candidate to look at the  [#33866 PR](https://github.com/web-platform-tests/wpt/pull/33866) ? It's an automatic PR crated by the CL I m working on to add support in Chrome for the new PermissionDescriptor, so that we can effectively grant or deny registerProtocolHandler request without user interaction. 

I hope this is also supported by Firefox, or at least assume it has interest to do so otherwise.

**Comment by annevk** [comment]
That doesn't sound great? Where is the proposal for that permission as well as its standardization venue?

**Comment by javifernandez** [comment]
> That doesn't sound great? Where is the proposal for that permission as well as its standardization venue?

This is still an idea, nothing has been landed yet. I'd appreciate any suggestion on how to build a proposal for standardization. I'd simply tried to implement what it's been suggested in this [comment](https://github.com/web-platform-tests/wpt/issues/26819#issuecomment-742445929) regarding the "something to force auto-granting permission to bypass the UI.
" issue.

> I think there is a generic permission thing we could use

The idea is to use the [SetPermission](https://w3c.github.io/permissions/#set-permission-command) extension commands for the [[WebDriver](https://w3c.github.io/permissions/#bib-webdriver)] specification for Automated testing, defined in the [Permission](https://w3c.github.io/permissions/) specification.

In order to to use the command we need to use a PermissionDescriptor, which can be used to retrieve a permission status usign the [query method](https://w3c.github.io/permissions/#query-method) of the Permission Interface.

I've got some inspiration on the tests we already have for the clipboard-apis, like the [readText-granted.https.html ](https://github.com/web-platform-tests/wpt/blob/master/clipboard-apis/permissions/readText-granted.https.html) test, where we are using the set_permission WebDriver command to grant permission associated to the "clipboard-read" descriptor. 

I guess we would need to add a Permission API integration section for the Custom Handlers spec, like the one defined in the [Clipboad API ](https://w3c.github.io/clipboard-apis/#clipboard-permissions) spec.  

I'm not sure where is the right standarizaiton venue for the PermissionDescriptor name. I've found that Firefox defines the [Permissions.webidl ](https://searchfox.org/mozilla-central/source/dom/webidl/Permissions.webidl) while Chrome has the [permission_descriptor.idl](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/permissions/permission_descriptor.idl;drc=f35c2f3fa70024abdcb62c7a7b1019267607d486) both diverging quite a lot in the enumeration of permission names.

**Comment by javifernandez** [comment]
I've created an [issue](https://github.com/whatwg/html/issues/7920) in the html spec to discuss the standardization of this new permission name.

**Comment by annevk** [comment]
What I was hoping is that we could have something that does not end up being web-exposed.

**Comment by annevk** [comment]
I recommend reaching out to @jgraham on Matrix.

**Comment by javifernandez** [comment]
If I've understood it correctly, @jgraham propose the definition of a new WebDrviver endpoint to handler the permission prompt. I also have understood that the ideal approach would be to use the new WebDriver-BiDi but unfortunately this won't be available soon. Regarding the new endpoint, I've filed https://github.com/w3c/webdriver/issues/1677; it seems that this user prompts related issue is affecting other testing use cases, so perhaps it'll be closed as duplicated. 

Anyway, while studying the WebDriver spec I found out that there is indeed a [way](https://w3c.github.io/webdriver/#user-prompts) of handling simple prompt dialogs. Wouldn't be possible to use one of these as part of the registerProtocolHandler method ? 

The spec doesn't mention at all which kind of dialog should be used; it states. 

> A user agent could, for instance, prompt the user and offer the user the opportunity to add the site to a shortlist of handlers, or make the handlers their default, or cancel the request. User agents could also silently collect the information, providing it only when relevant to the user.

Wouldn't be possible to change to text in the spec to suggest the use of a specific dialog ?

**Comment by javifernandez** [comment]
Another approach, more in the line of the original idea to define a new WebDriver endpoint, would be to define an 'extension command' similar to what we have for the [Secure Payment Confirmation](https://w3c.github.io/secure-payment-confirmation/) feature with the [Set SPC Transaction Mode](https://w3c.github.io/secure-payment-confirmation/#sctn-automation-set-spc-transaction-mode) command.

**Comment by javifernandez** [comment]
At lest @foolip expressed interest on defining a new WebDriver endpoint for the Custom Handlers, so that we could define some kind of autoreply on the prompt dialog and define automated tests for the registerProtocolHandlers method. 

I've filed an [issue](https://github.com/whatwg/html/issues/8251) for the html spec to discuss this idea and figure out whether there is enough support from at least 2 implementers, so that a PR for the spec is worth. It'd be great to have some feedback from Mozilla, perhaps @jgraham ?

**Comment by javifernandez** [comment]
We have now a new WebDriver extension command to avoid the user prompt dialog, which together with the [bless](https://web-platform-tests.org/writing-tests/testdriver.html#test_driver.bless)  API, should be enough to provide testing automation for protocol handlers.

I'm currently working on the implementation for this command for chromedriver and it seems there is "some" interest expressed (see [here](https://github.com/mozilla/standards-positions/issues/685) and [here](https://github.com/whatwg/html/pull/8267#issuecomment-1377669247)) by Firefox. I have the [PR#35792](https://github.com/web-platform-tests/wpt/pull/35792) for automated tests covering the cases we already have in the manual tests.

**Comment by javifernandez** [comment]
This is implemented in Chrome [1](https://issues.chromium.org/issues/40237231) and defined the proper APIs and actions in the WPT scrips [2](https://github.com/web-platform-tests/wpt/pull/35792), so I think we can close this issue now.
