### ISSUE TITLE
module named 'distutils.spawn' not found (triggered by ../../wpt lint call)

### ISSUE THREAD

**Issue by TalbotG** [web-platform-tests/wpt#27180]
@web-platform-tests/admins

Dear fellow advanced GitHub colleagues,

I was creating [PR27179](https://github.com/web-platform-tests/wpt/pull/27179) and did what I always do : '../../wpt lint' and I got this response:
{
Traceback (most recent call last):
  File "../../wpt", line 5, in <module>
    from tools.wpt import wpt
  File "/home/gerard/Documents/github/web-platform-tests/tools/wpt/wpt.py", line 10, in <module>
    from . import virtualenv
  File "/home/gerard/Documents/github/web-platform-tests/tools/wpt/virtualenv.py", line 5, in <module>
    from distutils.spawn import find_executable
ModuleNotFoundError: No module named 'distutils.spawn'
}

The good news is I was still able to submit such PR (but without a prior lint validation check).

All the best to you in 2021 (and lots of vaccination in 2021)

Gérard

**Comment by sideshowbarker** [comment]
I can’t reproduce in my macOS environment — neither in my existing wpt clone nor after cloning the repo from scratch and testing in that. But I guess that’s unsurprising, because it just means I have python distutils installed.

I think you can solve this by installing distutils — either using whatever package manager your OS/system provides, or else pip.

As far as I can from looking at that wpt infra bits, there’s nothing in there which installs distutils; instead the code just expects it to be installed in whatever python environment you’re using to run wpt stuff.

**Comment by TalbotG** [comment]
Michael,

Thank you for your quick response.

From what I can see, python3-distutils package has to be the package to install. 

https://packages.debian.org/buster/python3-distutils

"
This package contains the distutils module from the Python standard library.
"
I use Debian 10 (buster). Right now, python3-distutils package is indeed **not** installed on my system.

**Comment by TalbotG** [comment]
Okay... I just installed 

https://packages.debian.org/buster/python3-distutils version 3.7.3-1

and

https://packages.debian.org/buster/python3-lib2to3 version 3.7.3-1

Michael, do you know of a way by which I can verify that everything is in order now and functionning accordingly?

**Comment by sideshowbarker** [comment]
> Michael, do you know of a way by which I can verify that everything is in order now and functionning accordingly?

As far as the immediate issue, just re-run `wpt lint`?

**Comment by TalbotG** [comment]
I have re-run `wpt lint` and it worked!

Thank you for your assistance, Michael. This is greatly appreciated.

I am closing this issue now.
