### ISSUE TITLE
MojoJS 404 Client Error on Mac/Windows

### ISSUE THREAD

**Issue by leobalter** [web-platform-tests/wpt#27264]
I got this error from a new MacOS machine. OS Version is Catalina 10.15.7

The link to mojois is 404 on the browser as well and I don't know if there is any alternative available.

```
$ ./wpt run --install-browser --headless chrome dom/historical.html
Download and install chrome [Y/n]?
ERROR Cannot enable MojoJS: 404 Client Error: Not Found for url: https://storage.googleapis.com/chromium-browser-snapshots/Mac/845324/mojojs.zip
```

**Comment by stephenmcgruer** [comment]
Thanks for the report leo. This error should be non-blocking I believe; does the `wpt run` continue correctly or does it stop running after the ERROR?

**Comment by domenic** [comment]
I am also getting this non-blocking error every time I use `wpt run`, on Windows. For me it is:

```
ERROR Cannot enable MojoJS: 404 Client Error: Not Found for url: https://storage.googleapis.com/chromium-browser-snapshots/Win/886005/mojojs.zip
```

**Comment by leobalter** [comment]
I eventually did try again (from to Jan 20 to last month) to recollect the behavior but missed reporting here.

I managed to get `wpt run` but like @domenic reported it still runs.

As I just run wpt casually, I wonder if the 404 client error might be failing any subset of tests, but I guess it's not really affecting many of the tests I'm targeting.

**Comment by DanielRyanSmith** [comment]
I took a cursory glance at this issue, and it comes from the fact `mojojs.zip` is not bundled with Windows and Mac revisions of Chromium. This error should not be present on a Linux machine.

I checked the directroy for the [Mac revision mentioned by @leobalter](https://storage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Mac/845324/), as well as the [Windows revision mentioned by @domenic](https://storage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win/886005/), and the mojojs file is definitely not present. To make sure this is not just a transient issue, I checked the latest revisions as of this comment and the file is still not present for either [Mac](https://storage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Mac/970135/) or [Windows](https://storage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win/970118/). However, it is available for all recent revisions I have checked when downloading for [Linux](https://storage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Linux_x64/970148/).

**Comment by DanielRyanSmith** [comment]
I've updated the title for this issue and since I've been working on infra items that are tangentially related to this, I'll post my diagnosis here:
The current implementation of WPT's MojoJS installation for Chrome tries to download and install from the [Chromium Snapshots API](https://storage.googleapis.com/chromium-browser-snapshots/index.html), but the MojoJS file is only bundled with the `Linux_64` revisions of Chromium. This means that MojoJS will only be downloaded on Linux and will print a generic and confusing 404 Error message for every invocation of `wpt run chrome` that is not on Linux (see issue #27264). If the file is platform-independent, the likely fix here is to always pull from the more reliable [chrome-wpt-mojom](https://storage.googleapis.com/chrome-wpt-mojom/). If not platform-independent, make the MojoJS install only attempted on Linux.

**Comment by DanielRyanSmith** [comment]
@foolip This is the issue I spoke of regarding MojoJS. I think this is worth taking care of, as it's confusing to users and also there's a better process for us to handle downloading the correct MojoJS version. It's also worth writing thorough documentation about how we're getting MojoJS and why we do it.
