### ISSUE TITLE
Incrementally expanding the use of mypy

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#28833]
Creating a new issue to consolidate discussion.

I asked in https://github.com/web-platform-tests/wpt/pull/28815:

> @gsnedders I'm having some fun learning more about mypy. I'm not sure it's worth annotating all of wptserve, but the reason I started was because I found it very hard to guess what the types of some arguments in request.py were. But starting from the "leaf" files results in less cascading errors.
>
> Is there an approach to incrementally improving type coverage that you took for other bits that I could copy?

@jgraham wrote in https://github.com/web-platform-tests/wpt/pull/28757#discussion_r625019309:

> I think if we want to start adding type annotations we should also figure out how we're going to check them (and this is perhaps not a small problem for test files because it likely means vendors should be running the exact same version of mypy in their CI; for tools changes it's kind of assumed that people submitting patches to vendor repos are able to deal with the consequences of failing upstream checks, but that is less true for test authors).

https://mypy.readthedocs.io/en/stable/existing_code.html has some useful guidance, but we'd still need to figure out most of the hard problems stemming from downstream changes ourselves.

Let's treat the problem of tools/ and everything else separately. Outside of tools/, my thoughts are:
- webdriver/tests/ is fairly self-contained. With about 18.5k lines of code, it's probably worthwhile.
- *.py handlers are going to be the hardest since they're often edited in vendor repos, and not of huge value since they're usually short scripts

**Comment by foolip** [comment]
Is it possible to lint for type annotations so that they're only used where we actually run mypy?

I noticed there's at least `webtransport/quic/handlers/client-indication.quic.py` which came from https://github.com/web-platform-tests/wpt/pull/22844.

**Comment by jgraham** [comment]
Note that a lot of WebDriver tests originate in vendor patches. So it's exactly the kind of code where being able to run the typecheck as part of vendor CI using the exact same version of mypy that we use elsewhere would be most worthwhile. That seems like a reasonably complex problem and so isn't the first thing I'd tackle. Also (hopefully) tests are faily small and self contained, so figuring out the code directly isn't too bad (I don't think this is always true but it's a nice idea :) )

Practically I think the largest benefit in the short term is going to come from extending the use of mypy to cover more of the tools/ directory. I'm not so worried about the vendor CI problem there since it's a much smaller group of contributors and they mostly know how to interact with GitHub. 

Making wptserve and wptrunner a) pass typechecks and b) actually have type annotations seems like the right next step. I'd guess it's going to be a few weeks of work at least; some Python patterns are easy to express in code and hard to express in types, and I've previously found during this kind of conversion that I just rewrote code to be less dynacially typed rather than trying to figure out how to make mypy happy.

**Comment by jgraham** [comment]
Oh and for linting, I'm pretty sure we could write a lint using the python tokenize module (or build a full ast if needed) to find things that look like type annotations outside a specific list of directories. It's not going to be trivial, but it feels possible at least.

**Comment by foolip** [comment]
How big of a step would it be to run mypy on all of tools/ but only have the strict options apply to the parts of the code that it currently runs on (manifest+lint+gitignore)?

**Comment by jgraham** [comment]
You could rename `mypy.ini` to `mypy_strict.ini` and add a `mypy_lax.ini` and make tox run some modules with one and some with the other. How hard it would be to make the code pass anything other than `ignore_errors=True` I don't know without running the experiment.

**Comment by foolip** [comment]
I gave this a shot today, and with not too much fixing of fatal errors it's possible to run mypy for all of tools/ with a bunch of packages explicitly ignored, and some paths not checked at all. I'll send PRs of minor things that are blocking with reference to this issue.

**Comment by gsnedders** [comment]
> Oh and for linting, I'm pretty sure we could write a lint using the python tokenize module (or build a full ast if needed) to find things that look like type annotations outside a specific list of directories. It's not going to be trivial, but it feels possible at least.

I'm not convinced it's overly worthwhile to actually forbid them elsewhere, tbh?

But I do think getting all of tools/* covered would be good. (And we can use the Py3 syntax now! 💜)

**Comment by foolip** [comment]
OK, it was hairy to get done but the result looks clean enough: https://github.com/web-platform-tests/wpt/pull/28900

It depends on some other changes, so I'm leaving it as a draft. Enough mypy for today I think :)

**Comment by foolip** [comment]
Closing this, mypy is now running with optional typing in all of tools/. Getting 100% type coverage is a whole other story, and probably not worth pushing for.
