### ISSUE TITLE
Split chrome product into chromium and chrome

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#28970]
While working on https://github.com/web-platform-tests/wpt/pull/28902 I realized that the `Chrome` class supports installing both Chromium and Chrome, depending on the channel. And it will try to find the ChromeDriver binary in a different manner for each, exemplified by code like this:

https://github.com/web-platform-tests/wpt/blob/f0f68baf062ad5f49a550bde80213458546cb70a/tools/wpt/browser.py#L748-L749

At the same time, being able to run a specific revision of Chromium would be very handy, and the code is *almost* in a place where that's possible.

So it seems like a good idea to split the product into two, one for the blue-icon Chromium binaries from https://www.chromium.org/getting-involved/download-chromium and another for Google Chrome, with code sharing as necessary. The result should be that something like this is possible:

> ./wpt run --chromium-revision=881632 chromium dom/

As a nice follow-up to this, we could also do the work of identifying which recent revision actually works on Linux, macOS and Windows, and make it easy to use that version with `--chromium-revision=pinned`, or even pin it by default with `--chromium-revision=latest`.

**Comment by gsnedders** [comment]
This is presumably actually a `tools.wpt` run issue, not a `wptrunner` issue? It doesn't make sense to split it on the wptrunner side, does it?

**Comment by foolip** [comment]
Yeah, I was reading `tools/wpt/browser.py` and not thinking too hard when I labeled this. The files in `tools/wptrunner/wptrunner/browsers/` are pretty small and not a whole lot of duplication that I can see.

**Comment by dasa376** [comment]
function add_contact_links ( $text ) {   $text .= '   <hr><p><a href="' . get_permalink($post) . '#commentform">Add a comment to the post, or <a href="mailto:admin@example.com?subject=In%20reply%20to%20%22' . str_replace(' ', '%20', get_the_title()) . '%22">email a reply</a>.</p>';   return $text; } add_filter('the_content_feed', 'add_contact_links');

**Comment by DanielRyanSmith** [comment]
I'm interested in taking a look at this issue. I have some initial questions that could be clarified:

1. It looks like the Chromium chromedriver is being used for Chrome when no version is specified. Will this still need to be the  case when splitting the two?
2. Would it be advisable to implement the new `Chromium` Browser and BrowserSetup child classes to inherit from the `Chrome` classes and override methods as needed, or is this a potentially risky way to solve the problem?
3. Are there any important details about specifically running tests against Chromium that will need to be addressed?

**Comment by foolip** [comment]
Thanks for taking a look @DanielRyanSmith!

> 1. It looks like the Chromium chromedriver is being used for Chrome when no version is specified. Will this still need to be the  case when splitting the two?

This is one of the strange things about the current situation. I think we should use the `chromedriver` binary built from the same commit or release branch as the browser under test. For Chrome that's an official ChromeDriver release, and for Chromium it'll be `chromedriver` from the same URL as the Chromium archives that we download.

I'm not sure about Chrome Dev and Canary, in the past there was no official ChromeDriver for those channels, and I think that's why `chromedriver` from Chromium is being used here.

> 2. Would it be advisable to implement the new `Chromium` classes to inherit from the `Chrome` Browser and BrowserSetup child classes and override methods as needed, or is this a potentially risky way to solve the problem?

I was thinking that `Chrome`, `Edge` and `Opera` would inherit from `Chromium`. But when getting into the details there may be good reasons to do it some other way. Like maybe we want a abstract base class that does nothing, and having the Chromium product be a sibling class for Chrome.

> 3. Are there any important details about specifically running tests against Chromium that will need to be addressed?

I think one question is what to do with expectations, the *.ini files that is. If we have to specify both `chrome` and `chromium` for all failing tests in infrastructure/ that would be a nuisance. But it is what we do for Safari and WebKitGTK, so maybe that's fine. We could also just have Chromium expectations here.

**Comment by DanielRyanSmith** [comment]
Excellent, I'll take a thorough look and report back if I have further questions.

**Comment by DanielRyanSmith** [comment]
Hello @foolip, I took a further look and I have a big wall of questions to make sure I am approaching this issue correctly. Maybe you have the answer to some of these?

1. Will testing Chromium separately have any reduced testing functionality? Or should it have all the testing capability of any other browser?

2. What exactly needs to be separated into Chromium? Is it just a matter of changing how the binaries are detected/installed, and the running of the tests function the same as with Chrome?

3. I noticed there is a class for “Edge” and “EdgeChromium”. Are there times where Edge is run without Chromium and will that still need to be supported?

4. Will there need to be any changes to how Edge and Opera install/detect their webdriver? Or will there be no functional change to how Edge and Opera? 

5. Follow up to question 4, if no functional change is needed, is there a reason we would need Edge and Opera to inherit from Chromium? Is there any functionality they need to share?

6. Are there any differences in how different channels are tested or is it just used to determine where to get the browser binary?

7. Which channels are the most important and do all browsers have the same channels?

8. Can we still only reliably download the nightly version of the Chrome browser and does this apply to Chromium? ([see here](https://github.com/web-platform-tests/wpt/blob/master/tools/wpt/browser.py#L554))

9. Based on this:
_"I think we should use the chromedriver binary built from the same commit or release branch as the browser under test. For Chrome that's an official ChromeDriver release, and for Chromium it'll be chromedriver from the same URL as the Chromium archives that we download."_
Do we have some way to detect which chromedriver binary the browser being tested has been built with?

10. Will Chromium need a separate requirements file like the ones specified [here](https://github.com/web-platform-tests/wpt/blob/master/tools/wpt/browser.py#L526)?

11. What do we need Mojo.js for on Chrome and do we need it for Chromium?

Thanks for the help with this!

**Comment by DanielRyanSmith** [comment]
Here are some more questions I have now that I'm diving deeper into this issue:
1. Do Chromium and Chrome have all the same channels?
2. Judging by [the Chrome browser install method](https://github.com/web-platform-tests/wpt/blob/master/tools/wpt/browser.py#L552), it looks like the only browser binary that can be installed via `./wpt install` is the Chromium top of tree. Just to make sure, does that mean this download is Chromium and not Chrome?
3. If the previous question is true and we are only downloading the Chromium browser binary, that means that we currently don't have the implementation to `./wpt install` a Chrome browser binary at the moment. Is there an api that exists that can consistently get some version of Chrome for the user?
4. Does Chromium need the mojo.js download as well?
5. It looks like Chromium will need its own [wptrunner file](https://github.com/web-platform-tests/wpt/blob/master/tools/wptrunner/wptrunner/browsers/chrome.py) if we want to run tests as a separate product. Is there anything specifically that should be different in the Chromium version of this file?

**Comment by DanielRyanSmith** [comment]
This is the basic set of functionality I've been able to set up and split for Chrome and Chromium so far:

| Functionality  | Chrome | Chromium | 
| ------------- | ------------- | ------------- |
| Can use `./wpt install` to install correct browser binary | ❌ | ✅ |
| Can use `./wpt install` to install correct webdriver | ✅ | ✅ |
| Detects browser binary on machine | ✅ | ❌ |
| Detects browser binary in venv | ❌   |  ✅  |
| Distinguishes difference between Chrome and Chromium browser binaries | ✅ | ✅ |
| Detects webdriver in venv    | ✅  | ✅ |
| Prompts webdriver install if not found    | ✅  | ✅ |
| Distinguishes difference between Chrome and Chromium webdriver binaries | ✅ | ✅ |
| Runs basic tests (dom/historical.html for example) | ✅ | ✅ |

The biggest thing that I've noticed is that originally we could only `./wpt install` the Chromium top of tree browser for the user and there was no way to use this command to install Chrome. That is why the current functionality above states that Chrome cannot be detected in the venv. This can change if we still want to look for Chrome in the venv or we implement a way to download the browser binary for Chrome.
Here are some more questions I have now that I'm diving deeper into this issue:

1. The first question relates to the above. Is there some api for us to install Chrome for the user or is it only Chromium ToT we can retrieve this way? If we can only download Chromium, do we cease functionality if the user tries to run `./wpt install chrome browser`?
2. Should we still search the venv for a Chrome browser binary if we cannot install it using `./wpt install`?
3. With the current implementation, you cannot have both Chromium and Chrome's webdriver in your virtual environment at the same time. If switching back from testing Chromium to Chrome, the user will be prompted to reinstall the relevant chromedriver. However, the wrong chromedriver should never been incorrectly detected and used. Is this a good approach?
4. Do Chromium and Chrome have all the same channels?
5. Does Chromium need the mojo.js download as well?
6. It looks like this [wptrunner file](https://github.com/web-platform-tests/wpt/blob/master/tools/wptrunner/wptrunner/browsers/chrome.py) is an important piece of running tests. At first glance it looks like we need a separate version of this file for Chromium, but perhaps there is a way to implement this so that they use the same file if that's feasible. Is there anything specifically that should be different in the Chromium version of this file? It's a lot of information and I'm not sure what to differentiate here.
7. Where can I find the *.ini files that are relevant to these changes? I'd like to ensure I'm looking in the correct place

**Comment by foolip** [comment]
For anyone following along, @DanielRyanSmith have discussed the questions out-of-band, I'm not just ignoring :)

**Comment by DanielRyanSmith** [comment]
This is the current production implementation of WPT's ChromeDriver install:
1. If a binary is already in the venv and "matches" based on our loose matching, we just use that
2. If channel is nightly, install tip-of-tree and ignore everything else
3. Detect version from browser binary
4. Use it to try and get a version from official releases
5. If that fails, detect the chromium revision that matches the browser binary version
6. Download from the Chromium snapshots bucket based on that revision.
7. If we fail to match a revision or the revision isn't available for download, fall back to tip-of-tree

I tested this two times today to be certain this is correct. I used the debian install we use for taskcluster to get a google-chrome-unstable version of Chrome dev. The first time I did this, the Chrome dev version was 100.x.x.x, and when installing ChromeDriver via WPT's setup, it fell all the way back to downloading from tip-of-tree Chromium ChromeDriver.
I tried it later and downloaded Chrome dev again. Coincidentally, we just moved the dev version up to 101.x.x.x a few hours ago- so when I tried it again, the revision matching from Omaha Proxy and download from snapshots worked. But I think that might be because Chrome Dev is exactly the tip-of-tree now 😅

This also brings up an important usability issue... With the current implementation, if you don't specify a --channel at all, Chrome will always download a tip-of-tree ChromeDriver no matter what browser version you're using. The process only checks if the browser and webdriver are compatible when checking an already existing ChromeDriver, and just assumes they match after installing.
