### ISSUE TITLE
WebKitGTK runs using old WebKitGTK

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#29203]
It seems like https://webkitgtk.org/built-products/x86_64/release/nightly/Ubuntu-20.04/MiniBrowser/ hasn't been updated in a while (since April), hence we're getting kinda old with the WebKitGTK runs now on wpt.fyi?

cc @clopez

**Comment by clopez** [comment]
Indeed. There is a failure on the nightly build bot: https://build.webkit.org/#/builders/30
I wiill look at fixing it.

**Comment by clopez** [comment]
This was caused by the build system trying to use libsoup3 which was still not available on the base system or the trird-party jhbuild system. Changed the build options to use libsoup2 back.
The bot is producing built products back again. I will configure an alert to be alerted next time more quickly about this.
