### ISSUE TITLE
Unable to render korean symbols in some css-text related tests

### ISSUE THREAD

**Issue by javifernandez** [web-platform-tests/wpt#29308]
I'm not sure whether the following tests are loading the right font, but the screenshot used to visualize the failure doesn't look correct. 

https://wpt.fyi/results/css/css-text/white-space/trailing-ideographic-space-003.html?label=master&label=experimental&aligned

https://wpt.fyi/analyzer?screenshot=sha1%3Ae9a4efd3ee417e41ed59eb8a38db0e5707d8de9c&screenshot=sha1%3A0a8c8214cf48eb8ce0d59eda42ccede98a8d364c

**Comment by foolip** [comment]
@jgraham I assume the issue of which fonts are installed has come up before, do you know if the way things now work is intentional, or something we should fix?

**Comment by jgraham** [comment]
I thought typically we wanted the fonts to be checked in and used as a webfont. Having system-wide requirements on font availability is tricky (we used to require Ahem to be on the system, and had some quite complex infrastructure to install it, but eventually switched to web fonts). Of course there are some tests for which webfonts don't work (e.g. font selection tests).

@jfkthame might have some additional input here.

**Comment by jfkthame** [comment]
I guess the assumption of the test here is that all systems will have some kind of a font for Japanese, which is probably true for standard installations of macOS or Windows, but may not be for a base Linux system unless the user has installed some additional font/language-support packages (depending how the specific distro organizes these things).

So yes, it would be better/more reliable to use a webfont rather than assuming system font availability. In this case, for Japanese character support, maybe the font that's already present at `tests/fonts/mplus-1p-regular.woff` would serve. (I haven't specifically checked its character repertoire, but I believe it covers common CJK characters.)

**Comment by gsnedders** [comment]
See also: https://github.com/web-platform-tests/wpt/issues/13203

**Comment by r12a** [comment]
I agree with @jfkthame, but fwiw and just in case it's useful for some cases where webfonts won't work, there's a list of system fonts available on Mac and Windows, grouped by script (plus Noto and SIL fonts) at https://r12a.github.io/scripts/fontlist/.  It's not 100% exhaustive, but it's close.

**Comment by gsnedders** [comment]
Closing this in favour of #13203, to avoid splitting the discussion further.
