### ISSUE TITLE
Rename master branch to main branch

### ISSUE THREAD

**Issue by rniwa** [web-platform-tests/wpt#30242]
Per https://www.w3.org/Guide/manual-of-style/#inclusive, we should rename master branch to main branch.

Also see https://github.com/w3c/idcg/issues/17

**Comment by lucacasonato** [comment]
xref https://github.com/web-platform-tests/rfcs/pull/80

**Comment by foolip** [comment]
I'd also like to see this happen. If someone would like to take over https://github.com/web-platform-tests/rfcs/pull/80 and drive it to completion, I would be very happy. It's a lot of work to ensure this change won't break anything given all the repos involved, and also things like https://wpt.fyi/results/?label=experimental&label=master&aligned where we'd need some changes in wpt.fyi.

**Comment by jgraham** [comment]
Yes. This is not a trivial change since there's quite a lot of infrastructure to update, spread across multiple repositories and consumers of wpt. Despite that, I agree that it's a good idea if we can come up with a plan that isn't just "break consumers and hope they update". However I'm going to close this issue to ensure that discussion happens in one place (the RFC).
