### ISSUE TITLE
Trick(?) to force MutationObserver records may not be cross-compatible

### ISSUE THREAD

**Issue by Kaiido** [web-platform-tests/wpt#35393]
In [/shadow-dom/declarative/innerhtml-on-ordinary-template.tentative.html ](https://github.com/web-platform-tests/wpt/blob/master/shadow-dom/declarative/innerhtml-on-ordinary-template.tentative.html) and [/shadow-dom/declarative/innerhtml-before-closing-tag.tentative.html](https://github.com/web-platform-tests/wpt/blob/master/shadow-dom/declarative/innerhtml-before-closing-tag.tentative.html) a surprising 

```html
  <script></script> <!-- Ensure observer runs -->
```

line is found. 
This triggered [this StackOverflow question](https://stackoverflow.com/questions/73283986/) where I developed the hypothesis that this line is supposed to force the MutationObserver's notifications to be dispatched before the `<script></script>`'s parent element is closed.  

However, if this hypothesis is indeed the correct one, then it should be noted that it doesn't work in Firefox, where scripts are apparently ran only if the `<script>` tag actually has a text value.  
One solution would be to add the comment as a JS comment inside the `<script>` instead and maybe change this comment to make it clear it relies on this side-effect.  

And if my hypothesis is wrong and that this `<script></script>` serves an entirely different purpose, I guess a better comment explaining what it is really doing may be a good idea.

cc @mfreed7

**Comment by mfreed7** [comment]
Thanks for raising this issue! Also thanks for [your analysis on SO](https://stackoverflow.com/questions/73283986/how-script-tag-forces-mutationobserver-to-run-early-in-declarative-shadow-dom), which I agree with.

Per spec, the [clean up after running script](https://html.spec.whatwg.org/multipage/webappapis.html#clean-up-after-running-script) algorithm, step 3, says:

3. If the [JavaScript execution context stack](https://tc39.es/ecma262/#execution-context-stack) is now empty, [perform a microtask checkpoint](https://html.spec.whatwg.org/multipage/webappapis.html#perform-a-microtask-checkpoint). (If this runs scripts, these algorithms will be invoked reentrantly.)

That's called by [run a classic script](https://html.spec.whatwg.org/multipage/webappapis.html#run-a-classic-script) in all cases, and that algorithm makes no mention of exceptions for, e.g. empty scripts.

I might be missing a mention somewhere about empty scripts, but I couldn't find one. If not, this seems like a bug in Gecko, rather than a problem with the test. If so, the likely best course of action would be to raise a [bug on Bugzilla](https://bugzilla.mozilla.org/enter_bug.cgi).

**Comment by Kaiido** [comment]
Fair enough, I opened https://bugzil.la/1784187 however I still believe this "Ensure observer runs" is quite obscure as to "how" it's supposed to do this, and "when" it does this. Maybe replacing with "Ensure observer runs **now**" would be enough?

**Comment by mfreed7** [comment]
> Fair enough, I opened https://bugzil.la/1784187 however I still believe this "Ensure observer runs" is quite obscure as to "how" it's supposed to do this, and "when" it does this. Maybe replacing with "Ensure observer runs **now**" would be enough?

Thanks for the suggestion - done! Hopefully the new version is more clear. I also added some content to the `<script>` tag to hopefully make it more compatible with Gecko in the meantime.
