### ISSUE TITLE
wpt-firefox-nightly-stability blocks a change that adds fuzzy rule to a test

### ISSUE THREAD

**Issue by wangxianzhu** [web-platform-tests/wpt#37632]
https://chromium-review.googlesource.com/c/chromium/src/+/4118401 adds fuzzy rules for css/compositing/mix-blend-mode/*, to tolerate small differences in color blending results, antialiased-pixels along rounded corners, edges of 3d-transformed elements. However, css/compositing/mix-blend-mode/mix-blend-mode-animation.html flakily failed on wpt-firefox-nightly-stability (https://github.com/web-platform-tests/wpt/runs/10219129974):

```
FAIL /css/compositing/mix-blend-mode/mix-blend-mode-animation.html - ...
Found 10000 pixels different, maximum difference per channel 76
...
Found 10000 pixels different, maximum difference per channel 6
...
Found 10000 pixels different, maximum difference per channel 4
...
Found 10000 pixels different, maximum difference per channel 8
...
Found 10000 pixels different, maximum difference per channel 8
...
Found 10000 pixels different, maximum difference per channel 10
...
Found 10000 pixels different, maximum difference per channel 11
...
Found 10000 pixels different, maximum difference per channel 3
...
Found 10000 pixels different, maximum difference per channel 7
```

The first failure looks like a real one. I'm wondering why the test wasn't failing without the change. I could modify the fuzzy range to 0-10 to make the test pass in an 80% chance on Firefox, but there is still a chance to fail.

**Comment by wangxianzhu** [comment]
I just looked into the test, and I believe the flakiness is a problem of the test which contains an opacity animation from 1 to 0.1, instead of the browser. I'll add a large fuzzy range for the test to tolerate the flakiness.

However, it's still a question why wpt-firefox-nightly-stability blocks a change that adds fuzzy rules.

**Comment by jgraham** [comment]
The infrastructure isn't nearly sophisticated enough to be able to tell whether a change is a) only to fuzzy rules and b) only weakening the pass conditions, not making it tighter. And even weakening the pass conditions could turn a perma-fail into an intermittent pass, which would cause stability checks to fail.

So basiclly I don't think we can do much better here whilst retaining stability checking in CI.

**Comment by wangxianzhu** [comment]
Oh, I thought my change caused the test to fail on Firefox somehow. Now I perhaps understand that the test previously consistently failed on Firefox, and now it sometimes succeeds with the change.

In my change, I can modify the test to make it not flaky.

However, in general, if a change reduces the failure rate (e.g. from 100% to 50%) of a test, should the change be blocked?

**Comment by jgraham** [comment]
We don't currently have any way of knowing that the failure rate went down. But also it's not really clear that a flaky test is better than a permafail, and if you introduced a change that made a permafail test pass some of the time, it might (as in this case) be a relatively small adjustment to make it reliably pass instead.

**Comment by WeizhongX** [comment]
Currently if a PR is blocked by wpt-firefox-nightly-stability, the two-way-sync rotation team will file a crbug in chromium then admin merge the PR.

Maybe we should make a change to make wpt-firefox-nightly-stability non-blocking, and file a crbug automatically.

**Comment by jgraham** [comment]
Note that this is also a problem with Chromium stability jobs; they can block PRs including exports from Gecko.

The reason to make the stability jobs blocking is because knowingly introducing flake into tests is bad, and vendor exports are highly likely to have only been tested in the vendor engine. So the CI acts as a warning that the test might be making engine-specific assumptions that are likely to lead to the results being ignored in other browsers (e.g. because the test will be annoated as flaky or just disabled).

So even though this does indeed cause frustration, to consider making a change here we'd need clear evidence that the existing setup isn't achieving its goals, and to have a broader discussion about other changes that might achieve those goals instead. Just ignoring the problem and allowing people to land tests that are unstable in other browsers without any warning isn't going to result in a usable cross-vendor testsuite.

**Comment by WeizhongX** [comment]
I totally agree with the goal set above. The thing is stability jobs can block PRs, but they won't block the corresponding CL from landing in chromium. (What is the case in Gecko?) Once the chromium CL is merged, there is not much left to be done on the PR. What we do now is to file a crbug for the author, then admin merge the PR. If we don't merge the PR, there is a chance there would be merge conflicts on subsequent exports.

The exporter will put a comment on CL if the corresponding PR at upstream is flaky. What action to take is totally up to the author. Depending on the situation, for example an existing flakiness, it's possible no action will be taken.

So what I am proposing is simply to automate the current process.

Can we block the CL from landing in chromium on in gecko if the test is flaky in another browser? Probably not if the issue is not in the test, we would also need to reduce the false positive rate at upstream.

**Comment by wangxianzhu** [comment]
Thanks jgraham for the explanation. I'm closing this issue. I filed it when I misunderstood the situation. I thought my CL caused the test to fail on Firefox, but actually my CL caused the test from 100% failing to flaky. It's good to catch such situations and avoid that.
