### ISSUE TITLE
Error when running `wpt run`

### ISSUE THREAD

**Issue by marcoscaceres** [web-platform-tests/wpt#39279]
Whe I try: 
```
./wpt run safari badging

```

I get
```

  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [185 lines of output]
```

**Comment by gsnedders** [comment]
Once again our choice of default logger provides essentially useless output, because it swallows all the output that might tell the user what actually failed to build.

If you re-run with `--log-mach - --log-mach-level debug` do you get anything more useful?

Or, practically, at this point, given this is months old, I expect it's non-actionable?

**Comment by marcoscaceres** [comment]
Closing... it's working.
