### ISSUE TITLE
LegacyWindowAlias shouldn't be tested in ShadowRealm idlharness tests

### ISSUE THREAD

**Issue by mgaudet** [web-platform-tests/wpt#39480]
Working on getting the ShadowRealms web-platform integration, and I find that `url/idlharness-shadowrealm.window.js` fails the LegacyWindowAlias test.

Feels like since ShadowRealm globals aren't `window` the alias shouldn't exist, and thus the test should pass.

**Comment by ptomato** [comment]
I've reviewed this and I think the test harness is correct — I verified that it only checks for the existence of the LegacyWindowAlias if `'document' in self`, which should not be true for a ShadowRealm global.

The name of the test in the results list is maybe a bit confusing, because in a ShadowRealm global the test actually asserts that the alias is _not_ present. So if it's failing, that might mean that the alias is erroneously present. Closing for now, feel free to reopen if I've misunderstood.
