### ISSUE TITLE
Missing Firefox nightly runs since May 4

### ISSUE THREAD

**Issue by past** [web-platform-tests/wpt#39939]
Firefox nightly runs are [missing](https://wpt.fyi/runs?label=master&label=experimental&max-count=100&product=chrome&product=edge&product=firefox&product=safari&product=webkitgtk) for the last week or so.

/CC @jgraham

**Comment by ulrich-berkmueller** [comment]
+1 for a quick fix, as it blocks the update of the aligned experimental statistics on wpt.fyi. In particular, the wpt.fyi/interop-2023 page is not updated and it seems that there is no progress on any browser).

**Comment by jgraham** [comment]
Since this is a pretty serious kind of issue, recording the triage steps here, in the hope that it's easier for people to investigate in the future:
 * Go to https://github.com/web-platform-tests/wpt/commits/master Notice all the red crosses by the builds.
 * Click on one shows that the Firefox jobs are indeed all failing.
 * Look for the first commit where there's a green tick: https://github.com/web-platform-tests/wpt/commit/c56aec60503481604225fdb7705f67d82ce437b8 and the first failing commit: https://github.com/web-platform-tests/wpt/commit/78e46a7f0a75734569955befb07ba9c89d4245e7 Those don't obviously look like they should have infra changes, so no big red flags at this point.
 * Look at some logs from one of the failing jobs. Using the job https://github.com/web-platform-tests/wpt/runs/13253070022 then "View logs in Taskcluster" for https://community-tc.services.mozilla.com/tasks/PeMvngUwRPK1tF-TCLquQg/runs/0/logs/live/public/logs/live.log
 * OK, there's a stacktrace trying to read the `profile.json` file (`tokenize.TokenError: ('EOF in multi-line statement', (51, 0))`). So now we've done all the steps that just require looking at wpt infrastructure, and we either need to look at code or have some prior understanding of how things work.
 * In this case I know we're taking the profile data from `hg.mozilla.org` directly, so it seems highly likely something changed in mozilla-central, and maybe there was a corresponding mozprofile change that hasn't been released yet. Let's see.
 * https://hg.mozilla.org/mozilla-central/log/tip/testing/profiles/web-platform/user.js is the history of one of the files we're using. There's a formatting change from [Bug 1830265](https://bugzilla.mozilla.org/show_bug.cgi?id=1830265) that looks very suspicious.
 * Looking at the diff for that https://hg.mozilla.org/mozilla-central/rev/546391a0de46c884b2cf65949331b02898137024 it seems like the initial hypothesis was correct; someone made a backwards incompatible change to the file format without considering out of tree consumers.
 
 I'm going to file a bugzilla bug and either get that change reverted or a new mozprofile released.

**Comment by past** [comment]
Closing, as this seems now fixed.
