### ISSUE TITLE
Azure pipeline error, Install Safari Technology Preview 

### ISSUE THREAD

**Issue by TalbotG** [web-platform-tests/wpt#39947]
@foolip , @jcscottiii , @gsnedders , @whimboo , @stephenmcgruer

Dear fellow github admins and colleagues,

In [Pull Request 39940](https://github.com/web-platform-tests/wpt/pull/39940/) , I stumbled on the following error (which seems like the same as in [Issue 34926](https://github.com/web-platform-tests/wpt/issues/34926)):

Check failure on line 87 in Build log

@azure-pipelines azure-pipelines / Azure Pipelines (affected tests without changes: Safari Technology Preview)
Build log #L87
Bash exited with code '1'.

L86: RemoteDisconnected('Remote end closed connection without response'))
L87: ##[error]Bash exited with code '1'.
L88: Finishing: Install Safari Technology Preview

Raw logs give:

2023-05-10T22:44:28.6718470Z requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2023-05-10T22:44:28.6825670Z ##[error]Bash exited with code '1'.
2023-05-10T22:44:28.6871330Z ##[section]Finishing: Install Safari Technology Preview

**Comment by TalbotG** [comment]
I closed and reopened this morning the [Pull Request 39940](https://github.com/web-platform-tests/wpt/pull/39940) and then the Continuous Integration checks restarted and are still running after 2 full hours... and are still running as both wpt.fyi hook: safari-preview-affected-tests are still spinning and running. There is obviously a problem with the installation of Safari Tech Preview.

**Comment by gsnedders** [comment]
> Check failure on line 87 in Build log

https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=100348&view=logs&j=44ec0541-331f-516a-1683-b860fdd2ecd9&t=90ea950a-2ef3-5f6e-551d-e9a4bef4254f

> https://github.com/azure-pipelines azure-pipelines / Azure Pipelines (affected tests without changes: Safari Technology Preview)
> Build log #L87
> Bash exited with code '1'.
> 
> L86: RemoteDisconnected('Remote end closed connection without response'))
> L87: ##[error]Bash exited with code '1'.
> L88: Finishing: Install Safari Technology Preview

This just looks like Azure Pipelines was failing to download the builds—don't know where the problem was, but clearly traffic wasn't getting through, and not clear we can do anything here.

> I closed and reopened this morning the [Pull Request 39940](https://github.com/web-platform-tests/wpt/pull/39940) and then the Continuous Integration checks restarted and are still running after 2 full hours... and are still running as both wpt.fyi hook: safari-preview-affected-tests are still spinning and running. There is obviously a problem with the installation of Safari Tech Preview.

A quick glance at https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=100406&view=logs&j=08493cca-2103-51b1-0f09-cf056c7851d8 shows "Started: Today at 15:52" v. the pipeline itself "Today at 13:55" — i.e., it simply didn't run at all for nearly two hours after being added, which is just a capacity issue (c.f. #33980).

Based on all that above, closing this.
