### ISSUE TITLE
Split up html/dom/interfaces.html

### ISSUE THREAD

**Issue by Ms2ger** [web-platform-tests/wpt#4002]
See comments starting at https://github.com/w3c/web-platform-tests/pull/3999#issuecomment-254416097

**Comment by Ms2ger** [comment]
>> In theory, sure. The one thing I'm worried about is making it harder to update to the spec.
>
> You mean because it would be harder to find where the IDL is pasted to update it?

Right now, you can use the script from <https://github.com/w3c/testharness.js/blob/5ed9b8fec6ca35d1281117c4fab7fa55d25e847b/docs/idlharness.md> to update everything at once; that may not be as obvious in a split test

**Comment by Ms2ger** [comment]
CC @foolip @sideshowbarker @jgraham

**Comment by foolip** [comment]
I didn't know there was a script, and it would be a bad idea to make it harder to keep tests in sync with the spec.

@mdittmer is working on some tools to scrape IDL from specs in order to compare them with Blink. I wonder if that could be put to use for also keeping IDL in web-platform-tests in sync with their specs?

Any new interface would have to end up *somewhere*, but maybe its initial location could be picked manually and then it's updated in place after that.

**Comment by ayg** [comment]
Two ways to have this still be easy to update:

1) Have the IDL in a separate include that's included by a few different files.  Each file somehow chops up the IDL, includes only one chunk as a tested IDL, and includes all other chunks as an untested IDL.

2) Write a different update script that does the chopping up and sticks the bits into the correct files.  This would have to be a command-line script (which we could include in the wpt tree) instead of an in-browser script.

In either case, I don't know how the script would figure out how to chop it up.  We need to keep the file that tests each interface be stable, because otherwise expected failures would move between files when the IDL is updated.

I really think it would be best if Blink and WebKit figured out some way to have a longer timeout for this file instead.  Firefox manages to.

**Comment by foolip** [comment]
@tkent-google, did you ever investigate exactly how slow these tests are, and if putting them in SlowTests would suffice?

**Comment by cdumez** [comment]
To work around the issue, WebKit skips this test in debug builds.

**Comment by tkent-google** [comment]
@foolip 
It seems I didn't try ```[Slow]``` specifier.
https://codereview.chromium.org/1149383002

**Comment by tkent-google** [comment]
Also, I tried enabling interfaces.html some weeks ago, and didn't enable it because its behavior wasn't stable.  The test creates a WebSocket object, and it shows a console error asynchronously.

As for splitting, how about adding filter argument to IdlArray.prototype.test?  For example, a file tests only interfaces starting with 'H', and another file tests anything else.
```
    idlArray.test("H.*");
```

```
    idlArray.test("[^H].*");
```

**Comment by ayg** [comment]
That sounds like a nice, stable way to split it up.  So have the IDL in a separate file that's included by a few different files (solution #1 above), and have a few test files that run various subsets based on patterns (just make sure that they collectively cover everything).

**Comment by ayg** [comment]
It creates a WebSocket object to test the WebSocket interface.  This should be harmless, right?

**Comment by Ms2ger** [comment]
Fixed in #11414
