### ISSUE TITLE
CSS2-based test text/text-align-white-space-003.xht is no longer valid per CSS Text 3

### ISSUE THREAD

**Issue by jfkthame** [web-platform-tests/wpt#40092]
This testcase checks that when white-space is set to pre-wrap, justification is not applied, which was what CSS2 required.

However, CSS Text 3 removed this restriction, allowing justification to be applied, in which case the test will not match the reference rendering.

As of today, https://wpt.fyi/results/css/CSS2/text/text-align-white-space-003.xht?label=experimental&label=master&aligned shows only Firefox passing this test, with both WebKit and Blink-based browsers failing because they apply justification, as allowed by CSS Text 3.

And with the landing of https://bugzilla.mozilla.org/show_bug.cgi?id=1253840, Gecko will also apply justification, and fail the test similarly to the other browsers.

So I suggest that it's time to either drop this test, or update its "expected" result to reflect the reality of modern browser behavior.

cc @TalbotG

**Comment by TalbotG** [comment]
@jfkthame , Jonathan,

First, thank you for adding me to this issue.

I am not sure we need to do anything about this test since it has the "may" flag. So, passing or failing such test is not required in order to claim compliance or conformance with the spec. Of course, we can remove it too. And later (I am quite busy these days... and behind, trailing in my to-do list) , I can create another test which will comply with CSS3 Text... or if you have a replacement test ready, I can review and approve it too.

I do not like this test as written for other (side, secondary) reasons. Anyway.. I am adding @fantasai and @frivoal just to be extra sure here, since they are editors of CSS3 Text.

**Comment by TalbotG** [comment]
@jfkthame ,

I see your 4 white-space-pre-wrap-justify-00[1-4]* tests and your 4 related references in
phabricator.services.mozilla.com/D178213
.. but I do not see your 4 tests in WPT repository...

**Comment by TalbotG** [comment]
I can create a pull request for you @jfkthame 
- which would include your 4 white-space-pre-wrap-justify-00[1-4]* tests and their 4 related references (as they are in phabricator.services.mozilla.com/D178213 ) and
- which would remove 
http://wpt.live/css/CSS2/text/text-align-white-space-003.xht

The pull request would have to be reviewed and approved by @fantasai or @frivoal 

Is that OK?

**Comment by jfkthame** [comment]
Yes, the new tests from phabricator.services.mozilla.com/D178213 should automatically get merged to WPT when the mozilla bug is resolved. Didn't happen yet because the initial landing was backed out, but I'll be re-trying soon.
