### ISSUE TITLE
Do not use empty string for test variant

### ISSUE THREAD

**Issue by WeizhongX** [web-platform-tests/wpt#40952]
For tests with variants, "wpt run the-test" will run the test and all the variants. This is undesirable because developers can not focus on the tests they want to run.

For example, "html/semantics/scripting-1/the-script-element/defer-script/async-script.html" has two tests:
html/semantics/scripting-1/the-script-element/defer-script/async-script.html and html/semantics/scripting-1/the-script-element/defer-script/async-script.html?reload

"wpt run html/semantics/scripting-1/the-script-element/defer-script/async-script.html"  should only run the first test. To run both, devs should write "wpt run html/semantics/scripting-1/the-script-element/defer-script/async-script.html  html/semantics/scripting-1/the-script-element/defer-script/async-script.html?reload"

**Comment by WeizhongX** [comment]
@jgraham @jonathan-j-lee thoughts?

**Comment by WeizhongX** [comment]
Looks like this is a problem specific to this test, because it has a variant with empty content, as below. I will make a change to this test for now. Should we make it a rule that variant content should not be empty?

    <meta name=variant content="">
    <meta name=variant content="?reload">

**Comment by jonathan-j-lee** [comment]
> Should we make it a rule that variant content should not be empty?

I don't think so---the empty variant seems to signal that it exercises some "default" behavior.

I also don't think changing `wpt run` to interpret a test path as the empty variant instead of all variants would represent a net improvement, since:
* Running all variants in a file now requires specifying all of them explicitly. Supporting globs might make this less painful (e.g., `html/semantics/scripting-1/the-script-element/defer-script/async-script.html*`).
* Presumably, we would keep the old behavior for test files without an empty variant, which introduces inconsistency.

---

For reference, test files with empty variants seem uncommon:

```sh
→ grep -R 'meta.*variant.*content=""' ~/chromium/src/third_party/blink/web_tests/external/wpt | wc -l
143
```

**Comment by gsnedders** [comment]
Do we not have differences here between `wpt run html/semantics/scripting-1/the-script-element/defer-script/async-script.html` and `wpt run /html/semantics/scripting-1/the-script-element/defer-script/async-script.html`?

IIRC, the former (without a leading slash) looks up the path as a file within the manifest; the latter specifies a URL to run, which presumably might be a specific variant?
