### ISSUE TITLE
Issue with css/printing/page-size-002-print.html

### ISSUE THREAD

**Issue by jwatt** [web-platform-tests/wpt#43350]
This test and reference appear to render differently in Chrome.

https://github.com/web-platform-tests/wpt/blob/3d4528724bca7062f8c39d879ac45f342a3291c0/css/printing/page-size-002-print.html
https://github.com/web-platform-tests/wpt/blob/3d4528724bca7062f8c39d879ac45f342a3291c0/css/printing/page-size-002-print-ref.html

The short page height of 50px appears to trigger Chrome to reject the CSS page size and instead use US Letter.

From experiment, it seems that adding a `margin` with a value less than `25px` to the `@page` rule in the test will get Chrome to honor the CSS page size. Presumably Chrome has some logic to reject the CSS page size if the page margins leave no room for any page content. The [default page margin of 0.5 inches](https://github.com/web-platform-tests/rfcs/blob/master/rfcs/print_test.md) is 48px by definition, which clearly is too much to leave any room for page content.

Printing the test in Chrome using `Save as PDF`, each of the three `div`s is printed to a separate page. The reference on the other hand results in a single page containing all the `div`s. This seems expected if the CSS page size is rejected, given that the test uses `break-before` and the reference uses a div height equal to the specified (but rejected) page height.

Perhaps the test should be changed to set the page margins to zero?

Besides the issue with the test, someone working on Chrome probably wants to look into why their WPT test runner isn't failing on this test.

@mstensho

**Comment by mstensho** [comment]
You're right. Chrome discards the size / margins in @page if it results in a nearly-zero / negative page area size. Code here:
https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/dom/document.cc;l=2809-2815;drc=416222c9d2b7585aafcbc8bc2017f3bc251aac9e

The code above is currently not an issue when running WPT tests (well, as long as we're using our own test runner, at least) in Chromium, though, since the default margins are 0 then. That's another interesting discussion, though. See https://github.com/web-platform-tests/wpt/issues/40788 - it's not entirely clear if the default margins should be 0 or 0.5in. This test assumes that they are 0, and we should really have some tests that make assumptions about default margins, since we're apparently attempting to define a default for WPT. But if it's not 0, this test is wrong. :)

**Comment by jwatt** [comment]
Thanks for the reply.

So I'm a little confused after reading #40788. It sounds like you changed from using 0.5in in your test runner to using 0, but you commented in that issue that `infrastructure/reftest/reftest_match-print.html` would then start failing. It looks like that test would still fail with a margin of 0, so did you just mark it as failing for you, or am I missing something?

Would you be ameanable to going back to using 0.5in margins, and then we can change `css/printing/page-size-002-print.html`?

**Comment by mstensho** [comment]
Chromium has never used 0.5 as default margins for WPT reftests, and that was the issue that I wanted to clarify, before adding code for it.

I'll change it to use 0.5 inch margins:

https://chromium-review.googlesource.com/c/chromium/src/+/5067421

**Comment by jwatt** [comment]
Sorry, read "Chromium currently uses a page area size of 4 by 2 inches for WPT print reftests, assuming that there's a 0.5 inch margin on every side of a page box with the size of 5 by 3 inches" to mean that Chromium was assuming a 0.5 inch margin at that time. Anyway, as long as we'll be aligned now that sounds good. Thanks! :-)

**Comment by jwatt** [comment]
Fixed by 0e3f951468c57a6bf11d2d5ff08142c125e4593a. Thanks, Morten!
