### ISSUE TITLE
pointerrawupdate is expected not to work in non-secure contexts

### ISSUE THREAD

**Issue by pygy** [web-platform-tests/wpt#45097]
Hello, per https://www.w3.org/TR/pointerevents3/#the-pointerrawupdate-event, pointerrawupdate is only meant to work in pages served over HTTPS.

wpt apparently expects it to work in non-secure contexts, which is thus wrong IIUC.

https://wpt.fyi/results/pointerevents/pointerevent_pointerrawupdate.html?label=experimental&label=master

**Comment by atjn** [comment]
As far as I can tell, the test you are linking to is checking to make sure that no `pointerrawupdate` events have been fired, exactly because it is a non-secure context. This quote is from [the source code](https://github.com/web-platform-tests/wpt/blob/master/pointerevents/pointerevent_pointerrawupdate.html):
> This test checks that pointerrawupdate is not dispatched on non-SecureContext.

But you are correct that the test name is wrong. I have made a pull request to fix that :)
