### ISSUE TITLE
listitem should not be exposed as generic if it is rendered as a list item visually

### ISSUE THREAD

**Issue by tranjocelyn** [web-platform-tests/wpt#45715]
In `html-aam/roles-generic.html`, there is a listitem that is expected to be exposed as a generic role:

```
<li data-testname="el-li-orphaned" class="ex-generic">x</li>
```

However, when `roles-generic.html` is loaded in the browser, that listitem is rendered as a listitem (there is a bullet next to the `x`). We should render the same thing to screen users as well, i.e., we should expose the list item as a list item, not a generic.

**Comment by aleventhal** [comment]
+1. If the a11y tree is stricter than the overall rendering engine, then AT users will get a different experience from everyone else.

**Comment by aleventhal** [comment]
@scottaohara @jcsteh @cookiecrook looking for opinions.

**Comment by scottaohara** [comment]
https://github.com/w3c/html-aam/pull/540

if the `li` is used incorrectly (e.g., not within a `ul`, `ol` or `menu`) then it should not be a listitem.  This would be similar to if someone had done `<p>&bullet; whatever....</p>`

but per some clarifications that were added to the HTML AAM PR I added, if the markup structure is as follows:
```
<ul>
  <div> <!-- invalid HTML but doesn't cause the parser to restructure the DOM -->
     <li> _this_ should still be a list item since it's accessibility parent is a list (ul element) </li>
      ...
  </div>
</ul>
```

**Comment by aleventhal** [comment]
> if the li is used incorrectly (e.g., not within a ul, ol or menu) then it should not be a listitem. 

I'm not sure I 100% agree because this could break existing content.

I don't think it's a good idea that if an author specified an `<li>` that we change how we've been exposing it for over a decade. I don't want to deal with all the regressions. It will be busy work with no real user benefit. IMO We should let this go instead of being semantic stalinists :)

**Comment by aleventhal** [comment]
@jcsteh Since Firefox is already doing this, I'm fine with it if it hasn't caused issues with existing content, or you see it as an improvement. I've just had a lot of times where well-meaning changes like this cause a regression in Slack, and we don't find out until it's in a stable version.

**Comment by jcsteh** [comment]
Honestly, I don't personally agree with the orphaned roles stuff at all. I think they should all be authoring requirements, not enforced by the UA. However, the spec and tests disagree - see https://github.com/web-platform-tests/interop-accessibility/issues/109 - and we didn't feel it was worth pushing for this to be changed, assuming it had been specified this way for good reason. So, we implemented according to the spec.

FWIW, I haven't seen any regressions in the wild since we implemented this, either personally or bugs filed by others, but that doesn't mean there aren't any.

**Comment by jcsteh** [comment]
CC @nmlapre.

**Comment by jcsteh** [comment]
@nmlapre did remind me that this only landed in Nightly 6 days ago, which might be too short a time to say "there haven't been any regressions" with a great deal of certainty. I'll keep watching and update here if I spot any breakage in the wild, either personally or thanks to bug reports.

**Comment by scottaohara** [comment]
@jcsteh i'm surprised to hear you say that, because i'm using Firefox version 120 right now and looking at an orphaned `li` element in the a11y tree, it is reported as generic.  jaws and nvda treat it as such.   so i was under the impression this had been around for at least 5 versions, since i see the latest public release is firefox 125?

**Comment by jcsteh** [comment]
Ah, interesting. It seems that's true for `<li>`, but not, for example, `<div role="listitem">`. Markup elements are handled somewhat differently to ARIA roles and we had a specific code path to handle the orphaned `<li>` case. That was implemented [12 years ago](https://bugzilla.mozilla.org/show_bug.cgi?id=804461). Sheesh!

**Comment by nmlapre** [comment]
Minor addition to Jamie's comment: The 12-year-old code says that Gecko does this specific list item behavior ["to avoid text jamming"](https://searchfox.org/mozilla-central/rev/23ad6bdb310c9a46e6f37885b0d88ec5da3c00f7/accessible/base/nsAccessibilityService.cpp#1634). I landed the change for `role="listitem"` and friends [on the 10th](https://phabricator.services.mozilla.com/rMOZILLACENTRAL24a03f6f59b783fd2da519ce0755485296d479e5).

**Comment by scottaohara** [comment]
thank you both for clarifying.  

as this topic was only about the `li` element, i wasn't even thinking to check role=listitem and why i was so confused with what was being said vs what i had been seeing.  I even went back to the files i created for testing when I made the HTML AAM PR, and i had written down my results, stating "firefox already treats li elements as generic when incorrectly used outside of a list"

**Comment by jcsteh** [comment]
That's fair and I apologise for the confusion. Honestly, I had completely neglected to realise that this 12 year old code even existed. We needed to make additional changes (the ones landed on the 10th) to pass the other orphaned role WPT tests and I had incorrectly assumed those covered `<li>` as well.

**Comment by tranjocelyn** [comment]
thanks for the info everyone, this was very helpful.
