### ISSUE TITLE
WebKitGTK experimental runs missing since August 13

### ISSUE THREAD

**Issue by KyleJu** [web-platform-tests/wpt#47823]
The last run for WebKitGTK Experimental was August 13

https://wpt.fyi/runs?label=master&label=experimental&max-count=100&product=chrome&product=edge&product=firefox&product=safari&product=webkitgtk

@clopez could you take a look please?

**Comment by clopez** [comment]
The problem has been caused because an upgrade on the toolchain on the server generating the webkitgtk built-products also upgraded the libstdc++ version on the container and therefore the built-products generated are now incompatible with Ubuntu-20.04

Building webkitgtk requires gcc >= 11 nowadays and that is an issue as it is becoming increasingly hard to keep providing build-products for such old distro.

I think we should look into upgrading the docker container that is used for the WPT CI tests at taskcluster. Related: https://github.com/web-platform-tests/wpt/issues/43361

**Comment by clopez** [comment]
We are going to start providing a generic bundle that can work on any distro and has all the bleeding edge features enabled instead of providing a bundle with several features disabled to make it compile on an ancient distro like Ubuntu-20.04
To achieve that we will bundle all the required libraries instead of depending on the distro libraries.

I will submit a patch here to switch the WPT tooling to pull this new bundle once ready and that should make the webkitgtk runs work back as expected.

Work for shipping the new bundle tracked at https://bugs.webkit.org/show_bug.cgi?id=280523 and the bugs linked there in see-also

**Comment by clopez** [comment]
Ok, the new bundles are ready to be used and I submitted at https://github.com/web-platform-tests/wpt/pull/48698 the changes so the WPT taskcluster CI system start using them

**Comment by clopez** [comment]
The new bundle seems to be working as expected and the first result at TaskCluster completed here: https://wpt.fyi/results/?run_id=5131295269322752

This is a diff with the previous one from August: https://wpt.fyi/results/?diff&filter=ADC&run_id=5177350312689664&run_id=5131295269322752
Big diff as there has been lot of time in the between.

Some of the regressions may be caused by https://bugs.webkit.org/show_bug.cgi?id=281747
