### ISSUE TITLE
Changes to .tentative tests

### ISSUE THREAD

**Issue by annevk** [web-platform-tests/wpt#48258]
In https://github.com/web-platform-tests/wpt/commit/15c5ae88f39e8599f9b03ee523ddd4f89ab269d0 @dizhang168 with review from @tkent-google made quite major changes to a tentative test contributed by WebKit.

The rationale given was that the behavior wasn't standardized. But that's what .tentative means.

Could you please revert this change?

cc @foolip

**Comment by dizhang168** [comment]
The original test was only for Selection.direction, which is a new not fully standardized test that Webkit added. I agree it should be kept as tentative.
https://github.com/web-platform-tests/wpt/commit/55dd5fe143e41101ad9ad19e6171c2468dc960d2

However, the part I removed was for an addendum that Gecko made to test multi click (single, double and triple clicks).
https://github.com/web-platform-tests/wpt/commit/3af40b404cfb8ca6ef1b8866c8046e6fa9e49429
https://github.com/web-platform-tests/wpt/commit/04e0f3e72f4d9310e32fa3f003e6d31823a6b891

I looked into this and the click behavior is not specified. Because of OS differences, it is also hard to have this standardized:
https://github.com/w3c/selection-api/issues/70#issuecomment-607530902
https://github.com/w3c/selection-api/issues/177#issuecomment-2145397475

When this patch was landed, I did cc the OP to make sure they are aware and so they can correct me:
https://github.com/web-platform-tests/wpt/pull/47043#issuecomment-2215516313

If we still feel strong about keeping this part of the test in WPT, I can add it as a separate new file called selection-direction-on-clicks.tentative.html and make it clear that shipping selection.direction doesn't mean this test should become non-tentative.

**Comment by annevk** [comment]
If the expectation is that it can become non-tentative modulo a set of subtests, putting those subtests in a separate file seems like the best way forward indeed. Unless you have actual confirmation from the writer of the tests that removing them is okay. (Probably best done as a PR against WPT itself with them as reviewer.)

**Comment by dizhang168** [comment]
Thanks for the feedback. I have created the PR for it and asked @sefeng211's review: https://github.com/web-platform-tests/wpt/pull/48267

Note: I agree with you it is not good to remove a test without the original writer's approval. I did cc and gotten their approval in the original PR: https://github.com/web-platform-tests/wpt/pull/47043#issuecomment-2218386948

**Comment by dizhang168** [comment]
Closing this as I have re-added the subtests as "selection/Selection-direction-on-clicks.tentative.html".

**Comment by annevk** [comment]
Thanks @dizhang168 and apologies for not entirely appreciating the sequence of events here. Glad it was a misunderstanding.
