### ISSUE TITLE
Make sure all lints listed

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#5299]
Originally posted as https://github.com/gsnedders/wpt-docs/issues/18 by @gsnedders on 18 Jan 2017, 15:27 UTC:

> I'm pretty sure we don't have all the lints lists in the lint-tools documentation. We should.

**Comment by foolip** [comment]
http://web-platform-tests.org/writing-tests/lint-tool.html looks pretty complete to me. @gsnedders, can you find the missing ones?

**Comment by foolip** [comment]
Yep, @lukebjerring just noticed that MISSING_LINK isn't documented anywhere.

**Comment by jugglinmike** [comment]
We just merged gh-17189, so the online documentation of the lint tool now describes every available rule (including MISSING-LINK):

https://web-platform-tests.org/writing-tests/lint-tool.html

And because that list is programatically generated, we can have more confidence that the documentation will remain up-to-date as the rule set changes.
