### ISSUE TITLE
Padding in 'CSS2/css1/c412-blockw-000.xht'?

### ISSUE THREAD

**Issue by tgraham-antenna** [web-platform-tests/wpt#6960]
Is the '`padding-left: auto; padding-right: auto`' in 'CSS2/css1/c412-blockw-000.xht' (https://github.com/w3c/web-platform-tests/blob/master/css/CSS2/css1/c412-blockw-000.xht) an error or, as a carry-over from CSS1, is it trying to test the "Three of the seven properties can be set to 'auto'" statement from https://www.w3.org/TR/REC-CSS1/#horizontal-formatting?

**Comment by TalbotG** [comment]
'padding-left: auto; padding-right: auto'  are 2 invalid (invalid both in CSS1 and in CSS2.x) declarations. So, this definitely looks like an error to me. 

I must have reviewed that test because I made the reference file for it; so I may have reported something about that test in public-css-testsuite mailing list...

The "Three of the seven properties can be set to 'auto'" statement from 
https://www.w3.org/TR/REC-CSS1/#horizontal-formatting? 
are width, margin-left and margin-right.

**Comment by TalbotG** [comment]
Tony,

I propose to change
 'padding-left: auto; padding-right: auto' 
for
 'padding-left: 0; padding-right: 0' 

Otherwise I propose to add invalid flag to the test and then to add a comment between line 25 and 26 saying:
/* 
'padding-left' and 'padding-right' can only be specified with a <length> or a <percentage>; 'auto' is not a valid property value for 'padding-left' and 'padding-right' properties */

**Comment by tgraham-antenna** [comment]
It's been a while since I opened this issue, but I suspect that I found the possible rationale from CSS1 only because I was casting around for a reason for the test to be as it was.  Personally, I'm happy for the values to change to '0'.

**Comment by TalbotG** [comment]
Tony, I think I was unable to create pull requests back in May 2018 ... and then I must have forgot about this issue. 
Today, I went through a lot of emails and noticed this issue.
I am sorry for the wait.

Tony, if you see a mistake like this 'padding-left: auto' or of this sort in other CSS2 tests, please let me know. I have more time available in July 2019 and I can create pull requests now.

**Comment by TalbotG** [comment]
Over in PR 17592, all 10 Continuous Integration checks have passed. So, now, it is a matter of waiting for 1 among 6 reviewers to approve the pull request.

**Comment by frivoal** [comment]
Fixed thanks to #17592
