### ISSUE TITLE
How to handle mock or automated behavior?

### ISSUE THREAD

**Issue by wpt-issue-mover** [web-platform-tests/wpt#7156]
Originally posted as https://github.com/w3c/testharness.js/issues/85 by @scheib on 09 Oct 2014, 22:08 UTC:

> Some tests require the platform or user to be mock-ed or automated for tests to run on automated infrastructure. For example, Chromium LayoutTests have access to [TestRunner](https://code.google.com/p/chromium/codesearch#search/&sq=package:chromium&type=cs&q=file:/test_runner/test_runner.h) which exposes methods such as [window.testRunner.setMockScreenOrientation](https://code.google.com/p/chromium/codesearch#search/&sq=package:chromium&type=cs&q=\"setMockScreenOrientation\").
> 
> However, without care these tests will not function when used in other browsers, or with manual testing. One example are the Chromium Pointer Lock tests using [doNextStepWithUserGesture](https://code.google.com/p/chromium/codesearch#search/&sq=package:chromium&type=cs&q=doNextStepWithUserGesture) which allow automation to mock a user-gesture (e.g. mouse click/key press) but also provide a way for manual testers to progress tests.
> 
> Has design been discussed to extend testharness with a mock concept that browsers can populate and which when possible falls through to manual instructions?

**Comment by scheib** [comment]
In June 2017 discussions in several threads, and also a VC call, discussing Web Bluetooth, Web USB, and WebVR resulted in this [summary of specification with matching test APIs](https://lists.w3.org/Archives/Public/public-test-infra/2017AprJun/0080.html). I'll include the summary here:

> Related to this thread [Specifications with matching test APIs](https://www.w3.org/Search/Mail/Public/search?keywords=&hdr-1-name=subject&hdr-1-query=%22Specifications+with+matching+test+APIs%22&index-grp=Public_FULL&index-type=g&type-index=)
> and the earlier thread [UserAgent-specific files in Web Platform Tests](https://www.w3.org/Search/Mail/Public/search?keywords=&hdr-1-name=subject&hdr-1-query=%22UserAgent-specific+files+in+Web+Platform+Tests%22&index-grp=Public_FULL&index-type=g&type-index=)
> 
> This is a summary of a call discussing web platform testing with “Test
> APIs” including James Graham (Mozilla) and Philip Jägenstedt, Reilly Grant,
> Vincent Scheib (Google).
> 
> Web Bluetooth, WebUSB, and WebVR are actively seeking to develop web
> platform tests with new requirements compared to existing tests. Complex
> state must be configured for these features to be tested, e.g. fake
> bluetooth devices. “Test APIs” are proposed as being paired with
> specifications.
> 
> Concerns raised and discussed include:
> 
> A) With new testing patterns we may develop unexpected influence on future
> implementations. Particularly risky when only a small number of developers
> are influencing the API. E.g. WebUSB which doesn’t yet have other
> implementations.
> 
> B) WebDriver already operates at a high level, helping avoid test APIs
> being too implementation specific.
> 
> C) Test APIs that don’t work with browser’s standard shipping versions may
> be a problem. E.g. they won’t run with web-developer focused testing
> infrastructure, BrowserStack, Sauce, etc. And, they’re harder to run
> manually.
> 
> D) Our primary goal is to have conforming web browser implementations.
> Considering the goal of “Testing APIs should work for web-app developers”
> is lower priority.
> 
> Recommendations:
> 
> Test APIs should clearly indicate their purpose and scope:
> 
> - They are intended only for WPT. This means test APIs can be modified more
> freely if a later implementation discovers limitations in the testing API.
> We do not want additional resistance to API change due to e.g. web app
> developers using the test API.
> 
> - Test APIs should be designed carefully to only use concepts from the
> feature being tested, and not the details of the implementation. E.g.
> garbage collection, implementation specific feature details, synchronous
> responses, etc.

**Comment by RByers** [comment]
Note that [some support for automation](https://web-platform-tests.org/writing-tests/testdriver.html) is currently available and in regular use.  /cc @foolip

**Comment by foolip** [comment]
It's fun to see this old issue and that we've actually resolved half of it now. [doNextStepWithUserGesture](https://code.google.com/p/chromium/codesearch#search/&sq=package:chromium&type=cs&q=doNextStepWithUserGesture) is now supported. [`test_driver.bless()`](https://web-platform-tests.org/writing-tests/testdriver.html#bless) is the shorthand for it, but that's built on [`test_driver.click()`](https://web-platform-tests.org/writing-tests/testdriver.html#click) which you can also use.

We have [type:untestable](https://github.com/web-platform-tests/wpt/issues?q=is%3Aopen+is%3Aissue+label%3Atype%3Auntestable) issues for tracking missing capabilities, and there are many. For [window.testRunner.setMockScreenOrientation](https://code.google.com/p/chromium/codesearch#search/&sq=package:chromium&type=cs&q=\"setMockScreenOrientation\"), I think [No way to test sensor APIs](https://github.com/web-platform-tests/wpt/issues/9686) is the right issue, and @Honry is working on the API in https://github.com/w3c/sensors/pull/369.

For Web Bluetooth, WebUSB, and WebVR, a different form of mocking has emerged using Mojo JS. @Hexcles, is there a tracking page or issue for those capabilities?

Closing this issue now since the basic infrastructure (testdriver.js) is there, but I acknowledge there is much work to be done for specific APIs. Please file new issues for specifics and add the type:untestable label if you have them.
