### ISSUE TITLE
Look through TTWF tutorial and see if it has useful content

### ISSUE THREAD

**Issue by wpt-issue-mover** [web-platform-tests/wpt#7183]
Originally posted as https://github.com/w3c/testharness.js/issues/244 by @gsnedders on 15 Feb 2017, 17:32 UTC:

> This is https://github.com/w3c/testtwf-website-src/blob/f29957b16f1df126d0ee62cf133f4ef67d888c0e/docs/testharness-tutorial.md
> 
> It's currently not linked to from anywhere on the TTWF website or elsewhere in the documentation; we should merge this into our own website. It will soon be gone with a redirect to the API documentation which it mostly duplicates.
> 
> This is also https://github.com/w3c/testtwf-website/issues/123

**Comment by foolip** [comment]
I think the documentation of the different assertions looks pretty good, examples are useful. Maybe fold that into http://web-platform-tests.org/writing-tests/testharness-api.html?

**Comment by jugglinmike** [comment]
Most of the pages have referenced corresponding content within the WPT repository since 2014. I reviewed the external documentation [as it was published on 2014-08-22](https://github.com/w3c/testtwf-website-src/tree/3d67d44cf8e67607655fac1369cc10ae74dfc909) with the understanding that a lot has changed since then.

Most of the content is available in WPT's `docs` directory today. I classified the rest of the content as either "out of scope" (given that TTWF had different goals), "acceptable omission" (for content that is either outdated or not relevant), and "useful content" (for content that ought to be copied in to WPT's current documentation).

- [bugs.md](https://github.com/w3c/testtwf-website-src/blob/1f43dcc7eced6c1824ea662e82a6c93cb1034693/docs/bugs.md)
  - **out of scope**
- [faq.md](https://github.com/w3c/testtwf-website-src/blob/1f43dcc7eced6c1824ea662e82a6c93cb1034693/docs/faq.md)
  - **out-of-scope**
- [test-templates.md](https://github.com/w3c/testtwf-website-src/blob/485a73bd0eaae8e02b6f6adc17e18851c9718507/docs/test-templates.md)
  - **acceptable omission**: guidance on the formatting of metadata
  - **acceptable omission**: description of "reviewer" metadata
- [testharness-documentation.md](https://github.com/w3c/testtwf-website-src/blob/1f43dcc7eced6c1824ea662e82a6c93cb1034693/docs/testharness-documentation.md)
  - **acceptable omission**: description of "template code"--private testharness.js functions
- [testharness.js tutorial](https://github.com/w3c/testtwf-website-src/blob/f29957b16f1df126d0ee62cf133f4ef67d888c0e/docs/testharness-tutorial.md)
  - **useful content**: explanation of "one assertion violation per test"
  - **useful content**: description of `format_value` (a previously-undocumented testharness.js utility function)
  - **acceptable omission**: explanation of `testharnessreport.js` (this seems distracting for the typical contributor)
  - **acceptable omission**: incorrect claim about `<div id=log>`
  - **acceptable omission**: incorrect claim about setting `timeout` for synchronous tests
  - **acceptable omission**: [`vendor-prefix.js` pattern was removed on 2017-07-27](https://github.com/web-platform-tests/wpt/commit/4efe9f5bfe0eb84e3f131e7bb1d9bd91ad24c288)
  - **acceptable omission**: subtest-specific metadata is not generally declared today ([I could only find one set of tests which does](https://github.com/web-platform-tests/wpt/blob/424c4b83cbbe7dd792e83eebfcaa84d6e0c5826e/html/infrastructure/urls/resolving-urls/query-encoding/resources/resolve-url.js))
  - **acceptable omission**: outdated information on `setup` (describes unsupported `timeout` property; does not mention `timeout_multiplier` or `allow_uncaught_exception` properties)
- [test-a11y.md](https://github.com/w3c/testtwf-website-src/blob/1f43dcc7eced6c1824ea662e82a6c93cb1034693/docs/test-a11y.md)
  - **out of scope**

I've proposed new wordings that are intended to cover the same topics: gh-18303 and gh-18304

**Comment by foolip** [comment]
Thanks Mike! Feel free to close this issue when you like.

**Comment by jugglinmike** [comment]
We just merged both pull requests, so this is resolved
