### ISSUE TITLE
setrequestheader-content-type.htm is erroneously sending back an extra blank space back to the browser for empty headers.

### ISSUE THREAD

**Issue by wisniewskit** [web-platform-tests/wpt#7567]
This web platform test is checking that an empty Content-Type header is being sent by the UA, which both Firefox and Edge are actually doing. However, the test fails because it's returning a responseText with an extra space.

That is, when I have the test's python script `XMLHttpRequest/resources/inspect-headers.py` print out the `raw_headers.headers` it actually receives, the results are what the test expects: 'Content-Type: \r\n'

However, when I ask that same script to spit out the byte sequence (in decimal) it's going to pass back as the responseText it will be checking on the client-side, it gives:  67, 111, 110, 116, 101, 110, 116, 45, 84, 121, 112, 101, 58, 32, 32, 10

Note that extra space at the end. The test is accidentally fooling itself into thinking that Firefox (and probably Edge as well) are failing.

**Comment by wisniewskit** [comment]
@annevk, what should we do about this? It's still causing spurious test-failures. Changing a line in [inspect_headers.py](https://github.com/web-platform-tests/wpt/blob/master/xhr/resources/inspect-headers.py#L11) seems to do the trick, but I'm not 100% sure if that's what we'd want to do:
```
-        if len(value) > 1 and value[0] == ' ':
+        if len(value) and value[0] == ' ':
```

**Comment by annevk** [comment]
So it seems Chrome and Firefox are doing this differently. Firefox always ends with a space, but Chrome does not. E.g., I wanted to change this to the more strict
```python
if ': ' not in line:
  return "Syntax error: no colon and space found: " + line
name, value = line.split(': ', 1)
```
but that fails in Chrome as it won't include a space after the colon if the value is the empty string (but will otherwise).

I guess your fix is acceptable for now (though I'd change the `1` to `0` for clarity), but it would seem even better to me if everyone generates H/1 requests in the same normalized manner.

cc @MattMenke2 @ddragana

**Comment by MattMenke2** [comment]
How do other browsers behave?  I don't have a strong opinion on what the behavior should be, but agree it should be standardized.  I'd be happy to make the changes in Chrome, if needed (At least assuming it's a behavior within the network stack, as I suspect it is).  If Edge and Safari share behavior, I'd suggest going with that one, just because I assume it would be easier to get all browsers to switch to it.

**Comment by annevk** [comment]
I think apart from Chrome, every other browser always serializes a header line as `[header-name]: [header-value]`, whereas in Chrome the space after the colon is only serialized if there is a non-empty value, as far as I can tell.

Since it seems you're okay with aligning that I'll update the test to enforce that serialization more strictly.

**Comment by annevk** [comment]
I filed https://bugs.chromium.org/p/chromium/issues/detail?id=891251 against Chrome.
