### ISSUE TITLE
Unable to test ARIA/AAM bindings

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#7753]
@halindrome wrote some automation tool here (ATTA); we should have these automated out of the box running under `wptrunner`.

cc/ @joanmarie

**Comment by halindrome** [comment]
There are a number of factors that make it complicated...  but yes, it is possible.  @joanmarie has done most of the recent work on the ATTA end.   Obviously the ATTA itself is platform specific.  I think all of the current ones are written in Python.

**Comment by foolip** [comment]
Maybe @alice or @robdodson have ideas about how to test this?

I suspect there's a confusion of acronyms here, since https://wicg.github.io/aom/spec/ and the AAM specs aren't about different layers, so the title should maybe say ARIA/AAM? If so, a separate issue for any difficulties testing AOM would be nice.

**Comment by alice** [comment]
Yes, I suspect this was meant to be AAM rather than AOM. Not the first time I've seen them collide.

**Comment by foolip** [comment]
I've changed the title. @gsnedders, can you confirm that's what you intended?

**Comment by gsnedders** [comment]
Uh, yeah, we should probably have a separate issue for AOM.

**Comment by JKereliuk** [comment]
Are there existing manual tests that need this?

**Comment by gsnedders** [comment]
@JKereliuk everything in wai-aria, core-aam, dpub-aam, and dpub-aria

**Comment by joanmarie** [comment]
I'm hoping that once AOM gives us a means to examine the shared/platform-independent accessibility trees of user agents, that will solve ARIA, DPub ARIA, and any other ARIA that's not an AAM spec.

Testing the AAM specs requires an additional tool (the client-side, platform-specific ATTAs). And some of them have dependencies (e.g. in Linux, it turns out that if you don't have the latest versions of ATK and AT-SPI2, you can reliably crash user agents when running table-cell related tests). We also need to handle things like ensuring the assistive technology support is enabled when needed and disabled afterwards. All these are solvable problems, but we don't have the solutions ready to go quite yet. Sorry!!

**Comment by cookiecrook** [comment]
I think this one can be closed now with due to patches in #38758 and #38925

**Comment by cookiecrook** [comment]
@joanmarie wrote:

> I'm hoping that once AOM gives us a means to examine the shared/platform-independent accessibility trees of user agents, that will solve ARIA, DPub ARIA, and any other ARIA that's not an AAM spec.

See https://github.com/web-platform-tests/interop-2023-accessibility-testing/issues/21

**Comment by zcorpan** [comment]
Agreed, closing.
