### ISSUE TITLE
Move CSS Counter Styles reftests over from mozilla-central

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#8122]
See tests not beginning with t1202 in http://searchfox.org/mozilla-central/source/layout/reftests/counters

Note these don't cover all Counter Styles but they are reftests unlike the current visual tests.

**Comment by dbaron** [comment]
There are also the tests in [layout/reftests/counter-style/](https://searchfox.org/mozilla-central/source/layout/reftests/counter-style), which are more relevant to the spec for `@counter-style`.  This was discussed in the CSS meeting today.  /cc @upsuper @fantasai

**Comment by upsuper** [comment]
I had some patches locally for [Gecko bug 1134099](https://bugzilla.mozilla.org/show_bug.cgi?id=1134099) to upstream the counter style tests.

Had a look at patches considered done in my local repo, I think the main thing needs to be split off from upstreaming in `layout/reftests/counter-style/` would be length limitation of generated string. The spec says
> Some values of system (symbolic, additive) and some descriptors (pad) can generate representations with size linear to an author-supplied number. ... User agents must support representations at least 60 Unicode codepoints long, but they may choose to instead use the fallback style for representations that would be longer than 60 codepoints.

Gecko implements a larger limitation than this, and some tests check against that limitation.

Other than that, I guess majority (if not all) of tests in that directory should be fine to upstream.

I do have patches for separating and moving. I was stuck (due to lack of time / motivation) on splitting the tests into finer-grained tests. If that is not necessary, I guess those patches should be usable immediately.

**Comment by jgraham** [comment]
FWIW I would always favour upstreaming things sooner over blocking on work that may never happen, unless the tests actually don't work without that work. If you want to change the tests later that's always possible after they are upstream.

**Comment by upsuper** [comment]
One possible problem of not splitting them is the canvas area. Some of the tests may be long vertically, which may fit into Gecko's reftest canvas but not wpt's. That is something we may need to take care.

**Comment by gsnedders** [comment]
@upsuper has done this all in https://bugzilla.mozilla.org/show_bug.cgi?id=1134099

**Comment by gsnedders** [comment]
Ah, @upsuper only did those from /layout/reftests/counter-style/ and not /layout/reftests/counters/.

@upsuper are you still planning on submitting those from /layout/reftests/counters/ too? (At least those that aren't from some old version of the CSS testsuite and those that aren't UA-dependent.)
